//! Compiles `news/` into the binary.
//!
//! A news entry travels with the code that implements it. In Python that is a wheel and a
//! `force-include` of `docs/news` into `charter/_news`; here it is `include_str!`, and the
//! property is the same one `charter/news.py` states: *a control plane has no reason to vendor
//! a copy and every reason not to — a copy drifts from the binary, invisibly and in both
//! directions.* An app installed from a signed bundle has no checkout to fall back to, so
//! there is no second source to drift from in the first place.
//!
//! **The file list is read from the directory rather than written down.** A checked-in list
//! of 338 `include_str!` lines would be a second statement of what is in `news/`, free to
//! disagree with the directory the day somebody adds an entry — which is exactly the shape
//! this whole module is about.
//!
//! The order is the directory's, sorted, which is `sorted(d.glob("*.md"))` in Python: for one
//! directory that is the filename's order, and `news::all` re-sorts by version on top of it,
//! relying on a STABLE sort to leave equal-ranked entries where the filename put them.

use std::fmt::Write as _;
use std::path::Path;

fn main() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("news");
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut names: Vec<String> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()))
        .map(|entry| {
            entry
                .expect("cannot read an entry of news/")
                .file_name()
                .to_string_lossy()
                .into_owned()
        })
        .filter(|name| name.ends_with(".md"))
        .collect();
    names.sort();
    assert!(!names.is_empty(), "news/ holds no entries");

    let mut out = String::from(
        "/// Every news entry, as `(filename, text)`, in filename order. Generated by \
         `build.rs`.\npub static FILES: &[(&str, &str)] = &[\n",
    );
    for name in &names {
        let path = dir.join(name);
        println!("cargo:rerun-if-changed={}", path.display());
        // Rust string escapes for a path and a filename. Real entry names are
        // `[0-9a-z.-]` and the directory is the crate's own, but a generator that assumes
        // its input is quote-free is a generator that emits code that will not compile the
        // day it is not.
        writeln!(
            out,
            "    ({:?}, include_str!({:?})),",
            name,
            path.to_string_lossy()
        )
        .expect("writing to a String cannot fail");
    }
    out.push_str("];\n");

    let target =
        Path::new(&std::env::var("OUT_DIR").expect("cargo sets OUT_DIR")).join("news_entries.rs");
    std::fs::write(&target, out)
        .unwrap_or_else(|e| panic!("cannot write {}: {e}", target.display()));
}
