"""A plugin charter did not write must not pass as wired.

`ensure_shim` never repairs a file it finds — the restraint that protects an operator's
edits. It also means a plugin generated by 0.40.0, whose guard threw on every tool call
and failed open, survives every upgrade afterwards while `doctor` reports the tree wired.
That is this repo's oldest failure shape (#177, #197) arriving through charter's own
writer, and it is live for anyone who ran `charter init` before the fix.

So the generated shim carries the version that wrote it, and `refresh_shim` rewrites one
whose stamp is older. That stamp is a NAME, and for two releases it was the whole test:
line 1 is the one line an edit leaves alone, so a body with every guard cut out of it, or
with `#433`'s single line put back, reported the running version and got a clean `doctor`
row. #433 was a routing table nothing dispatched through; this is a version comment over a
program nothing guards.

`shim_is_charters` asks the identity question instead — is this file byte-for-byte the
program charter generates — and `refresh_shim`, `stale_wiring`, `upgrade` and `doctor`
all take their "yes, this is ours" from it. The restraint is unchanged in the direction
that matters: charter still never overwrites a shim carrying the running stamp. It stops
vouching for it.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from charter import __version__, doctor
from charter.harness import opencode, registry

_RUNTIME = shutil.which("bun") or shutil.which("node")
_DRIVER = Path(__file__).parent / "fixtures" / "opencode_driver.mjs"

#: The one line #433 was. Put this back and every opencode tool — `read` included — goes
#: to the Bash guard, which reads ``tool_input["command"]`` and never looks at `tool_name`,
#: so the vault-read guard is absent on the harness again.
_ROUTING_LINE = "const hook = own(PRE_HOOKS, tool) ?? DEFAULT_PRE_HOOK"
_ROUTING_GONE = 'const hook = "pretooluse"'


def _tree(case) -> Path:
    p = Path(tempfile.mkdtemp(prefix="charter-stale-"))
    case.addCleanup(lambda: shutil.rmtree(p, True))
    return p


class TheShimSaysWhoWroteIt(unittest.TestCase):
    def test_it_carries_the_generating_version(self):
        self.assertIn(__version__, opencode.SHIM)

    def test_the_stamp_is_machine_readable(self):
        tree = _tree(self)
        opencode.ensure_shim(tree)
        self.assertEqual(opencode.shim_version(tree), __version__)

    def test_an_unstamped_shim_reads_as_unknown_rather_than_current(self):
        """A shim from before the stamp existed is exactly the dangerous case — it must
        never be mistaken for one this charter wrote."""
        tree = _tree(self)
        p = tree / opencode.SHIM_PATH
        p.parent.mkdir(parents=True)
        p.write_text("export const CharterPlugin = async () => ({})\n")
        self.assertIsNone(opencode.shim_version(tree))

    def test_a_missing_shim_has_no_version_either(self):
        self.assertIsNone(opencode.shim_version(_tree(self)))


class StaleIsNotWired(unittest.TestCase):
    """One installed shim, so one thing to be stale about — reported on the harness row
    rather than a row per tree, which is the simplification the global install bought."""

    def _installed(self, version: str | None) -> Path:
        import os
        from unittest import mock
        home = _tree(self)
        self.env = mock.patch.dict(os.environ, {"XDG_CONFIG_HOME": str(home)})
        self.env.start(); self.addCleanup(self.env.stop)
        g = opencode.global_dir()
        opencode.ensure_shim(g)
        if version is not None:
            p = g / opencode.SHIM_PATH
            p.write_text(p.read_text().replace(__version__, version))
        return g

    def test_a_shim_an_older_charter_wrote_is_named(self):
        self._installed("0.40.0")
        self.assertEqual(opencode.shim_version(opencode.global_dir()), "0.40.0")

    def test_a_current_shim_reports_this_version(self):
        self._installed(None)
        self.assertEqual(opencode.shim_version(opencode.global_dir()), __version__)


class RefreshingIsDeliberate(unittest.TestCase):
    def test_refresh_replaces_a_stale_shim(self):
        tree = _tree(self)
        opencode.ensure_shim(tree)
        p = tree / opencode.SHIM_PATH
        p.write_text(p.read_text().replace(__version__, "0.40.0"))
        self.assertEqual(opencode.refresh_shim(tree), "refreshed")
        self.assertEqual(opencode.shim_version(tree), __version__)

    def test_refresh_leaves_an_edited_shim_alone(self):
        """An unstamped file is somebody else's, and charter will not touch it.

        It is not the only file charter will not touch — see
        :class:`TheStampIsANameNotAnIdentity` for the one that carries the running stamp
        over a body charter did not write. Both are left alone; only the reason differs.
        """
        tree = _tree(self)
        p = tree / opencode.SHIM_PATH
        p.parent.mkdir(parents=True)
        p.write_text("// mine\nexport const CharterPlugin = async () => ({})\n")
        self.assertEqual(opencode.refresh_shim(tree), "not-ours")
        self.assertIn("// mine", p.read_text())

    def test_refresh_writes_a_missing_shim(self):
        self.assertEqual(opencode.refresh_shim(_tree(self)), "created")


class TheStampIsANameNotAnIdentity(unittest.TestCase):
    """Keep line 1 and change anything below it, and charter used to vouch for the file.

    Reproduced against the version that shipped this file's previous docstring: install the
    shim, replace the one line #433 was — `const hook = own(PRE_HOOKS, tool) ??
    DEFAULT_PRE_HOOK` — with the literal `"pretooluse"`, and

        shim_version   -> 0.51.0
        refresh_shim   -> "current"
        stale_wiring   -> ""
        upgrade        -> ("current", "0.51.0")
        doctor         -> ok

    while every `read` on that harness went to the Bash guard, which never looks at
    `tool_name`. That is #433 back in full, under a green tick, and gutting the file
    entirely scored the same five answers.

    Round one of this audit guarded by a NAME and round two by a CHARACTER, and both were
    walked past by the same attack respelled. A version comment is a name. So the question
    every one of these answers now rests on is the file's IDENTITY — is this byte-for-byte
    the program charter generates — which no respelling gets past, because there is
    nothing in it to respell.
    """

    def _installed(self) -> Path:
        home = _tree(self)
        self.enterContext(mock.patch.dict(os.environ, {"XDG_CONFIG_HOME": str(home)}))
        g = opencode.global_dir()
        opencode.ensure_shim(g)
        return g

    def _plant(self, body: str) -> Path:
        g = self._installed()
        (g / opencode.SHIM_PATH).write_text(body)
        return g

    #: The two ways to keep the stamp and lose the guards. `_gutted` is the loud one;
    #: `_ROUTING_GONE` is the one nobody would notice in a diff, and is #433 verbatim.
    def _gutted(self) -> str:
        return (opencode.SHIM.splitlines()[0] + "\n"
                'export const CharterPlugin = async () => ({\n'
                '  "shell.env": async (i, o) => { o.env.CHARTER_HARNESS = "opencode" },\n'
                '})\n')

    def _unrouted(self) -> str:
        self.assertIn(_ROUTING_LINE, opencode.SHIM)   # a no-op edit would prove nothing
        return opencode.SHIM.replace(_ROUTING_LINE, _ROUTING_GONE, 1)

    def _bodies(self):
        return (("gutted", self._gutted()), ("unrouted", self._unrouted()))

    def test_the_stamp_still_reads_the_running_version(self):
        """Not a regression — the demonstration. `shim_version` answers what line 1 SAYS,
        and every one of these files says the running version. That is why nothing may be
        decided from it alone."""
        for label, body in self._bodies():
            with self.subTest(body=label):
                g = self._plant(body)
                self.assertEqual(opencode.shim_version(g), __version__)

    def test_a_body_charter_did_not_write_is_not_charters(self):
        for label, body in self._bodies():
            with self.subTest(body=label):
                self.assertFalse(opencode.shim_is_charters(self._plant(body)))

    def test_refresh_neither_vouches_for_it_nor_overwrites_it(self):
        """Two halves, and dropping either is a different bug: calling it "current" is the
        false tick, and rewriting it destroys an operator's deliberate edit."""
        for label, body in self._bodies():
            with self.subTest(body=label):
                g = self._plant(body)
                self.assertEqual(opencode.refresh_shim(g), "edited")
                self.assertEqual((g / opencode.SHIM_PATH).read_text(), body)

    def test_the_harness_row_says_what_it_is(self):
        for label, body in self._bodies():
            with self.subTest(body=label):
                self._plant(body)
                stale = registry.get("opencode").stale_wiring()
                self.assertTrue(stale)
                # It is dropped into "its plugin is …", so it has to read as a phrase and
                # must not be mistaken for a version number.
                self.assertIn(__version__, stale)
                self.assertNotEqual(stale, __version__)

    def test_upgrade_declines_and_says_why(self):
        for label, body in self._bodies():
            with self.subTest(body=label):
                g = self._plant(body)
                status, detail = registry.get("opencode").upgrade(Path("/unused"))
                self.assertEqual(status, "manual")
                self.assertIn("reinit", detail)
                self.assertEqual((g / opencode.SHIM_PATH).read_text(), body)

    def test_doctor_does_not_print_a_clean_row_over_it(self):
        for label, body in self._bodies():
            with self.subTest(body=label):
                self._plant(body)
                self.enterContext(
                    mock.patch.dict(os.environ, {"CHARTER_HARNESS": "opencode"}))
                r = doctor.check_harness()
                self.assertEqual(r.status, doctor.WARN)
                self.assertTrue(r.hint)

    def test_the_shim_charter_just_wrote_is_still_a_clean_row(self):
        """The other direction, and the one a too-clever identity check breaks: charter's
        own freshly written file must be vouched for, or every plane warns forever."""
        g = self._installed()
        self.assertTrue(opencode.shim_is_charters(g))
        self.assertEqual(opencode.refresh_shim(g), "current")
        self.assertEqual(registry.get("opencode").stale_wiring(), "")
        self.enterContext(mock.patch.dict(os.environ, {"CHARTER_HARNESS": "opencode"}))
        self.assertEqual(doctor.check_harness().status, doctor.OK)

    def test_no_single_changed_character_anywhere_survives(self):
        """The property, not a list of edits.

        Every previous round of this audit was defeated by one input the fix's list did not
        contain — one codepoint, one path spelling, one case change. So this does not
        enumerate mutations: it changes ONE character at a spread of offsets across the
        whole file, line 1 included, and asks the same question every time. There is no
        entry to leave out.
        """
        g = self._installed()
        p = g / opencode.SHIM_PATH
        src = opencode.SHIM
        offsets = list(range(0, len(src), 97))
        # A stride wider than a line would step over whole guards; a file that shrank to
        # nothing would make this vacuous. Both are the same failure — nothing tested.
        self.assertGreater(len(offsets), 50)
        for i in offsets:
            with self.subTest(offset=i):
                # `~` is not in the shim's alphabet anywhere, so this is a change at every
                # offset rather than a no-op wherever the original character matched.
                p.write_text(src[:i] + "~" + src[i + 1:])
                self.assertFalse(opencode.shim_is_charters(g))
                self.assertNotEqual(opencode.refresh_shim(g), "current")

    def test_a_truncated_shim_is_not_charters_either(self):
        """Byte-for-byte means length too. A half-written file — an interrupted copy, a
        full disk — keeps line 1 and loses whichever guard was at the end."""
        g = self._installed()
        (g / opencode.SHIM_PATH).write_text(opencode.SHIM[:len(opencode.SHIM) // 2])
        self.assertFalse(opencode.shim_is_charters(g))
        self.assertEqual(opencode.refresh_shim(g), "edited")


@unittest.skipIf(_RUNTIME is None, "neither bun nor node is installed")
class WhatTheStampVouchedForDoesNotRun(unittest.TestCase):
    """The consequence, executed rather than argued.

    `shim_is_charters` returning False is a claim about a file. This runs that exact file
    under a real JS runtime and reads back which handler it spawned, so the reason the
    stamp is not enough is a measurement: `read` on a vault reaches `charter hook
    pretooluse` — the Bash guard — instead of `pretooluse-read`.
    """

    def _dispatch(self, body: str) -> list[str]:
        d = Path(tempfile.mkdtemp(prefix="charter-stale-run-"))
        self.addCleanup(shutil.rmtree, d, True)
        (d / "charter.mjs").write_text(body)
        (d / "drive.mjs").write_text(_DRIVER.read_text())
        scenario = {"event": "before", "tool": "read", "directory": "/plane",
                    "sessionID": "s1", "reply": '{"hookSpecificOutput":{}}',
                    "args": {"filePath": ".charter/vaults/devops.json"}}
        proc = subprocess.run([_RUNTIME, "drive.mjs"], input=json.dumps([scenario]),
                              capture_output=True, text=True, timeout=120, cwd=d)
        self.assertEqual(proc.returncode, 0, proc.stderr)
        return [c["command"].split("charter hook ")[1].split()[0]
                for c in json.loads(proc.stdout)[0]["calls"]]

    def test_the_shim_charter_generates_reaches_the_vault_guard(self):
        self.assertEqual(self._dispatch(opencode.SHIM), ["pretooluse-read"])

    def test_the_one_line_change_under_a_current_stamp_does_not(self):
        """#433 exactly, and byte-identical to the file `shim_is_charters` refuses to
        vouch for in :class:`TheStampIsANameNotAnIdentity`."""
        self.assertIn(_ROUTING_LINE, opencode.SHIM)
        gutted = opencode.SHIM.replace(_ROUTING_LINE, _ROUTING_GONE, 1)
        self.assertEqual(self._dispatch(gutted), ["pretooluse"])
        self.assertEqual(gutted.splitlines()[0], opencode.SHIM.splitlines()[0])


if __name__ == "__main__":
    unittest.main()
