"""A shim charter wrote at an older version must not pass as wired.

`ensure_shim` never repairs a file it finds — the restraint that protects an operator's
edits. It also means a plugin generated by 0.40.0, whose guard threw on every tool call
and failed open, survives every upgrade afterwards while `doctor` reports the tree wired.
That is this repo's oldest failure shape (#177, #197) arriving through charter's own
writer, and it is live for anyone who ran `charter init` before the fix.

So the generated shim carries the version that wrote it, and `doctor` compares that stamp
to the running charter. Naming it is the whole job: charter still does not rewrite the
file, because it cannot tell an old generated shim from one somebody deliberately changed
— only that it is not what this charter would write.
"""

from __future__ import annotations

import shutil
import tempfile
import unittest
from pathlib import Path

from charter import __version__, doctor
from charter.harness import opencode, registry


def _tree(case) -> Path:
    p = Path(tempfile.mkdtemp(prefix="charter-stale-"))
    case.addCleanup(lambda: shutil.rmtree(p, True))
    return p


class TheShimSaysWhoWroteIt(unittest.TestCase):
    def test_it_carries_the_generating_version(self):
        self.assertIn(__version__, opencode.SHIM)

    def test_the_stamp_is_machine_readable(self):
        tree = _tree(self)
        opencode.ensure_shim(tree)
        self.assertEqual(opencode.shim_version(tree), __version__)

    def test_an_unstamped_shim_reads_as_unknown_rather_than_current(self):
        """A shim from before the stamp existed is exactly the dangerous case — it must
        never be mistaken for one this charter wrote."""
        tree = _tree(self)
        p = tree / opencode.SHIM_PATH
        p.parent.mkdir(parents=True)
        p.write_text("export const CharterPlugin = async () => ({})\n")
        self.assertIsNone(opencode.shim_version(tree))

    def test_a_missing_shim_has_no_version_either(self):
        self.assertIsNone(opencode.shim_version(_tree(self)))


class StaleIsNotWired(unittest.TestCase):
    def test_doctor_names_a_tree_whose_shim_is_older(self):
        tree = _tree(self)
        opencode.ensure_shim(tree)
        p = tree / opencode.SHIM_PATH
        p.write_text(p.read_text().replace(__version__, "0.40.0"))
        from unittest import mock
        with mock.patch.object(doctor, "_work_trees", return_value=[tree]):
            r = doctor.check_harness_trees()
        self.assertEqual(r.status, doctor.WARN)
        self.assertIn("0.40.0", r.detail)
        self.assertIn("reinit", r.hint)

    def test_a_current_shim_is_a_clean_row(self):
        tree = _tree(self)
        registry.get("opencode").wire_tree(tree)
        from unittest import mock
        with mock.patch.object(doctor, "_work_trees", return_value=[tree]):
            self.assertEqual(doctor.check_harness_trees().status, doctor.OK)


class RefreshingIsDeliberate(unittest.TestCase):
    def test_refresh_replaces_a_stale_shim(self):
        tree = _tree(self)
        opencode.ensure_shim(tree)
        p = tree / opencode.SHIM_PATH
        p.write_text(p.read_text().replace(__version__, "0.40.0"))
        self.assertEqual(opencode.refresh_shim(tree), "refreshed")
        self.assertEqual(opencode.shim_version(tree), __version__)

    def test_refresh_leaves_an_edited_shim_alone(self):
        """charter cannot tell an old generated shim from one somebody changed on purpose,
        so it only replaces a file it can still recognise as its own — one whose stamp is
        there and whose body is byte-for-byte what that version generated is not the test;
        an ABSENT stamp is the signal that a human has been here."""
        tree = _tree(self)
        p = tree / opencode.SHIM_PATH
        p.parent.mkdir(parents=True)
        p.write_text("// mine\nexport const CharterPlugin = async () => ({})\n")
        self.assertEqual(opencode.refresh_shim(tree), "not-ours")
        self.assertIn("// mine", p.read_text())

    def test_refresh_writes_a_missing_shim(self):
        self.assertEqual(opencode.refresh_shim(_tree(self)), "created")


if __name__ == "__main__":
    unittest.main()


class ReinitMakesTheHintTrue(unittest.TestCase):
    """`doctor` says "→ charter reinit". A hint that does not fix what it points at is
    worse than no hint: it spends the operator's trust and leaves the guard inert."""

    def test_reinit_refreshes_a_stale_tree(self):
        from charter import commands

        tree = _tree(self)
        opencode.ensure_shim(tree)
        p = tree / opencode.SHIM_PATH
        p.write_text(p.read_text().replace(__version__, "0.40.0"))
        commands.refresh_work_tree(tree)
        self.assertEqual(opencode.shim_version(tree), __version__)

    def test_reinit_does_not_overwrite_a_shim_someone_edited(self):
        from charter import commands

        tree = _tree(self)
        p = tree / opencode.SHIM_PATH
        p.parent.mkdir(parents=True)
        p.write_text("// mine\n")
        commands.refresh_work_tree(tree)
        self.assertEqual(p.read_text(), "// mine\n")
