"""A shim charter wrote at an older version must not pass as wired.

`ensure_shim` never repairs a file it finds — the restraint that protects an operator's
edits. It also means a plugin generated by 0.40.0, whose guard threw on every tool call
and failed open, survives every upgrade afterwards while `doctor` reports the tree wired.
That is this repo's oldest failure shape (#177, #197) arriving through charter's own
writer, and it is live for anyone who ran `charter init` before the fix.

So the generated shim carries the version that wrote it, and `doctor` compares that stamp
to the running charter. Naming it is the whole job: charter still does not rewrite the
file, because it cannot tell an old generated shim from one somebody deliberately changed
— only that it is not what this charter would write.
"""

from __future__ import annotations

import shutil
import tempfile
import unittest
from pathlib import Path

from charter import __version__, doctor
from charter.harness import opencode, registry


def _tree(case) -> Path:
    p = Path(tempfile.mkdtemp(prefix="charter-stale-"))
    case.addCleanup(lambda: shutil.rmtree(p, True))
    return p


class TheShimSaysWhoWroteIt(unittest.TestCase):
    def test_it_carries_the_generating_version(self):
        self.assertIn(__version__, opencode.SHIM)

    def test_the_stamp_is_machine_readable(self):
        tree = _tree(self)
        opencode.ensure_shim(tree)
        self.assertEqual(opencode.shim_version(tree), __version__)

    def test_an_unstamped_shim_reads_as_unknown_rather_than_current(self):
        """A shim from before the stamp existed is exactly the dangerous case — it must
        never be mistaken for one this charter wrote."""
        tree = _tree(self)
        p = tree / opencode.SHIM_PATH
        p.parent.mkdir(parents=True)
        p.write_text("export const CharterPlugin = async () => ({})\n")
        self.assertIsNone(opencode.shim_version(tree))

    def test_a_missing_shim_has_no_version_either(self):
        self.assertIsNone(opencode.shim_version(_tree(self)))


class StaleIsNotWired(unittest.TestCase):
    """One installed shim, so one thing to be stale about — reported on the harness row
    rather than a row per tree, which is the simplification the global install bought."""

    def _installed(self, version: str | None) -> Path:
        import os
        from unittest import mock
        home = _tree(self)
        self.env = mock.patch.dict(os.environ, {"XDG_CONFIG_HOME": str(home)})
        self.env.start(); self.addCleanup(self.env.stop)
        g = opencode.global_dir()
        opencode.ensure_shim(g)
        if version is not None:
            p = g / opencode.SHIM_PATH
            p.write_text(p.read_text().replace(__version__, version))
        return g

    def test_a_shim_an_older_charter_wrote_is_named(self):
        self._installed("0.40.0")
        self.assertEqual(opencode.shim_version(opencode.global_dir()), "0.40.0")

    def test_a_current_shim_reports_this_version(self):
        self._installed(None)
        self.assertEqual(opencode.shim_version(opencode.global_dir()), __version__)


class RefreshingIsDeliberate(unittest.TestCase):
    def test_refresh_replaces_a_stale_shim(self):
        tree = _tree(self)
        opencode.ensure_shim(tree)
        p = tree / opencode.SHIM_PATH
        p.write_text(p.read_text().replace(__version__, "0.40.0"))
        self.assertEqual(opencode.refresh_shim(tree), "refreshed")
        self.assertEqual(opencode.shim_version(tree), __version__)

    def test_refresh_leaves_an_edited_shim_alone(self):
        """charter cannot tell an old generated shim from one somebody changed on purpose,
        so it only replaces a file it can still recognise as its own — one whose stamp is
        there and whose body is byte-for-byte what that version generated is not the test;
        an ABSENT stamp is the signal that a human has been here."""
        tree = _tree(self)
        p = tree / opencode.SHIM_PATH
        p.parent.mkdir(parents=True)
        p.write_text("// mine\nexport const CharterPlugin = async () => ({})\n")
        self.assertEqual(opencode.refresh_shim(tree), "not-ours")
        self.assertIn("// mine", p.read_text())

    def test_refresh_writes_a_missing_shim(self):
        self.assertEqual(opencode.refresh_shim(_tree(self)), "created")


if __name__ == "__main__":
    unittest.main()
