"""`charter … | head` is normal shell usage, not a charter bug.

When a consumer stops reading, the next write raises BrokenPipeError. charter treated that
as an uncaught exception: it propagated, Python failed to flush at shutdown (exit 120), and
the crash reporter recorded a bug report about it.

Both halves are wrong. A pipe closed by its reader is a **condition** — the same category
`cli.main` already puts KeyboardInterrupt and ProcTimeout in, per the comment there: "a
condition, not a bug". charter did nothing wrong, so it must exit quietly and report
nothing.

Found by charter's own crash detector, unprompted, from a `| head -1` in an ordinary
session — which is the feature working exactly as intended, on itself.
"""
from __future__ import annotations

import unittest
from unittest import mock

from charter import cli, report
from tests._isolation import PersonaIso


class TestABrokenPipeIsACondition(PersonaIso):
    def test_it_does_not_record_a_bug_report(self):
        """The load-bearing one. A report per `| head` would bury real crashes under
        noise generated by ordinary shell usage."""
        with mock.patch("charter.commands.cmd_doctor", side_effect=BrokenPipeError(32, "Broken pipe")):
            cli.main(["doctor"])
        self.assertEqual(report.pending(), [])

    def test_it_does_not_propagate(self):
        """It used to escape `main`, so Python failed to flush at shutdown and the process
        exited 120 — a number that means nothing to anyone reading it."""
        with mock.patch("charter.commands.cmd_doctor", side_effect=BrokenPipeError(32, "Broken pipe")):
            rc = cli.main(["doctor"])
        self.assertIsInstance(rc, int)

    def test_it_reports_the_conventional_sigpipe_status(self):
        """128 + SIGPIPE, matching the 128 + SIGINT that KeyboardInterrupt already
        returns here, so a caller reading exit codes sees one consistent scheme."""
        with mock.patch("charter.commands.cmd_doctor", side_effect=BrokenPipeError(32, "Broken pipe")):
            self.assertEqual(cli.main(["doctor"]), 141)

    def test_a_real_bug_is_still_recorded(self):
        """Guards the guard: this must narrow what counts as a bug, not switch it off."""
        with mock.patch("charter.commands.cmd_doctor", side_effect=ValueError("boom")):
            with self.assertRaises(ValueError):
                cli.main(["doctor"])
        self.assertEqual(len(report.pending()), 1)

    def test_a_keyboard_interrupt_still_returns_its_own_status(self):
        with mock.patch("charter.commands.cmd_doctor", side_effect=KeyboardInterrupt):
            self.assertEqual(cli.main(["doctor"]), 130)


if __name__ == "__main__":
    unittest.main()
