//! `charter docs generate`: the plane's generated docs, written from the plane's own files.
//! Python's `commands.cmd_docs` and `commands.refresh_readme_personas`.
//!
//! Two files, and they are different in kind:
//!
//! - `docs/topology.md` is **charter's**, whole. It carries a banner saying so and is
//!   rewritten from `inventory/repos.json` every time.
//! - `README.md` is the **operator's**. charter owns the span between two markers in it and
//!   nothing else — and a README that carries no markers is not touched at all, not even
//!   appended to (`roster::splice`).
//!
//! # This writes into the plane, so every path is gated as ITSELF
//!
//! `inventory/` and `docs/` are not data directories, and `contain::writable` answers for
//! `personas/`, `workspaces/` and `persona-state` only — so the gate here is
//! [`crate::inventory::in_plane`], asked of the exact file about to be opened and never of
//! the directory above it. A committed `docs -> /elsewhere` is refused rather than followed,
//! and so is a `README.md` that is a link out.
//!
//! **Python gates neither, and that is a divergence on purpose.** `cmd_docs` calls
//! `Path.write_text` on both, so a plane carrying a committed `docs` or `README.md` link
//! writes through it — into a file the plane does not contain, with content charter
//! generated. Here that is said and skipped. The exit status still follows Python's, so the
//! refusal is a warning an operator acts on rather than a second difference stacked on the
//! first.

use std::collections::BTreeSet;
use std::path::Path;

use serde_json::Value;

use super::{Say, Sink};
use crate::forge::{self, py_str};
use crate::{dispatch, inventory, roster};

/// The generated-file banner `docs/topology.md` opens with. `render.BANNER`.
const BANNER: &str =
    "<!-- GENERATED by `charter docs` from inventory/repos.json — do not edit by hand. -->";

/// `charter docs generate`, and the second half of `charter discover`.
///
/// Returns the exit status Python's `cmd_docs` returns: 1 for an inventory it will not
/// render from, 1 when a persona's memory store could not be listed (charter #1084 — the
/// topology is written either way, and the exit says the roster could not be refreshed),
/// else 0. `discover` ignores it, exactly as Python's `cmd_discover` ignores `cmd_docs`'s.
pub fn docs(root: &Path, group: &str, say: Sink) -> u8 {
    let doc = match inventory::load(root, group) {
        Ok(doc) => doc,
        Err(why) => {
            say(Say::Warn(why));
            return 1;
        }
    };
    let repos = inventory::listed(&doc);
    if repos.is_empty() {
        say(Say::Warn(
            "Inventory is empty — run `charter discover` first.".into(),
        ));
        return 1;
    }
    let at = root.join("docs").join("topology.md");
    let written = inventory::in_plane(root, &at).and_then(|()| {
        std::fs::create_dir_all(root.join("docs"))
            .and_then(|()| std::fs::write(&at, topology_md(group, &repos) + "\n"))
            .map_err(|e| format!("could not write {}: {e}", at.display()))
    });
    match written {
        Ok(()) => say(Say::Done(format!(
            "Generated docs/topology.md ({} repos)",
            repos.len()
        ))),
        Err(why) => say(Say::Warn(why)),
    }
    match refresh_readme(root, &mut *say) {
        Roster::Rewrote => {
            say(Say::Done(
                "Refreshed the persona roster block in README.md".into(),
            ));
            0
        }
        Roster::Unchanged => 0,
        Roster::Unread => 1,
    }
}

/// What happened to the README's roster block.
enum Roster {
    /// The block changed and the file was written.
    Rewrote,
    /// Nothing to do, or nothing charter may do: no README, no markers, an identical block,
    /// a file it could not read or write, or one that resolves out of the plane.
    Unchanged,
    /// A persona's memory store could not be listed, so no count was taken and the file was
    /// left alone. Named, and the exit says so.
    Unread,
}

/// Rewrite the marked roster block in `README.md`. Python's `refresh_readme_personas`.
///
/// **Best effort, and silent about the ordinary absences.** A plane with no README, or with
/// a hand-written one carrying no markers, is not a plane with a problem — charter says
/// nothing and changes nothing. The two things it DOES say are the two an operator has to
/// act on: a store it could not list, and a path that leads out of the plane.
fn refresh_readme(root: &Path, say: Sink) -> Roster {
    let at = root.join("README.md");
    if let Err(why) = inventory::in_plane(root, &at) {
        // Only for a README that is actually there: a plane with none has nothing to refuse,
        // and `in_plane` answers about where a path LANDS, which for an absent file is the
        // plane itself. Said here because the alternative is charter writing the operator's
        // roster into a file outside the plane, quietly.
        if std::fs::symlink_metadata(&at).is_ok() {
            say(Say::Warn(why));
        }
        return Roster::Unchanged;
    }
    let Ok(current) = std::fs::read_to_string(&at) else {
        return Roster::Unchanged;
    };
    // The MARKERS are looked for before any persona is read, because Python's
    // `splice_personas` returns before it calls `personas_md` — so a plane with no block
    // pays nothing, and an unreadable memory store in one costs nothing either.
    if !roster::has_block(&current) {
        return Roster::Unchanged;
    }
    let plane = crate::workspaces::Plane::open(root);
    let names = plane.personas().unwrap_or_default();
    let counts = dispatch::tally(root);
    let (rows, unread) = roster::rows(root, &names, &counts);
    if !unread.is_empty() {
        // `workspace.say_unread`: one sentence each, and then the README is left alone. A
        // count charter did not take has no business being committed as a number.
        for (path, code) in &unread {
            say(Say::Fail(crate::memstore::cannot_check(root, path, *code)));
        }
        return Roster::Unread;
    }
    let (generic, total) = dispatch::generic_share(&counts);
    let Some(new) = roster::splice(&current, &roster::block(&rows, generic, total)) else {
        return Roster::Unchanged;
    };
    if new == current {
        return Roster::Unchanged;
    }
    match std::fs::write(&at, new) {
        Ok(()) => Roster::Rewrote,
        Err(_) => Roster::Unchanged,
    }
}

/// A table cell: pipes escaped, newlines flattened, stripped. Python's `render._cell`.
fn cell(text: &str) -> String {
    inventory::py_strip(&text.replace('|', "\\|").replace('\n', " ")).to_string()
}

fn field(record: &Value, key: &str) -> String {
    py_str(record.get(key).unwrap_or(&Value::Null))
}

/// `docs/topology.md`. Python's `render.topology_md`.
pub fn topology_md(group: &str, repos: &[Value]) -> String {
    let mut repos: Vec<&Value> = repos.iter().collect();
    repos.sort_by_key(|r| field(r, "name"));
    // GitHub repos live in an "org", GitLab's in a "group"; a mixed or empty inventory has
    // no one right word and stays neutral.
    let kinds: BTreeSet<String> = repos
        .iter()
        .filter_map(|r| r.get("forge"))
        .filter(|f| !f.is_null())
        .map(py_str)
        .collect();
    let label = match kinds.iter().next() {
        Some(kind) if kinds.len() == 1 => match forge::Kind::parse(kind) {
            Some(k) => format!("{} {}", k.display(), k.owner_noun()),
            None => "group".to_string(),
        },
        _ => "group".to_string(),
    };
    let mut out = vec![
        BANNER.to_string(),
        String::new(),
        "# Repository Topology".to_string(),
        String::new(),
        format!(
            "**{} repos** in the `{group}` {label}. Refresh with `charter discover`.",
            repos.len()
        ),
        String::new(),
        "> Repos are cloned on demand into `workspaces/<workspace>/<name>/` (gitignored). This \
         list is complete even when nothing is cloned."
            .to_string(),
        String::new(),
        "| Repo | Kind | Stack | Branch | Description |".to_string(),
        "| --- | --- | --- | --- | --- |".to_string(),
    ];
    for r in repos {
        let description = match r.get("description") {
            Some(Value::String(s)) => cell(s),
            Some(v) if forge::truthy(v) => cell(&py_str(v)),
            _ => String::new(),
        };
        out.push(format!(
            "| `{}` | {} | {} | `{}` | {} |",
            field(r, "name"),
            field(r, "kind"),
            field(r, "stack"),
            field(r, "default_branch"),
            description
        ));
    }
    out.push(String::new());
    out.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn the_topology_is_pythons_table_with_a_forge_accurate_heading() {
        let repos = vec![
            json!({"name": "widget", "kind": "app", "stack": "rust", "default_branch": "trunk",
                   "description": "The widget — made well", "forge": "github"}),
            json!({"name": "legacy", "kind": "app", "stack": "unknown", "default_branch": "master",
                   "description": "x|y\nz", "forge": "github"}),
        ];
        let md = topology_md("acme", &repos);
        assert_eq!(
            md,
            "<!-- GENERATED by `charter docs` from inventory/repos.json — do not edit by hand. -->\n\
             \n\
             # Repository Topology\n\
             \n\
             **2 repos** in the `acme` GitHub org. Refresh with `charter discover`.\n\
             \n\
             > Repos are cloned on demand into `workspaces/<workspace>/<name>/` (gitignored). \
             This list is complete even when nothing is cloned.\n\
             \n\
             | Repo | Kind | Stack | Branch | Description |\n\
             | --- | --- | --- | --- | --- |\n\
             | `legacy` | app | unknown | `master` | x\\|y z |\n\
             | `widget` | app | rust | `trunk` | The widget — made well |\n"
        );
    }

    #[test]
    fn a_mixed_inventory_says_group_rather_than_guessing_a_forge() {
        let repos = vec![
            json!({"name": "a", "forge": "github"}),
            json!({"name": "b", "forge": "gitlab"}),
        ];
        assert!(topology_md("acme", &repos).contains("in the `acme` group."));
    }

    /// A plane with one repo in its inventory and whatever README the caller plants.
    fn plane(readme: Option<&str>) -> tempfile::TempDir {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        std::fs::write(root.join("charter.toml"), "").unwrap();
        std::fs::create_dir_all(root.join("inventory")).unwrap();
        std::fs::write(
            root.join("inventory/repos.json"),
            r#"{"group": "acme", "count": 1, "repos": [{"name": "widget", "kind": "app",
               "stack": "rust", "default_branch": "main", "description": "", "forge": "github"}]}"#,
        )
        .unwrap();
        let persona = root.join("personas/steward");
        std::fs::create_dir_all(persona.join("memory")).unwrap();
        std::fs::write(
            persona.join("persona.md"),
            "---\nname: steward\n---\n\n# S\n",
        )
        .unwrap();
        if let Some(text) = readme {
            std::fs::write(root.join("README.md"), text).unwrap();
        }
        dir
    }

    fn run(root: &Path) -> (u8, Vec<Say>) {
        let mut said = Vec::new();
        let code = docs(root, "acme", &mut |line| said.push(line));
        (code, said)
    }

    #[test]
    fn the_topology_is_written_and_a_readme_with_no_block_is_untouched() {
        let dir = plane(Some("# Mine\n\nHand written.\n"));
        let (code, said) = run(dir.path());

        assert_eq!(code, 0);
        assert_eq!(
            said,
            [Say::Done("Generated docs/topology.md (1 repos)".into())]
        );
        assert_eq!(
            std::fs::read_to_string(dir.path().join("README.md")).unwrap(),
            "# Mine\n\nHand written.\n",
            "charter owns the block and nothing else"
        );
        assert!(
            std::fs::read_to_string(dir.path().join("docs/topology.md"))
                .unwrap()
                .contains("| `widget` |")
        );
    }

    #[test]
    fn a_marked_readme_keeps_everything_outside_the_markers() {
        let readme = format!(
            "# Mine\n\nBefore.\n\n{}\nstale\n{}\n\n## After\n",
            roster::BEGIN,
            roster::END
        );
        let dir = plane(Some(&readme));
        let (code, said) = run(dir.path());

        assert_eq!(code, 0);
        assert!(
            said.contains(&Say::Done(
                "Refreshed the persona roster block in README.md".into()
            )),
            "{said:?}"
        );
        let now = std::fs::read_to_string(dir.path().join("README.md")).unwrap();
        assert!(now.starts_with("# Mine\n\nBefore.\n\n"), "{now}");
        assert!(now.ends_with("\n\n## After\n"), "{now}");
        assert!(
            now.contains("## Personas — roster & routing health"),
            "{now}"
        );
        assert!(!now.contains("stale"), "{now}");

        // A second run has nothing to change, and says nothing — git stays quiet on a no-op.
        let (code, said) = run(dir.path());
        assert_eq!(code, 0);
        assert_eq!(
            said,
            [Say::Done("Generated docs/topology.md (1 repos)".into())]
        );
    }

    #[test]
    fn an_empty_inventory_is_refused_rather_than_rendered_as_an_empty_table() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("charter.toml"), "").unwrap();
        let (code, said) = run(dir.path());

        assert_eq!(code, 1);
        assert_eq!(
            said,
            [Say::Warn(
                "Inventory is empty — run `charter discover` first.".into()
            )]
        );
        assert!(!dir.path().join("docs").exists(), "nothing was written");
    }

    #[test]
    #[cfg(unix)]
    fn a_persona_memory_store_it_cannot_list_stops_the_write_and_is_named() {
        // charter #1084: `Path.glob` answered `[]` for a directory it may not list, so a
        // count nobody took went into a COMMITTED file as a zero. The roster is left exactly
        // as it was, the directory is named, and the exit says the roster is stale.
        use std::os::unix::fs::PermissionsExt;
        let readme = format!("{}\nstale\n{}\n", roster::BEGIN, roster::END);
        let dir = plane(Some(&readme));
        let store = dir.path().join("personas/steward/memory");
        std::fs::set_permissions(&store, std::fs::Permissions::from_mode(0o000)).unwrap();
        let listable = std::fs::read_dir(&store).is_ok();
        let (code, said) = run(dir.path());
        // Restored before the assertions, so a failure still leaves a removable tree.
        std::fs::set_permissions(&store, std::fs::Permissions::from_mode(0o700)).unwrap();

        assert!(
            !listable,
            "this test needs a process that cannot read a 000 directory; as root every \
             directory is listable and it would pass without asking anything"
        );
        assert_eq!(code, 1, "the exit says the roster could not be refreshed");
        assert!(
            said.iter()
                .any(|line| matches!(line, Say::Fail(f) if f.contains("cannot be checked"))),
            "{said:?}"
        );
        assert!(
            std::fs::read_to_string(dir.path().join("README.md"))
                .unwrap()
                .contains("stale"),
            "the block charter could not count is the block it leaves alone"
        );
    }

    #[test]
    #[cfg(unix)]
    fn a_docs_directory_that_leads_out_of_the_plane_is_refused_not_followed() {
        // Python calls `Path.write_text` here with no containment check at all, so this
        // exact plane has it write charter's generated topology into a directory the plane
        // does not contain. `docs/` is not a data directory, so the gate is `in_plane`,
        // asked of the FILE — a check on the directory above it sees nothing to object to.
        let dir = plane(None);
        let elsewhere = tempfile::tempdir().unwrap();
        std::os::unix::fs::symlink(elsewhere.path(), dir.path().join("docs")).unwrap();
        let (code, said) = run(dir.path());

        assert_eq!(code, 0, "the roster half still ran");
        assert!(
            said.iter().any(|line| matches!(line, Say::Warn(w)
                if w.contains("resolves outside the plane"))),
            "{said:?}"
        );
        assert!(
            !elsewhere.path().join("topology.md").exists(),
            "the link was not followed"
        );
    }

    #[test]
    #[cfg(unix)]
    fn a_readme_that_leads_out_of_the_plane_is_refused_not_followed() {
        let dir = plane(None);
        let elsewhere = tempfile::tempdir().unwrap();
        let outside = elsewhere.path().join("README.md");
        let readme = format!("{}\nstale\n{}\n", roster::BEGIN, roster::END);
        std::fs::write(&outside, &readme).unwrap();
        std::os::unix::fs::symlink(&outside, dir.path().join("README.md")).unwrap();
        let (code, said) = run(dir.path());

        assert!(
            said.iter().any(|line| matches!(line, Say::Warn(w)
                if w.contains("resolves outside the plane"))),
            "{said:?}"
        );
        assert_eq!(
            std::fs::read_to_string(&outside).unwrap(),
            readme,
            "the operator's file outside the plane is not charter's to rewrite"
        );
        assert_eq!(code, 0, "Python exits 0 here, and so does this");
    }
}
