import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // `src/bindings.ts` is generated by tauri-specta; a test in the app crate guards it.
  { ignores: ["dist", "src-tauri", "src/bindings.ts"] },
  {
    files: ["**/*.{ts,tsx}"],
    extends: [
      js.configs.recommended,
      ...tseslint.configs.strict,
      reactHooks.configs.flat["recommended-latest"],
    ],
    languageOptions: { globals: globals.browser },
  },
);
