//! `charter change push`: every member's branch pushed, its request opened or found, and the
//! change's cross-link block spliced into each request's description (ADR 0060 §4; the
//! Python spec's §8.2 "EXTEND" answer, `charter/commands_change.py` at `cli-final`).
//!
//! **Membership is committed; destination is local.** The record names repos and branches and
//! never a place. Where each member goes, its forge, its repository path and its HTTPS push
//! URL, is read from the member's own clone's `origin`, which the operator put there by hand.
//! Every destination is printed before anything is pushed, so an agent's run is readable.
//!
//! **What it never does.** It commits nothing, and it never force-pushes: each push is the one
//! refspec `refs/heads/<branch>:refs/heads/<branch>`, with no `+` and no flag, so it can only
//! fast-forward the remote's branch or create it. It ignores a repo's `[repos.<name>] mode`,
//! `off` included: `off` governs saves, and this verb is run by hand over repos somebody named
//! (ADR 0060 D4, ADR 0051 amended).
//!
//! **Fire and report.** One member's failure is said and the rest still run: a third member
//! with no clone is no reason to leave the first two unpushed. A member charter reached and
//! could not open a request for is a `—` row of the block, never a missing one, because a
//! table without it says the change has fewer members than it has.
//!
//! **The block is charter's; the rest of the description is not.** Charter writes only
//! between [`BLOCK_BEGIN`] and [`BLOCK_END`]. A request whose description lacks exactly one
//! pair of them, outside any code fence, is left exactly as it is and named.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use super::cmd::{REFUSED, load, named, workspace_ok};
use super::record::{Record, TEXT_LIMIT};
use crate::forge::pr::{Pr, Repo, State};
use crate::forge::{self, Caller, ForgeBackend};
use crate::repocmd::Say;
use crate::shown;
use crate::tui::{self, Align};
use crate::worktree::git;

/// The line that opens charter's block in a request's description. Python's `BLOCK_BEGIN`,
/// kept to the byte, so a request the Python charter opened is spliced the same way.
pub const BLOCK_BEGIN: &str =
    "<!-- BEGIN charter change — GENERATED by `charter change push`; do not edit by hand. -->";
/// The line that closes it.
pub const BLOCK_END: &str = "<!-- END charter change -->";

/// A markdown fence, either spelling. A marker inside one is prose about the block, not the
/// block, and splicing there would rewrite an example somebody wrote out.
const FENCES: [&str; 2] = ["```", "~~~"];

/// One table cell: contained to one line first, so a `why` cannot become a second row, then
/// markdown's column separator escaped, so it cannot become a second column.
fn cell(value: &str) -> String {
    shown::one_line(value, TEXT_LIMIT).replace('|', "\\|")
}

/// A member charter reached: its request's number, and where that request lives.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Reached {
    pub number: u64,
    /// The repository's path on its forge: `owner/name`, or a GitLab namespace.
    pub path: String,
    /// `#` on GitHub, `!` on GitLab: per member, since one workspace can hold both.
    pub sigil: &'static str,
}

/// The block charter writes into every member's request: the change, why, and one row per
/// member with its request, or `—` for a member charter could not reach.
pub fn block(record: &Record, reached: &BTreeMap<String, Reached>) -> String {
    let mut lines = vec![
        BLOCK_BEGIN.to_string(),
        format!(
            "**Cross-repo change: `{}`** — {}",
            cell(&record.change),
            cell(&record.why)
        ),
        String::new(),
        "| repo | request | needs |".to_string(),
        "|---|---|---|".to_string(),
    ];
    for m in &record.members {
        let at = reached.get(&m.repo).map_or_else(
            || "—".to_string(),
            |r| format!("{}{}{}", cell(&r.path), r.sigil, r.number),
        );
        let needs = if m.needs.is_empty() {
            "—".to_string()
        } else {
            m.needs
                .iter()
                .map(|n| cell(n))
                .collect::<Vec<_>>()
                .join(", ")
        };
        lines.push(format!("| {} | {at} | {needs} |", cell(&m.repo)));
    }
    lines.push(BLOCK_END.to_string());
    lines.join("\n")
}

/// `body` with the region between charter's markers replaced by `block`, or `None` — a
/// refusal, not a fallback — when the markers are absent, when either appears more than
/// once, when they are out of order, or when either sits inside a code fence.
pub fn splice(body: &str, block: &str) -> Option<String> {
    let lines: Vec<&str> = body.lines().collect();
    let (mut begins, mut ends) = (Vec::new(), Vec::new());
    let (mut fence, mut fenced) = (false, false);
    for (i, line) in lines.iter().enumerate() {
        if FENCES.iter().any(|f| line.trim().starts_with(f)) {
            fence = !fence;
        }
        if line.contains(BLOCK_BEGIN) {
            begins.push(i);
            fenced |= fence;
        }
        if line.contains(BLOCK_END) {
            ends.push(i);
            fenced |= fence;
        }
    }
    let ([begin], [end]) = (begins.as_slice(), ends.as_slice()) else {
        return None;
    };
    if fenced || begin > end {
        return None;
    }
    let mut out: Vec<&str> = lines[..*begin].to_vec();
    out.extend(block.lines());
    out.extend_from_slice(&lines[end + 1..]);
    Some(out.join("\n"))
}

/// The description charter writes when it opens a request: the change's `why`, and its block
/// with no request in it yet, so the splice that follows has its markers to find.
fn new_body(record: &Record) -> String {
    format!(
        "{}\n\n{}",
        cell(&record.why),
        block(record, &BTreeMap::new())
    )
}

/// Where one member goes, resolved from its clone before anything is pushed.
struct Plan {
    repo: String,
    branch: String,
    clone: PathBuf,
    on: Repo,
    https: String,
    base: Option<String>,
}

/// One member that could not be planned: a refusal (2) or something wrong (1).
enum Unplanned {
    Refused,
    Failed,
}

fn plan(
    plane: &Path,
    ws: &str,
    repo: &str,
    branch: &str,
    say: &mut dyn FnMut(Say),
) -> Result<Plan, Unplanned> {
    let Some(clone) = crate::repos::clone_at(plane, ws, repo) else {
        say(Say::Fail(format!(
            "{}: no clone in workspace '{ws}', so it is not pushed.",
            named(repo)
        )));
        say(Say::Info(format!(
            "Clone it first: charter clone {} -w {ws}",
            named(repo)
        )));
        return Err(Unplanned::Refused);
    };
    let fail = |say: &mut dyn FnMut(Say), why: String| {
        say(Say::Fail(format!("{}: {}", named(repo), shown::line(&why))));
        Unplanned::Failed
    };
    let on = Repo::of_clone(plane, &clone.path).map_err(|why| fail(say, why))?;
    let Some(https) = crate::planegit::origin_https_of(plane, &clone.path) else {
        return Err(fail(
            say,
            "its origin is not a GitHub or GitLab URL charter can push to over HTTPS".into(),
        ));
    };
    let local = git::run(
        &clone.path,
        &[
            "rev-parse",
            "--verify",
            "--quiet",
            &format!("refs/heads/{branch}"),
        ],
        git::READ,
    );
    if !local.is_ok_and(|run| run.ok()) {
        return Err(fail(
            say,
            format!(
                "its clone has no branch {}. Create it there, or set the member's branch in \
                 workspaces/{ws}/changes/<slug>.json",
                named(branch)
            ),
        ));
    }
    let base = crate::reposave::default_branch(plane, repo, &clone.path);
    Ok(Plan {
        repo: repo.to_string(),
        branch: branch.to_string(),
        clone: clone.path,
        on,
        https,
        base,
    })
}

/// `charter change push <slug>`, through each member's forge's own backend.
pub fn push(plane: &Path, ws: &str, slug: &str, say: &mut dyn FnMut(Say)) -> u8 {
    push_with(plane, ws, slug, &|repo: &Repo| repo.backend(), say)
}

/// [`push`], asking the backend `backend_of` builds for each member's repo.
pub fn push_with(
    plane: &Path,
    ws: &str,
    slug: &str,
    backend_of: &dyn Fn(&Repo) -> Box<dyn ForgeBackend>,
    say: &mut dyn FnMut(Say),
) -> u8 {
    if !workspace_ok(plane, ws, say) {
        return 1;
    }
    let record = match load(plane, ws, slug, say) {
        Ok(record) => record,
        Err(code) => return code,
    };
    if record.members.is_empty() {
        say(Say::Fail(format!("change {} has no members.", named(slug))));
        say(Say::Info(format!(
            "Add one: charter change add {} <repo>",
            named(slug)
        )));
        return REFUSED;
    }
    let (mut refused, mut failed) = (0usize, 0usize);
    let mut plans = Vec::new();
    for m in &record.members {
        match plan(plane, ws, &m.repo, &m.branch, say) {
            Ok(p) => plans.push(p),
            Err(Unplanned::Refused) => refused += 1,
            Err(Unplanned::Failed) => failed += 1,
        }
    }
    let names: Vec<String> = plans.iter().map(|p| shown::line(&p.repo)).collect();
    let w = tui::column("", names.iter().map(String::as_str), 0, None);
    if !plans.is_empty() {
        say(Say::Info(format!(
            "Pushing {} member(s) of '{slug}'. Nothing is committed and nothing is forced:",
            plans.len()
        )));
    }
    for (p, name) in plans.iter().zip(&names) {
        let into = p.base.as_deref().map_or_else(String::new, |b| {
            format!(", its request into {}", shown::line(b))
        });
        say(Say::Out(format!(
            "  {}  {} → {}{into}",
            tui::pad(name, w, Align::Left),
            shown::line(&p.branch),
            shown::line(&p.https)
        )));
    }

    let caller = Caller::command();
    let mut reached: BTreeMap<String, Reached> = BTreeMap::new();
    let mut backends: BTreeMap<String, (Box<dyn ForgeBackend>, Pr)> = BTreeMap::new();
    for (p, name) in plans.iter().zip(&names) {
        let named_row = tui::pad(name, w, Align::Left);
        if !pushed(p, say) {
            failed += 1;
            continue;
        }
        let backend = backend_of(&p.on);
        let found = match backend.by_head(&caller, &p.on.path, &p.branch) {
            Ok(found) => found,
            Err(why) => {
                say(Say::Fail(format!(
                    "{}: pushed, but charter could not ask for its request: {}",
                    named(&p.repo),
                    shown::line(&why.to_string())
                )));
                failed += 1;
                continue;
            }
        };
        let sigil = p.on.forge.kind.change_sigil();
        let (pr, verb, standing) = match found {
            Some(req) => (
                Pr {
                    number: req.number,
                    url: req.url,
                },
                "pushed",
                (req.state != State::Open)
                    .then(|| format!(" ({})", super::observe::standing(&req.state))),
            ),
            None => {
                let Some(base) = p.base.as_deref() else {
                    say(Say::Fail(format!(
                        "{}: pushed, but charter does not know its default branch, so it \
                         cannot say where a request goes. Run: git -C {} remote set-head \
                         origin --auto",
                        named(&p.repo),
                        shown::line(&p.clone.display().to_string())
                    )));
                    failed += 1;
                    continue;
                };
                let title = format!("{}: {}", cell(&record.change), cell(&p.repo));
                match backend.open_or_update(
                    &caller,
                    &p.on.path,
                    &p.branch,
                    base,
                    &title,
                    &new_body(&record),
                ) {
                    Ok(opened) => (opened.pr, "opened", None),
                    Err(why) => {
                        say(Say::Fail(format!(
                            "{}: pushed, but its request into {} was not opened: {}",
                            named(&p.repo),
                            shown::line(base),
                            shown::line(&why.to_string())
                        )));
                        failed += 1;
                        continue;
                    }
                }
            }
        };
        say(Say::Done(format!(
            "{named_row}  {verb} → {sigil}{}{}  {}",
            pr.number,
            standing.unwrap_or_default(),
            shown::line(&pr.url)
        )));
        reached.insert(
            p.repo.clone(),
            Reached {
                number: pr.number,
                path: p.on.path.clone(),
                sigil,
            },
        );
        backends.insert(p.repo.clone(), (backend, pr));
    }

    let block = block(&record, &reached);
    let (mut written, mut current) = (0usize, 0usize);
    for (repo, (backend, pr)) in &backends {
        let path = &reached[repo].path;
        let sigil = reached[repo].sigil;
        let body = match backend.body(&caller, path, pr) {
            Ok(body) => body,
            Err(why) => {
                say(Say::Fail(format!(
                    "{}: {sigil}{}'s description could not be read: {}",
                    named(repo),
                    pr.number,
                    shown::line(&why.to_string())
                )));
                failed += 1;
                continue;
            }
        };
        let Some(spliced) = splice(&body, &block) else {
            say(Say::Fail(format!(
                "{}: {sigil}{}'s description has no single charter block outside a code \
                 fence, so charter left it as it is. Charter writes only between its own \
                 markers.",
                named(repo),
                pr.number
            )));
            failed += 1;
            continue;
        };
        if spliced == body.lines().collect::<Vec<_>>().join("\n") {
            current += 1;
            continue;
        }
        match backend.set_body(&caller, path, pr, &spliced) {
            Ok(()) => written += 1,
            Err(why) => {
                say(Say::Fail(format!(
                    "{}: {sigil}{}'s cross-link block was not written: {}",
                    named(repo),
                    pr.number,
                    shown::line(&why.to_string())
                )));
                failed += 1;
            }
        }
    }
    if written > 0 {
        say(Say::Done(format!(
            "cross-link block written into {written} request description(s)"
        )));
    }
    if current > 0 {
        say(Say::Info(format!(
            "cross-link block already current in {current} request description(s)"
        )));
    }
    if failed > 0 {
        1
    } else if refused > 0 {
        REFUSED
    } else {
        0
    }
}

/// Push one member's branch to its own name on its origin, and nothing else. `false` with
/// git's own words said when the remote refused it.
fn pushed(p: &Plan, say: &mut dyn FnMut(Say)) -> bool {
    let refspec = format!("refs/heads/{0}:refs/heads/{0}", p.branch);
    let helper = forge::helper_for(&p.on.forge);
    let run = match git::run_network(&p.clone, Some(&helper), &["push", &p.https, &refspec]) {
        Ok(run) => run,
        Err(unavailable) => {
            say(Say::Fail(format!(
                "{}: not pushed: {unavailable}",
                named(&p.repo)
            )));
            return false;
        }
    };
    if !run.ok() {
        let all = if run.err.trim().is_empty() {
            &run.out
        } else {
            &run.err
        };
        let last = all
            .lines()
            .rev()
            .find(|l| !l.trim().is_empty() && !l.trim_start().starts_with("hint:"))
            .unwrap_or("git said nothing");
        say(Say::Fail(format!(
            "{}: not pushed: {}",
            named(&p.repo),
            shown::line(last)
        )));
        return false;
    }
    // Kept in step, so the clone's own view of its remote matches what it now holds.
    let _ = git::run(
        &p.clone,
        &[
            "update-ref",
            &format!("refs/remotes/origin/{}", p.branch),
            &format!("refs/heads/{}", p.branch),
        ],
        git::READ,
    );
    true
}

#[cfg(test)]
mod tests;
