//! `charter persona sync-agents` — one Claude Code sub-agent per persona, generated into
//! `.claude/agents/<name>.md` — a port of `commands_persona.cmd_persona_sync_agents`,
//! `_render_agent`, `_write_agent` and `_approve_mcp`.
//!
//! # The generated file is compared byte for byte
//!
//! These files are committed in the operator's planes, and a re-sync that changed one byte of
//! one of them would be a diff on every plane the first time charter-app ran it. So the
//! rendering is Python's to the byte — frontmatter order, the marker line, every sentence of
//! the brief — and two tests hold that: the recorded scenarios, whose expected files Python
//! wrote, and `crates/charter-cli/tests/sync_agents_corpus.rs`, which re-syncs a real plane's
//! personas and compares against what that plane has committed.
//!
//! # Sources follow the tree, identity stays with the plane
//!
//! Run from a linked worktree of the plane, a generation reads that worktree's `personas/`
//! and writes that worktree's `.claude/agents/` (charter#678): the artifact belongs to the
//! branch. What this machine approved (the MCP record) and this machine's vault registry
//! stay the plane's — `config.in_tree`'s one exception. So every function here takes `root`
//! (the tree the sources are read from and the agents written into) and `state` (the plane's
//! state directory) separately.

use std::collections::BTreeMap;
use std::io::{BufRead, IsTerminal};
use std::path::{Path, PathBuf};

use crate::repocmd::{Say, Sink};

use super::{Resolved, mcp};

/// The marker every generated agent carries; a file without it is hand-written and never
/// charter's to touch.
pub const MARKER: &str = "GENERATED by `charter persona sync-agents`";

/// One y/N question on a terminal: `Some(answer)`, or `None` when the operator interrupted.
pub type Ask<'a> = &'a mut dyn FnMut(&str) -> Option<bool>;

/// [`confirm_on_terminal`]'s question, owned.
pub type Confirm = Box<dyn FnMut(&str) -> Option<bool>>;

/// Frontmatter keys copied straight into the generated agent — `AGENT_PASSTHROUGH_KEYS`.
const PASSTHROUGH: [&str; 3] = ["model", "color", "memory"];

/// Where the generated agents live, under the tree.
pub fn agents_dir(root: &Path) -> PathBuf {
    root.join(".claude").join("agents")
}

/// `_yaml_str`: newlines to spaces, stripped, then double-quoted with `\` and `"` escaped.
fn yaml_str(text: &str) -> String {
    let flat = text.replace('\n', " ");
    let flat = crate::memstore::py_strip(&flat);
    format!("\"{}\"", flat.replace('\\', "\\\\").replace('"', "\\\""))
}

/// `_agent_description`: what the router reads when it chooses an agent.
fn description(root: &Path, state: &Path, name: &str, meta: &BTreeMap<String, String>) -> String {
    let role = meta.get("role").map(String::as_str).unwrap_or(name);
    let when = meta
        .get("delegate-when")
        .map(|w| crate::memstore::py_strip(w))
        .unwrap_or("");
    let tools = meta.get("tools");
    let vault = super::vault_of(root, state, name);
    let mut tail = match (tools, vault) {
        (Some(tools), Some(vault)) => {
            format!(" Runs {tools} and pulls credentials from the '{vault}' vault.")
        }
        (Some(tools), None) => format!(" Runs {tools}. Holds no credentials of its own."),
        (None, Some(vault)) => format!(" Pulls credentials from the '{vault}' vault."),
        (None, None) => " Holds no credentials of its own.".to_string(),
    };
    if isolates(meta) {
        tail.push_str(
            " Runs in its own git worktree — it writes code, and parallel dispatches would \
             otherwise share one working tree.",
        );
    }
    if !when.is_empty() {
        format!("The {role} persona. Delegate to it for {when}.{tail}")
    } else {
        format!(
            "The {role} persona. Delegate {} tasks to it.{tail}",
            role.to_lowercase()
        )
    }
}

fn isolates(meta: &BTreeMap<String, String>) -> bool {
    meta.get("dispatch-isolation")
        .is_some_and(|v| crate::memstore::py_strip(v) == "worktree")
}

/// `_credential_rule`: the one-credential rule, in the words of THIS plane's forge CLIs.
fn credential_rule(root: &Path) -> String {
    let forges = crate::forge::load_config(root)
        .ok()
        .and_then(|cfg| crate::forge::to_query(&cfg).ok())
        .unwrap_or_else(|| {
            vec![(
                crate::forge::Forge::default_of(crate::forge::Kind::GitLab),
                String::new(),
                Vec::new(),
            )]
        });
    let clis: std::collections::BTreeSet<&str> =
        forges.iter().map(|(f, _, _)| f.kind.cli()).collect();
    let clis: Vec<&str> = clis.into_iter().collect();
    if let [cli] = clis.as_slice() {
        return format!(
            "**🔑 git = the {cli} token over HTTPS. Never SSH, never signing.** Repos are \
             pre-configured, so a plain `git push` works. If git ever asks for a key or \
             passphrase, run `charter git-policy --apply` — don't reach for SSH \
             (`{cli} auth status` checks the credential)."
        );
    }
    let joined = clis
        .iter()
        .map(|c| format!("`{c}`"))
        .collect::<Vec<_>>()
        .join(" / ");
    let checks = clis
        .iter()
        .map(|c| format!("`{c} auth status`"))
        .collect::<Vec<_>>()
        .join(" / ");
    format!(
        "**🔑 git = each repo's own forge's CLI token over HTTPS ({joined}). Never SSH, never \
         signing.** Repos are pre-configured, so a plain `git push` works. If git ever asks \
         for a key or passphrase, run `charter git-policy --apply` — don't reach for SSH \
         (check the credential with {checks})."
    )
}

/// `_render_agent`: the whole generated file for `name`, from its resolved definition.
pub fn render(root: &Path, state: &Path, name: &str, def: &Resolved) -> String {
    let meta = &def.meta;
    let role = meta
        .get("role")
        .cloned()
        .unwrap_or_else(|| super::py_title(name));
    let desc = meta
        .get("agent-description")
        .or_else(|| meta.get("description"))
        .cloned()
        .unwrap_or_else(|| description(root, state, name, meta));
    let mut fm = vec![
        format!("name: {name}"),
        format!("description: {}", yaml_str(&desc)),
    ];

    let (servers, _) = mcp::declared(root, name);
    let vault_key = meta.get("vault").map(String::as_str);

    if let Some(tools) = meta.get("agent-tools") {
        let grants: Vec<String> = servers
            .keys()
            .filter(|s| mcp::name_ok(s) && !tools.contains(&format!("mcp__{s}")))
            .map(|s| format!("mcp__{s}__*"))
            .collect();
        if grants.is_empty() {
            fm.push(format!("tools: {tools}"));
        } else {
            fm.push(format!("tools: {}, {}", tools, grants.join(", ")));
        }
    }
    let skills = super::declared_skills(root, name);
    if !skills.is_empty() {
        fm.push(format!("skills: {}", skills.join(", ")));
    }
    if isolates(meta) {
        fm.push("isolation: worktree".into());
    }
    if let Some(denied) = meta
        .get("disallowed-tools")
        .map(|d| crate::memstore::py_strip(d))
        .filter(|d| !d.is_empty())
    {
        fm.push(format!("disallowedTools: {denied}"));
    }
    if !servers.is_empty() {
        fm.push("mcpServers:".into());
        let approved = mcp::approved(state, name);
        let mut names: Vec<&String> = servers.keys().collect();
        names.sort();
        for server in names {
            let entry = mcp::render_entry(vault_key, &servers[server], &approved);
            let mut one = serde_json::Map::new();
            one.insert(server.clone(), entry);
            // `contain.json_line`: `json.dumps` with its default separators and
            // `ensure_ascii`, which is what keeps one server on one physical line.
            fm.push(format!(
                "  - {}",
                crate::pyjson::dumps(&serde_json::Value::Object(one), None, ", ", ": ")
            ));
        }
    }
    for key in PASSTHROUGH {
        if let Some(value) = meta.get(key) {
            fm.push(format!("{key}: {value}"));
        }
    }

    let memory_note = if meta.contains_key("memory") {
        format!(
            "\n- **Two memory stores, different jobs.** `.claude/agent-memory/{name}/` is the \
             generic Claude-agent memory (user / feedback / project / reference). Your durable \
             domain knowledge — the team-shared, committed base — lives in \
             `personas/{name}/memory/` and is reached with `charter recall`. **Search \
             charter's first**; write there for anything a teammate would want, and keep the \
             generic store to what isn't already in it."
        )
    } else {
        String::new()
    };

    let scripts = crate::personagrant::bin_scripts(root, name);
    let bin_note = if scripts.is_empty() {
        String::new()
    } else {
        let listed = scripts
            .values()
            .map(|path| {
                format!(
                    "  - `{}`",
                    crate::shown::readable(&super::rel(root, path), crate::memstore::PATH_LIMIT)
                )
            })
            .collect::<Vec<_>>()
            .join("\n");
        format!(
            "\n- **You carry your own executables.** Run them by path, not by name:\n{listed}\n  \
             A bare name is refused by the tool guard — it resolves through PATH, which charter \
             cannot vouch for."
        )
    };

    let uses: Vec<String> = meta
        .get("uses")
        .map(String::as_str)
        .unwrap_or("")
        .split(',')
        .map(|u| crate::memstore::py_strip(u).to_string())
        .filter(|u| !u.is_empty() && u != name)
        .collect();
    let borrows = crate::personagrant::borrows_of(root, name);
    let mut uses_note = String::new();
    if !uses.is_empty() {
        let joined = uses
            .iter()
            .map(|u| format!("`{u}`"))
            .collect::<Vec<_>>()
            .join(", ");
        uses_note = if borrows.is_none() {
            format!(
                "\n- **You may also use these personas: {joined}.** Read their vault \
                 (`charter persona secret list --persona <name>`), run their tools, or \
                 delegate a sub-task to their sub-agent (Agent tool, `subagent_type: <name>`)."
            )
        } else {
            format!(
                "\n- **You may delegate to these personas: {joined}.** Hand them a sub-task \
                 (Agent tool, `subagent_type: <name>`). Their tools are not auto-approved for \
                 you, and their vaults are not yours to open — do not name one to `charter \
                 secret …`. That second half is a rule you keep, not a wall charter holds: \
                 nothing refuses the vault name (`docs/personas.md` → Reusing another persona), \
                 which is exactly why it is written here. That is what `borrows:` is for, and \
                 it is deliberate: doing their work yourself should cost more than handing it \
                 over."
            )
        };
    }
    if let Some(borrows) = borrows.filter(|b| !b.is_empty()) {
        let joined = borrows
            .iter()
            .map(|b| format!("`{b}`"))
            .collect::<Vec<_>>()
            .join(", ");
        uses_note.push_str(&format!(
            "\n- **You borrow from: {joined}.** Read their vault (`charter persona secret list \
             --persona <name>`) and run their tools without a prompt."
        ));
    }

    let handoff = "\n- **Outside your domain, hand off — don't guess with partial credentials.** \
                   Delegate to the owner via the Agent tool (`subagent_type: <persona>`; it runs \
                   with *its own* vault — you never see its secrets); `charter persona list` \
                   shows who owns what. Never `charter persona use` to switch the active \
                   persona — that's user-request-only.";

    let creds = if super::vault_of(root, state, name).is_some() {
        format!(
            "\n- **Credentials** come only from this persona's vault, and are **never \
             printed**:\n  `charter persona secret list --persona {name}` — use `exec`/`cp` to \
             consume a secret, never `--reveal`.\n  Run tools through it, e.g. `charter persona \
             secret exec --persona {name} --file KUBECONFIG=kubeconfig -- kubectl -n <ns> get \
             pods`"
        )
    } else {
        format!(
            "\n- **This persona holds no credentials** (`vault: {}`). Never read another \
             persona's vault, and never improvise with a credential you find in the \
             environment — if a task needs one, hand off to the persona that owns it.",
            super::NO_VAULT
        )
    };

    let rel = super::def_rel(root, name);
    let charter = &def.charter;
    let rule = credential_rule(root);
    let mem = format!(
        "\n## Memory\n- **Search before acting** — never bulk-read the indexes: `charter recall \
         \"<keywords>\"` searches\n  every base at once (your memory, shared, the active \
         workspace) and labels hits by source.\n- **Record what's durable** as you learn: \
         `charter persona remember {name} \"<one fact>\"` — one\n  curated idea each; \
         `--shared` if every persona benefits, `--ephemeral` for session scratch.\n  \
         Persistent memory commits + pushes itself immediately, so it reaches the team as you \
         write it.\n- **Never** put secrets in memory/refs — credentials live only in the vault."
    );
    let body = format!(
        "<!-- {MARKER} from {rel} — edit the persona, not this file. -->\n\nThis sub-agent acts \
         as the **{name}** persona — {role} — in an\nisolated context. Adopt the charter below \
         as your role.\n\n{charter}\n\n## As a persona sub-agent\n- \
         {rule}{creds}{bin_note}{uses_note}{memory_note}{handoff}\n- Follow the control \
         plane's conventions (see CLAUDE.md); report results concisely to the caller.\n{mem}\n"
    );
    format!("---\n{}\n---\n{body}", fm.join("\n"))
}

/// What happened to one persona's agent — `_write_agent`'s return.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Outcome {
    Written,
    /// A hand-written agent sits at the name, and was left alone.
    Skipped,
    /// `draft: true` — no agent, and a generated one from before is removed.
    Draft,
    /// A frontmatter key charter can prove was meant to be read and cannot read.
    Unreadable,
    /// The definition does not load.
    Missing,
}

/// `persona.key_issues`: the persona's OWN keys written twice or spelled in another case.
pub fn key_issues(root: &Path, name: &str) -> Vec<String> {
    let Some(pairs) = crate::personas::load(root, name) else {
        return Vec::new();
    };
    let mut counts: BTreeMap<&str, usize> = BTreeMap::new();
    for (key, _) in &pairs {
        *counts.entry(key.as_str()).or_default() += 1;
    }
    let mut issues = Vec::new();
    for (key, n) in &counts {
        if *n > 1 {
            issues.push(format!(
                "frontmatter key '{}' is declared more than once — charter keeps the LAST line \
                 and the first is lost before anything reads it. Two lines are a contradiction \
                 in the file, not a value to pick: delete one",
                crate::shown::short(key)
            ));
        }
    }
    for key in counts.keys() {
        if let Some(meant) = crate::personagrant::misspelled_key(key) {
            issues.push(format!(
                "frontmatter key '{}' is read by nothing — charter matches keys exactly, so \
                 this is not `{meant}:` and its value never reaches charter. Spell it \
                 `{meant}:`",
                crate::shown::short(key)
            ));
        }
    }
    issues
}

fn is_generated(path: &Path) -> bool {
    std::fs::read_to_string(path).is_ok_and(|t| t.contains(MARKER))
}

/// `_remove_agent`: remove a persona's GENERATED agent, never a hand-written one.
fn remove_agent(root: &Path, name: &str) -> bool {
    let path = agents_dir(root).join(format!("{name}.md"));
    if path.exists() && is_generated(&path) && crate::contain::within_plane(root, &path) {
        return std::fs::remove_file(&path).is_ok();
    }
    false
}

/// `_write_agent`: generate or refresh one persona's agent.
pub fn write_agent(root: &Path, state: &Path, name: &str, say: Sink) -> Outcome {
    let Some(def) = super::resolve(root, name) else {
        return Outcome::Missing;
    };
    if !key_issues(root, name).is_empty() {
        remove_agent(root, name);
        return Outcome::Unreadable;
    }
    if super::is_draft(root, name) {
        remove_agent(root, name);
        return Outcome::Draft;
    }
    let dir = agents_dir(root);
    let path = dir.join(format!("{name}.md"));
    if path.exists() && !is_generated(&path) {
        say(Say::Warn(format!(
            "{} exists and isn't generated — leaving the hand-written agent alone.",
            super::rel(root, &path)
        )));
        return Outcome::Skipped;
    }
    // Contained, where Python is not: a committed `.claude/agents/<name>.md` that is a link
    // out of the plane would otherwise be written THROUGH, into a file nobody reviewed.
    if !crate::contain::within_plane(root, &path) {
        say(Say::Warn(format!(
            "{} resolves out of the plane — leaving it alone.",
            super::rel(root, &path)
        )));
        return Outcome::Skipped;
    }
    let text = render(root, state, name, &def);
    if std::fs::create_dir_all(&dir).is_err() || std::fs::write(&path, text).is_err() {
        say(Say::Warn(format!(
            "could not write {} — nothing was generated for '{name}'.",
            super::rel(root, &path)
        )));
        return Outcome::Skipped;
    }
    Outcome::Written
}

/// What `sync-agents` was asked.
#[derive(Debug, Clone, Default)]
pub struct Options<'a> {
    pub persona: Option<&'a str>,
    pub approve_mcp: bool,
    pub yes: bool,
    pub dry_run: bool,
}

/// `charter persona sync-agents`, and its exit code.
///
/// `plane` is the plane; `cwd` is where the command was run, which decides the TREE the
/// generation reads and writes (see the module header). `ask` answers one y/N question on a
/// terminal; `None` when stdin is not one.
pub fn sync_agents(plane: &Path, cwd: &Path, options: &Options, ask: Option<Ask>, say: Sink) -> u8 {
    let state = super::state_dir(plane);
    let Some(tree) = crate::planegit::tree_of(plane, cwd) else {
        return sync_in(plane, &state, None, options, ask, say);
    };
    if !tree.join("personas").is_dir() && plane.join("personas").is_dir() {
        say(Say::Fail(format!(
            "{} is a worktree of the plane at {}, and carries no `personas/`. Generated \
             sub-agents belong to the tree that holds their sources, and this one holds none — \
             nothing was written. Run this in {}, or check out a branch that carries \
             `personas/`.",
            tree.display(),
            plane.display(),
            plane.display()
        )));
        return 1;
    }
    sync_in(&tree, &state, Some(plane), options, ask, say)
}

fn sync_in(
    root: &Path,
    state: &Path,
    plane: Option<&Path>,
    options: &Options,
    ask: Option<Ask>,
    say: Sink,
) -> u8 {
    let one = options.persona.filter(|p| !p.is_empty());
    if let Some(one) = one
        && let Some(refused) = crate::personas::name_refusal(root, one)
    {
        say(Say::Fail(refused));
        return 1;
    }
    let names: Vec<String> = match one {
        Some(one) => vec![one.to_string()],
        None => super::names(root),
    };
    if names.is_empty() {
        say(Say::Info(
            "No personas to sync. Add one first: write personas/<name>/persona.md.".into(),
        ));
        return 0;
    }
    if options.approve_mcp {
        let rc = approve_mcp(
            plane.unwrap_or(root),
            root,
            state,
            &names,
            options.yes,
            options.dry_run,
            ask,
            say,
        );
        if rc != 0 {
            return rc;
        }
    }

    let outcomes: Vec<(String, Outcome)> = names
        .iter()
        .map(|n| (n.clone(), write_agent(root, state, n, say)))
        .collect();
    let with = |o: Outcome| -> Vec<String> {
        outcomes
            .iter()
            .filter(|(_, got)| *got == o)
            .map(|(n, _)| n.clone())
            .collect()
    };
    let written = with(Outcome::Written);
    let drafts = with(Outcome::Draft);
    let unreadable = with(Outcome::Unreadable);
    let withheld: Vec<(String, Vec<(String, String)>)> = written
        .iter()
        .map(|n| (n.clone(), mcp::withheld(root, state, n)))
        .filter(|(_, v)| !v.is_empty())
        .collect();
    let refused: Vec<(String, Vec<String>)> = written
        .iter()
        .map(|n| (n.clone(), mcp::declared(root, n).1))
        .filter(|(_, v)| !v.is_empty())
        .collect();

    let mut removed: Vec<String> = Vec::new();
    let dir = agents_dir(root);
    if one.is_none() && dir.exists() {
        let existing = super::names(root);
        let mut files: Vec<PathBuf> = std::fs::read_dir(&dir)
            .map(|r| r.filter_map(Result::ok).map(|e| e.path()).collect())
            .unwrap_or_default();
        files.sort();
        for file in files {
            // `glob("*.md")`: by name, so `.md` itself (whose stem is `.md`) is one too.
            if !file
                .file_name()
                .is_some_and(|n| n.to_string_lossy().ends_with(".md"))
                || !file.is_file()
            {
                continue;
            }
            let Some(stem) = file.file_stem().map(|s| s.to_string_lossy().into_owned()) else {
                continue;
            };
            if !existing.contains(&stem)
                && is_generated(&file)
                && crate::contain::within_plane(root, &file)
                && std::fs::remove_file(&file).is_ok()
            {
                removed.push(stem);
            }
        }
    }

    let listed = if written.is_empty() {
        "none".to_string()
    } else {
        written.join(", ")
    };
    say(Say::Done(format!(
        "Synced {} persona sub-agent(s) → .claude/agents/ ({listed})",
        written.len()
    )));
    if let Some(plane) = plane {
        say(Say::Info(format!(
            "  written into the worktree you ran from: {}",
            dir.display()
        )));
        say(Say::Info(format!(
            "  the plane's own copy ({}) is untouched — it updates when this branch merges.",
            agents_dir(plane).display()
        )));
    }
    if !drafts.is_empty() {
        say(Say::Warn(format!(
            "Skipped {} draft persona(s): {} — an unfinished charter must not become a \
             sub-agent's system prompt. Finish it, drop the `draft: true` line, then re-run.",
            drafts.len(),
            drafts.join(", ")
        )));
    }
    if !unreadable.is_empty() {
        say(Say::Warn(format!(
            "Skipped {} persona(s) whose frontmatter charter cannot read: {}. A key spelled in \
             another case, or declared twice, is read by nothing — and `agent-tools:`, \
             `disallowed-tools:` and `draft:` are enforced by being PRESENT, so a misspelling \
             drops the allowlist, the denylist or the draft guard rather than narrowing \
             anything. No agent is generated until the key is fixed:",
            unreadable.len(),
            unreadable.join(", ")
        )));
        for n in &unreadable {
            for msg in key_issues(root, n) {
                say(Say::Info(format!("  {}: {msg}", crate::shown::short(n))));
            }
        }
    }
    if !removed.is_empty() {
        say(Say::Info(format!(
            "Removed stale generated agents: {}",
            removed.join(", ")
        )));
    }
    if !refused.is_empty() {
        let count: usize = refused.iter().map(|(_, v)| v.len()).sum();
        say(Say::Warn(format!(
            "Refused {count} MCP server name(s): a name is emitted into the generated agent's \
             YAML and into `mcp__<server>__*`, so it may hold only letters, digits, '_', '.' \
             and '-' (64 max). These servers are NOT declared in the agent:"
        )));
        for (n, bad) in &refused {
            for server in bad {
                say(Say::Info(format!("  {}", mcp::label(&[n, server]))));
            }
        }
        say(Say::Info(format!(
            "  Rename them in the persona's `{}` and re-run.",
            mcp::MCP_FILE
        )));
    }
    if !withheld.is_empty() {
        let count: usize = withheld.iter().map(|(_, v)| v.len()).sum();
        say(Say::Warn(format!(
            "Withheld the vault from {count} MCP server(s): the committed `mcp.json` names the \
             command that would receive it, and this one has not been approved on this machine."
        )));
        for (n, servers) in &withheld {
            for (server, line) in servers {
                let line = if line.is_empty() {
                    mcp::UNRENDERABLE
                } else {
                    line
                };
                say(Say::Info(format!(
                    "  {} → {line}",
                    mcp::label(&[n, server])
                )));
            }
        }
        say(Say::Info(
            "  Read the command above. If it is what you expect, approve it with:".into(),
        ));
        say(Say::Info(
            "    charter persona sync-agents --approve-mcp".into(),
        ));
    }
    for n in &written {
        say(Say::Info(format!(
            "  invoke '{n}' via the Agent/Task tool (subagent_type: {n})"
        )));
    }
    if !written.is_empty() {
        say(Say::Info(
            "New/changed agents load on the next Claude Code session (restart to use now).".into(),
        ));
    }
    0
}

/// `_approve_mcp`: ask about, and record, each credentialed server whose consent line the
/// operator has READ. `--yes` approves without asking and is required off a terminal;
/// `--dry-run` shows the lines and records nothing.
#[allow(clippy::too_many_arguments)]
fn approve_mcp(
    plane: &Path,
    root: &Path,
    state: &Path,
    names: &[String],
    yes: bool,
    dry_run: bool,
    mut ask: Option<Ask>,
    say: Sink,
) -> u8 {
    if !(yes || dry_run || ask.is_some()) {
        say(Say::Fail(
            "--approve-mcp hands a persona's vault value to a command a COMMITTED file names, \
             so it asks before recording — and there is no terminal to ask on."
                .into(),
        ));
        say(Say::Info(
            "  Re-run in a terminal, or add --dry-run to see what it would ask about without \
             recording anything."
                .into(),
        ));
        return 1;
    }
    for n in names {
        let declared = mcp::credentialed(root, n);
        if declared.is_empty() {
            continue;
        }
        let mut keep: Vec<String> = Vec::new();
        for c in declared {
            let label = mcp::label(&[n, &c.server]);
            let Some(fp) = c.fingerprint else {
                say(Say::Warn(format!(
                    "  cannot approve {label} — {}",
                    mcp::UNRENDERABLE
                )));
                continue;
            };
            say(Say::Info(format!("  {label} → {}", c.line)));
            if dry_run {
                continue;
            }
            if !yes {
                let answer = match ask.as_mut() {
                    Some(ask) => ask(&format!("    approve {label}? [y/N] ")),
                    None => Some(false),
                };
                match answer {
                    None => {
                        say(Say::Fail(format!(
                            "interrupted — nothing recorded for {}",
                            mcp::label(&[n])
                        )));
                        return 130;
                    }
                    Some(false) => {
                        say(Say::Info(format!(
                            "    skipped {label} — the vault stays withheld"
                        )));
                        continue;
                    }
                    Some(true) => {}
                }
            }
            keep.push(fp);
        }
        if !dry_run {
            mcp::approve(plane, state, n, &keep);
        }
    }
    if dry_run {
        say(Say::Info(
            "  --dry-run: nothing approved. Re-run without it to be asked.".into(),
        ));
    }
    0
}

/// `_confirm`, for a caller on a terminal: the question on stderr, one line read from stdin,
/// and only an explicit `y`/`yes` is a yes. EOF is a no, and printed as the newline Python
/// prints for it.
pub fn confirm_on_terminal() -> Option<Confirm> {
    if !std::io::stdin().is_terminal() {
        return None;
    }
    Some(Box::new(|prompt: &str| {
        eprint!("{prompt}");
        let mut line = String::new();
        match std::io::stdin().lock().read_line(&mut line) {
            Ok(0) | Err(_) => {
                eprintln!();
                Some(false)
            }
            Ok(_) => {
                let answer = crate::memstore::py_strip(&line).to_lowercase();
                Some(answer == "y" || answer == "yes")
            }
        }
    }))
}
