// Every command the window can invoke, in ONE list (ADR 0052, charter-app#276).
//
// This file is read twice. `lib.rs` hands the list to `tauri-specta`, which registers each
// command in the invoke handler and writes it into the TypeScript the UI imports. `build.rs`
// `include!`s the same file and hands the same names to Tauri's app manifest, which makes each
// one an `allow-<command>` permission and folds them into the two permission sets that the
// capabilities in `capabilities/` grant. So a command added here is registered, typed and allowed
// in one edit. A command registered anywhere else cannot be reached from the window at all:
// once an app has a manifest, Tauri refuses every app command that no capability grants.
//
// The two classes are what a review of this list is for:
//
// - `value_free`: nothing it returns is a secret's value. Most of the app.
// - `vault_values`: what puts a secret's value where the window can reach it, which is a vault's
//   reveal and its copy. A capability of their own grants them, to the main window only, so a
//   window added to the default capability later does not inherit them. A new command goes
//   here if it hands the window a value that the vault design (ADR 0047) keeps out of it. The
//   default is the other list, and adding one here means amending ADR 0052.
//
// Plain macros and no items, so the file means the same thing inside a build script as inside
// the crate. Paths are written `module::command`; the IPC knows a command by the last segment.

/// Hands the list, by class, to `$then!`.
macro_rules! app_commands {
    ($then:ident) => {
        $then! {
            value_free: [
                first_frame,
                portal::session_bus,
                portal::restart_on_the_session_bus,
                vaultswaiting::vaults_to_move,
                vaultswaiting::finish_moving_vaults,
                title_bar_room,
                plane_at_launch,
                open_planes,
                close_plane,
                opener::recent_planes,
                opener::pick_project,
                opener::open_plane,
                opener::approve_plane,
                opener::planes_to_restore,
                opener::relaunch_ask,
                opener::relaunch,
                opener::window_holds_planes,
                windows::move_projects,
                windows::projects_handed,
                windows::charter_windows,
                windows::show_window_holding,
                opener::create_project,
                firstrun::first_run_found,
                firstrun::harness_setup_found,
                firstrun::type_installer,
                sandboxing::sandbox_state,
                sandboxing::answer_sandbox_offer,
                sandboxing::acknowledge_project_hosts,
                sandboxing::persona_grants_held,
                sandboxing::allow_persona_grants,
                sandboxing::type_sandbox_install,
                sandboxing::sandbox_block_report,
                sandboxing::file_sandbox_block_report,
                sandboxing::allow_sandbox_block,
                sandboxing::sandbox_grants,
                sandboxing::revoke_sandbox_grant,
                sandboxing::owed_restarts,
                sandboxing::grantable_folders,
                sandboxing::list_grantable_folder,
                sandboxing::unlist_grantable_folder,
                vaultroute::vault_refusals,
                vaultroute::allow_refused_vault,
                vaultroute::keep_vault_blocked,
                dispatchlimits::dispatch_limits,
                dispatchgrants::dispatch_grants_needed,
                dispatchgrants::allow_dispatch,
                dispatchgrants::keep_dispatch_blocked,
                dispatchgrants::never_dispatch,
                dispatchgrants::dispatch_standing,
                dispatchgrants::lift_dispatch_never,
                dispatchgrants::allow_dispatch_to_any,
                dispatchgrants::revoke_dispatch_to_any,
                dispatchgrants::accept_project_dispatch,
                dispatchgrants::decline_project_dispatch,
                dispatchgrants::give_back_dispatch,
                dispatchgrants::remove_dormant_dispatch,
                dispatchgrants::allow_dispatch_anywhere,
                dispatchgrants::set_dispatch_workspace,
                dispatchgrants::accept_project_dispatch_in,
                dispatchgrants::decline_project_dispatch_in,
                dispatchgrants::dispatch_grants,
                dispatchgrants::revoke_dispatch_grant,
                dispatchgrants::dispatch_arrival,
                dispatchgrants::answer_dispatch_arrival,
                dispatchgrants::dispatch_gone_told,
                dispatchaway::dispatch_away,
                dispatchaway::allow_dispatch_away,
                dispatchaway::dismiss_dispatch_away,
                dispatchaway::never_dispatch_away,
                firstrun::open_repo,
                firstrun::template_that_fits,
                firstrun::open_local_project,
                firstrun::repo_instructions,
                firstrun::import_instructions,
                firsttask::first_task_run,
                open_session,
                open_shell_in_branch,
                close_session,
                ignore_needs_you,
                asking::pending_asks,
                asking::answer_ask,
                send_input,
                send_input_bytes,
                resize_session,
                watch_session,
                unwatch_session,
                running_sessions,
                chat_states,
                opened_chats,
                chats_that_would_not_start,
                retry_chat_that_did_not_start,
                forget_chat_that_did_not_start,
                start_chat_fresh,
                ask_chat_restart,
                restart_chat,
                chats_on_older_sandbox,
                restart_chat_without_sandbox,
                handoff::ask_persona_offer,
                handoff::ask_persona_chat,
                handoff::persona_chats_of,
                handoff::close_chat_stopping,
                chats_plane_updated,
                chat_in_front,
                plane_pins,
                pin_project,
                pin_workspace,
                arrange_workspace_pins,
                thismachine::this_machine,
                thismachine::forget_project,
                thismachine::locate_project,
                thismachine::revoke_approval,
                thismachine::pin_on_this_machine,
                pin_chat,
                open_chat_tab,
                tab_shows,
                chat_order,
                rename_chat,
                ask_to_quit,
                quit,
                quit_cancelled,
                killswitch::agents_stopped,
                killswitch::stop_every_agent,
                killswitch::rearm_agents,
                hide_window,
                window_showing,
                plane_sidebar,
                workspace_panels,
                plane_root_panels,
                session_record,
                dispatches::dispatches,
                dispatches::dispatch_worktree_loss,
                dispatches::dispatch_worktree_discard,
                finished::finished_tasks,
                finished::clear_finished_tasks,
                reopen_finished_task,
                resume_session,
                autosave::plane_fetch,
                saving::plane_saving,
                saving::choose_plane_mode,
                saving::save_plane,
                saving::workspace_saving,
                saving::save_repo,
                workspaces::workspace_create,
                live::workspace_live_preview,
                live::workspace_live,
                workspaces::workspace_at_risk,
                workspaces::workspace_remove,
                workspaces::workspace_rename,
                workspaces::workspace_starts_fresh,
                workspaces::workspace_focused,
                workspaces::reachable_repos,
                workspaces::take_repos,
                workspaces::clone_repo,
                workspaces::drop_repo,
                workspaces::drop_repo_membership,
                workspace_repos,
                alerts_everywhere,
                start_options,
                approve_profile,
                start_chat,
                worktrees::worktree_of_chat,
                worktrees::worktree_list,
                worktrees::worktree_add,
                worktrees::worktree_remove,
                worktrees::worktree_merge,
                worktrees::worktree_done,
                piecefiles::piece_file,
                piecefiles::open_in_your_editor,
                piecefiles::open_their_agents_md,
                piecefiles::move_their_agents_md_aside,
                piecefiles::copy_branch_path,
                piecefiles::reveal_branch_path,
                piecefiles::branch_tree,
                piecefiles::branch_status,
                piecefiles::branch_ahead_behind,
                piecefiles::what_changed,
                filewatch::files_watch,
                findfiles::find_files,
                findfiles::find_files_end,
                branchwatch::branch_watch,
                searchfiles::search_files,
                searchfiles::search_files_more,
                searchfiles::search_files_end,
                updates::update_channel,
                updates::set_update_channel,
                updates::check_for_update,
                updates::install_update,
                updates::restart_to_update,
                extensions::installed_extensions,
                extensions::pick_extension,
                extensions::install_extension,
                extensions::approve_extension,
                extensions::forget_extension,
                extensions::set_extension_on,
                extensions::extension_themes,
                extensions::extension_icon_themes,
                extensions::extension_panels,
                vaults::vault_list,
                vaults::vault_open,
                vaults::vault_refresh,
                vaults::vault_create,
                vaults::vault_remove,
                vaults::vault_secret_add,
                vaults::vault_secret_set,
                vaults::vault_secret_rename,
                vaults::vault_secret_delete,
                vaults::vault_identity_move,
                vaults::vault_identity_put,
                personas::persona_create,
                personas::persona_remove,
                personas::persona_edit,
                personas::persona_marks,
                personas::persona_mark_set,
                personas::persona_profile,
                personas::persona_set_profile,
                todos::todo_add,
                todos::todo_done,
                todos::todo_forget,
                todos::todo_read,
                worklinks::chat_work_link,
                worklinks::chat_work_unlink,
                worklinks::chat_work_item,
                memories::memory_read,
                memories::memory_edit,
                memories::memory_archive,
                memories::memory_unarchive,
                memories::memory_archived,
                memories::memory_create,
                memories::memory_move,
                memories::memory_scopes,
                curation::curation_offers,
                curation::curate,
                references::reference_into_chat,
                references::start_chat_here,
                smartclose::smart_close_offer,
                smartclose::smart_close,
                smartclose::cancel_smart_close,
                smartclose::smart_closing,
                stopping::stop_chat,
                stopping::stopping_chats,
                extensions::project_extensions,
                extensions::extensions_on,
                extensions::extension_facts,
                harness_plugins::project_harness_plugins,
                extensions::project_theme,
                extensions::project_theme_drawn,
                extensions::project_icons_drawn,
                views::extension_views,
                views::extension_programs_run,
                views::open_view,
                views::run_action,
                views::extension_commands,
                views::reopened_views,
                views::window_views,
                views::window_focus,
                views::reopened_focus,
                changes::change_push_question,
                changes::change_push,
                changes::change_land_question,
                changes::change_land,
                doctor::plane_doctor,
                doctor::plane_doctor_fix,
                doctor::plane_doctor_fix_identity,
                doctor::plane_doctor_identity,
                settings::project_settings,
                settings::save_project_settings,
                settings::mark_profile_asks,
                settings::move_project_settings,
                settings::add_project_forge,
                settings::remove_project_forge,
                settings::add_project_profile,
                settings::remove_project_profile,
                settings::rename_project_profile,
                settings::add_sandbox_host,
                settings::remove_sandbox_host,
                settings::confirm_sandbox_host,
                settings::project_saving_in_force,
                settings::workspace_settings,
                settings::save_workspace_settings,
                usage::chat_usage,
                pin::plane_pin,
                about::about_charter,
                clipath::install_cli_on_path,
                windowprefs::write_layout,
                windowprefs::adopt_layout,
                windowprefs::set_dismissed,
                windowprefs::use_built_in_theme,
            ],
            vault_values: [
                vaults::vault_secret_reveal,
                vaults::vault_secret_copy,
            ],
        }
    };
}

/// The name the IPC knows a command by: the last segment of its path.
#[allow(
    unused_macros,
    reason = "used by build.rs and by the crate's tests, not by the app"
)]
macro_rules! command_name {
    ($only:ident) => {
        stringify!($only)
    };
    ($first:ident :: $($rest:ident)::+) => {
        command_name!($($rest)::+)
    };
}

/// The list's names, as `(value_free, vault_values)`: `app_commands!(command_names)`.
#[allow(
    unused_macros,
    reason = "used by build.rs and by the crate's tests, not by the app"
)]
macro_rules! command_names {
    (
        value_free: [$($($free:ident)::+),* $(,)?],
        vault_values: [$($($value:ident)::+),* $(,)?] $(,)?
    ) => {
        (
            &[$(command_name!($($free)::+)),*] as &'static [&'static str],
            &[$(command_name!($($value)::+)),*] as &'static [&'static str],
        )
    };
}
