// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  The plane the app was started in, or why there is none. */
	planeRoot: () => typedError<string, string>(__TAURI_INVOKE("plane_root")),
	/**  Starts a session. No program is the operator's shell. */
	openSession: (program: string | null, args: string[], cwd: string | null, columns: number, rows: number) => typedError<number, string>(__TAURI_INVOKE("open_session", { program, args, cwd, columns, rows })),
	/**  Ends a session and everything it started. */
	closeSession: (session: number) => typedError<null, string>(__TAURI_INVOKE("close_session", { session })),
	/**  Sends what a pane typed to the session's program. */
	sendInput: (session: number, text: string) => typedError<null, string>(__TAURI_INVOKE("send_input", { session, text })),
	/**  Tells a session how big the pane showing it now is. */
	resizeSession: (session: number, columns: number, rows: number) => typedError<null, string>(__TAURI_INVOKE("resize_session", { session, columns, rows })),
	/**
	 *  Opens a view of a session for a pane that is now on screen: the channel is sent the screen
	 *  as it already is, and then the session's output. Answers with the id that closes the view.
	 */
	watchSession: (session: number, output: Channel<string>) => typedError<Watching, string>(__TAURI_INVOKE("watch_session", { session, output })),
	/**  Closes a view, for a pane that has gone off screen. The session keeps running. */
	unwatchSession: (session: number, view: number) => typedError<null, string>(__TAURI_INVOKE("unwatch_session", { session, view })),
	/**  The sessions that are running, in the order they were opened. */
	runningSessions: () => __TAURI_INVOKE<number[]>("running_sessions"),
};

/* Types */
/**
 *  A view a pane has open, and the size the screen it opened on was drawn for. The pane sets
 *  its terminal to that size before it draws the screen, so what was wrapped stays wrapped.
 */
export type Watching = {
	view: number,
	columns: number,
	rows: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

