// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  The window says its first frame is on screen, which is where cold start ends.
	 * 
	 *  It answers with the one line to put on screen when that took longer than the limit, and
	 *  with nothing when it did not. An operator who launched charter from an icon has no
	 *  standard error to read, and a start that took half a minute with no window has to say why
	 *  somewhere they can see it (charter-app#24). Only the first call is answered: a webview
	 *  that reloads has not started the process again.
	 * 
	 *  `CHARTER_BENCH_LOG` — which only `tools/bench.mjs` sets — also prints the number here.
	 */
	firstFrame: () => __TAURI_INVOKE<string | null>("first_frame"),
	/**
	 *  Where charter's title bar may start.
	 * 
	 *  **Asked of the binary and never sniffed from a user agent.** The one fact that decides this
	 *  is whether `titleBarStyle: "Overlay"` in `tauri.conf.json` was honoured, and that is a
	 *  property of the target this binary was built for — which `cfg!` knows exactly and a
	 *  `navigator.userAgent` string only guesses at. It is also why this is a command rather than
	 *  a stylesheet constant: one frontend bundle is built per target by the same CI job that
	 *  builds the binary, but nothing in the bundle is told which target it landed in.
	 * 
	 *  The window asks once, after the first frame, and the bar shifts right by
	 *  [`MACOS_WINDOW_CONTROLS`] when the answer lands. That settle is deliberate: the alternative
	 *  is awaiting an IPC round trip before `createRoot().render()`, which puts a command between
	 *  the process starting and the first frame — the one thing `main.tsx` is written to avoid
	 *  (ADR 0026's 2 s cold start). A title bar that finishes placing itself a millisecond after
	 *  it is drawn is the same settle the project strip, the workspace strip and the status line
	 *  all already have.
	 */
	titleBarRoom: () => __TAURI_INVOKE<TitleBarRoom>("title_bar_room"),
	/**
	 *  What this launch had to go on, and the plane it opened — or the fact that it opened none.
	 * 
	 *  **Never an error.** The working directory is a HINT: it is resolved once, at startup, to
	 *  decide which plane the first window opens, and after that a window's plane is explicit and
	 *  the working directory is never consulted again. A launch that resolved no plane leaves the
	 *  app running and holding nothing, which is a state the window draws rather than a failure
	 *  it reports.
	 */
	planeAtLaunch: () => __TAURI_INVOKE<Launch>("plane_at_launch"),
	/**
	 *  Every plane this process is holding, by id.
	 * 
	 *  There can be none, and none is an ordinary state: it is what an app launched outside any
	 *  plane comes up in, and what it returns to when the last project is closed.
	 */
	openPlanes: () => __TAURI_INVOKE<PlaneId[]>("open_planes"),
	/**
	 *  Lets go of a plane: its record is written, its sessions are ended, and its hook socket is
	 *  released.
	 * 
	 *  **Nothing of the plane on disk goes.** Closing a project is the app letting go of it, and
	 *  a plane closed here can be opened again — by this process or another — with everything
	 *  still in it.
	 * 
	 *  Its opposite is `opener::open_plane`, which is gated: opening a plane runs what its record
	 *  names, so it happens behind the operator's yes (ADR 0035). Closing one needs no gate — it
	 *  only ever does less.
	 */
	closePlane: (plane: PlaneId) => typedError<null, string>(__TAURI_INVOKE("close_plane", { plane })),
	/**
	 *  The planes this machine remembers, each checked against the disk, with what was dropped.
	 * 
	 *  **On a blocking thread, and this is not a micro-optimisation.** Every row costs a
	 *  `symlink_metadata` and a second `stat` for the manifest, and a remembered plane can be on a
	 *  network mount, an unplugged external disk or an automounted share. `machine::read` is
	 *  deliberately lexical for exactly this reason, and the disk question it leaves out is asked
	 *  here — off the thread that draws, so an opener waiting on a share that is not coming back
	 *  is an opener that is still on screen.
	 */
	recentPlanes: () => typedError<Recents, string>(__TAURI_INVOKE("recent_planes")),
	/**
	 *  Asks the operating system for a folder, and answers with the one the operator chose.
	 * 
	 *  Null is a cancelled dialog, which is not a failure and says nothing. The path is not
	 *  resolved here and not checked here: [`open_plane`] does both, because it is also what a
	 *  recents row and a second launch go through, and three callers resolving a path three times
	 *  is three answers to one question — the defect `plane.rs` records twice in its own
	 *  docstrings.
	 */
	pickProject: () => typedError<string | null, string>(__TAURI_INVOKE("pick_project")),
	/**
	 *  Opens a plane, **or answers with the question that has to be asked first**.
	 * 
	 *  The one way in for every caller that is not the launch: a recents row, a picked folder, a
	 *  typed path, and a second launch handing its directory to this process. All four go through
	 *  the same resolution and the same consent read, in `Planes::open_if_approved`.
	 * 
	 *  A plane that is already open is answered with the id it already has, and nothing is bound
	 *  or started a second time — which is `Planes::open`'s rule and the reason it exists.
	 */
	openPlane: (path: string) => typedError<Opened, string>(__TAURI_INVOKE("open_plane", { path })),
	/**
	 *  The operator's answer to [`Ask`]: yes, open it.
	 * 
	 *  `contributes` is the value the dialog drew, handed straight back. It is checked against the
	 *  plane again before anything is approved or opened — see `Planes::approve_and_open`, where
	 *  the check and the reason for it live.
	 * 
	 *  **This is a separate click from the one that opened the dialog, and it has to be.** A
	 *  command that both asked and opened would be asking nothing.
	 */
	approvePlane: (path: string, contributes: PlaneContribution) => typedError<PlaneId, string>(__TAURI_INVOKE("approve_plane", { path, contributes })),
	/**
	 *  The projects a cold launch has to put back, and every one it would not take back.
	 * 
	 *  **Answered to the window rather than acted on here, and that is the whole shape of it.**
	 *  Opening a project starts the programs its reopen record names, so every open goes through
	 *  the trust gate — and the gate ends in a dialog, which only something with a window can
	 *  carry through. A restore that opened these itself would be a third mint of `Approved`
	 *  covering every project the operator had ever had open at once. So this says *which*, the
	 *  window opens each one through `open_plane` like a recents row, and a project that has
	 *  started doing more than what was approved is asked about exactly as it would have been.
	 * 
	 *  **On a blocking thread**, for `recent_planes`' reason: every row costs a
	 *  `symlink_metadata` and a `stat`, and a remembered project can be on a share that is not
	 *  coming back.
	 */
	planesToRestore: () => typedError<Restore, string>(__TAURI_INVOKE("planes_to_restore")),
	/**
	 *  A window says what it is holding: its projects as tabs, and which one is in front.
	 * 
	 *  Two things, in one call, because they are one fact. A notification about a chat in a
	 *  project the operator is NOT looking at is sent rather than suppressed — see [`Showing`],
	 *  where the gap this closes is written down — and the tab strip is written into this
	 *  machine's store so the next cold launch puts it back (ADR 0033).
	 * 
	 *  **The window says; nothing asks it.** The window is the only thing that knows what it
	 *  draws, and a core that inferred the arrangement from its own registry would be answering
	 *  "what is open in this process", which is a different question the moment a project is held
	 *  but not on screen.
	 */
	windowHoldsPlanes: (held: WindowTabs) => __TAURI_INVOKE<void>("window_holds_planes", { held }),
	/**
	 *  Makes a NEW project — scaffolds a plane in a directory — **and opens it through the gate**.
	 * 
	 *  Two halves, in this order and never the other way round. What is written is
	 *  `scaffold::init`'s, which is `charter init`; what happens next is [`open_plane`]'s gate,
	 *  because a plane charter has just created is still a plane this machine has approved
	 *  nothing about (ADR 0035). So the ordinary answer to this command is an [`Ask`], and the
	 *  operator reads what their new project contributes before it is opened — the same dialog, on
	 *  the same path, as a project that came from a recents row.
	 * 
	 *  **It never writes a plane into a repository the operator pointed at.** That is `init`'s own
	 *  refusal (`scaffold::repo_is_not_a_plane_yet`) and ADR 0035's decision, and it is reached
	 *  here rather than reimplemented: a directory picked in a dialog has nobody standing in it,
	 *  so the scaffolding — including an edit to a tracked `.gitignore` — is a write nobody typed.
	 *  `plane_is_this_repo` is the operator asking for the old shape **by name**, which is how
	 *  charter's own plane exists, and it comes from a box they ticked.
	 * 
	 *  **The directory is the directory, and no walk decides otherwise.** `plane::place` — what
	 *  the CLI's `init` uses — reads `$CHARTER_ROOT` and walks up to an enclosing plane, which is
	 *  right for a command run where somebody is standing and wrong for one handed a path: a new
	 *  project inside `~/code` would otherwise be scaffolded into whatever plane happens to be
	 *  above it. The walk is still asked, through `plane::find_root`, but only to REFUSE: a
	 *  directory inside a plane is a place for a workspace's clone, not for a second plane.
	 * 
	 *  **And that is not a second walk** (charter-app#178). The operator's ruling was worded as
	 *  *walk as the CLI does, and refuse rather than write when the walk lands somewhere other
	 *  than the directory picked*, and a reviewer asked the fair question about the paragraph
	 *  above: if this asks `find_root` where the CLI asks `place`, the two can drift, and the day
	 *  they do, the refusal starts naming a plane `charter init` would not have chosen. They
	 *  cannot. `find_root` and `place` are **one** walk in this core — `plane::walk`, which is a
	 *  single function on purpose and says so at length, because two copies of it are two answers
	 *  about one directory (M2.9, then M2.16). The two differ in what they do with a `None` and
	 *  in reading `$CHARTER_ROOT`, and neither difference can reach the `Some` this refusal is
	 *  made of. `$CHARTER_ROOT` is the one thing deliberately not honoured here, and that is the
	 *  difference this command wants: a variable inherited from whatever shell opened the app is
	 *  not an answer about a folder somebody just pointed at.
	 *  `the_refusal_names_the_plane_the_cli_would_have_scaffolded_into` holds the identity, so a
	 *  change that made the two walks disagree lands in this file.
	 * 
	 *  **`adopt` is the third answer, and ADR 0035's default** (charter-app#175). Beside "refuse"
	 *  and "scaffold the old shape" there is now "make the plane here and take that repository as
	 *  its first clone", which is what the record actually decided — *"`charter init` on an
	 *  existing repo adopts that repo as the plane's first clone and makes the plane beside it"*.
	 *  It is two directories because it is two answers: the dialog asks for both, and neither is
	 *  guessed from the other.
	 */
	createProject: (path: string, planeIsThisRepo: boolean, adopt: string | null) => typedError<Opened, string>(__TAURI_INVOKE("create_project", { path, planeIsThisRepo, adopt })),
	/**
	 *  Starts a session, and remembers it as a chat so a quit can write it down. No program is
	 *  the operator's shell.
	 */
	openSession: (plane: PlaneId, program: string | null, args: string[], cwd: string | null, name: string, columns: number, rows: number) => typedError<number, string>(__TAURI_INVOKE("open_session", { plane, program, args, cwd, name, columns, rows })),
	/**  Ends a session and everything it started. It is no longer a chat a quit would record. */
	closeSession: (plane: PlaneId, session: number) => typedError<null, string>(__TAURI_INVOKE("close_session", { plane, session })),
	/**  Sends what a pane typed to the session's program. */
	sendInput: (plane: PlaneId, session: number, text: string) => typedError<null, string>(__TAURI_INVOKE("send_input", { plane, session, text })),
	/**  Tells a session how big the pane showing it now is. */
	resizeSession: (plane: PlaneId, session: number, columns: number, rows: number) => typedError<null, string>(__TAURI_INVOKE("resize_session", { plane, session, columns, rows })),
	/**
	 *  Opens a view of a session for a pane that is now on screen: the channel is sent the screen
	 *  as it already is, and then the session's output. Answers with the id that closes the view.
	 */
	watchSession: (plane: PlaneId, session: number, output: Channel<string>) => typedError<Watching, string>(__TAURI_INVOKE("watch_session", { plane, session, output })),
	/**  Closes a view, for a pane that has gone off screen. The session keeps running. */
	unwatchSession: (plane: PlaneId, session: number, view: number) => typedError<null, string>(__TAURI_INVOKE("unwatch_session", { plane, session, view })),
	/**  The sessions that are running, in the order they were opened. */
	runningSessions: (plane: PlaneId) => typedError<number[], string>(__TAURI_INVOKE("running_sessions", { plane })),
	/**
	 *  What every chat is doing, and which of them are asking for you.
	 * 
	 *  The window asks once, when it opens; after that it is told (`chat-moved`). A chat the app
	 *  has never heard from is `unknown`, which is what the spec says a harness with no state
	 *  hook shows.
	 */
	chatStates: (plane: PlaneId) => typedError<Moved[], string>(__TAURI_INVOKE("chat_states", { plane })),
	/**
	 *  The chats the app already has open — at a launch, the ones put back from the record.
	 * 
	 *  The window asks this instead of opening its own: putting the record back happens before
	 *  there is a window, so that a relaunch does not depend on a webview having run.
	 */
	openedChats: (plane: PlaneId) => typedError<OpenChat[], string>(__TAURI_INVOKE("opened_chats", { plane })),
	/**
	 *  The chats this launch could not start, by name and reason. They are still recorded, and
	 *  will be tried again at the next launch.
	 */
	chatsThatWouldNotStart: (plane: PlaneId) => typedError<([string, string])[], string>(__TAURI_INVOKE("chats_that_would_not_start", { plane })),
	/**  Says which chat is in front, so the record brings that one back in front. */
	chatInFront: (plane: PlaneId, session: number | null) => typedError<null, string>(__TAURI_INVOKE("chat_in_front", { plane, session })),
	/**  What this operator has pinned in this project. */
	planePins: (plane: PlaneId) => typedError<Pins, string>(__TAURI_INVOKE("plane_pins", { plane })),
	/**  Pins or unpins the project itself. */
	pinProject: (plane: PlaneId, pinned: boolean) => typedError<null, string>(__TAURI_INVOKE("pin_project", { plane, pinned })),
	/**  Pins or unpins one workspace inside a project. */
	pinWorkspace: (plane: PlaneId, workspace: string, pinned: boolean) => typedError<null, string>(__TAURI_INVOKE("pin_workspace", { plane, workspace, pinned })),
	/**
	 *  Pins or unpins one chat.
	 * 
	 *  Its own command rather than a third case of the two above, because it is written
	 *  somewhere else entirely: a chat pin goes in the plane's own `.charter/app/reopen.json`
	 *  and never in the machine store, which ADR 0034 forbids holding a chat's name.
	 */
	pinChat: (plane: PlaneId, session: number, pinned: boolean) => typedError<null, string>(__TAURI_INVOKE("pin_chat", { plane, session, pinned })),
	/**
	 *  Asks the app to quit, the way the menu's Quit and the tray's do.
	 * 
	 *  It is the same function they call, so what this goes through is the real path: the ask
	 *  is counted, the window is shown, and the window is sent `quit-asked`. The command
	 *  palette's own quit action is this too.
	 */
	askToQuit: () => __TAURI_INVOKE<void>("ask_to_quit"),
	/**  The window's answer to being asked to quit: go. */
	quit: () => __TAURI_INVOKE<void>("quit"),
	/**  The window's answer to being asked to quit: not now. The next ask warns again. */
	quitCancelled: () => __TAURI_INVOKE<void>("quit_cancelled"),
	/**  Hides the window, which is what its close button does. Every session keeps running. */
	hideWindow: () => __TAURI_INVOKE<void>("hide_window"),
	/**  Whether the window is on screen. The scenario tests ask; nothing in the UI does. */
	windowShowing: () => __TAURI_INVOKE<boolean>("window_showing"),
	/**
	 *  The sidebar, read from the plane on disk every time it is asked for.
	 * 
	 *  Read fresh rather than cached: the plane is a directory the operator also edits by hand
	 *  and another charter process writes, so a cache here would be a second answer to "what is
	 *  on disk" that nothing invalidates.
	 * 
	 *  The chats are the ones `Chats` already holds — one model of a chat, not a second derived
	 *  from the sessions. What files one under a workspace is the directory it works in, because
	 *  nothing on the plane records a chat: `.charter/frame/` belongs to the tmux frame and the
	 *  app stays out of it.
	 */
	planeSidebar: (plane: PlaneId) => typedError<Sidebar, string>(__TAURI_INVOKE("plane_sidebar", { plane })),
	/**
	 *  The focused workspace's panels: its repos, its todos and the plane's personas.
	 * 
	 *  Its own command, separate from the repos below, because everything here is a directory
	 *  listing and a few small files. The panels paint the moment a workspace is focused, and
	 *  the part that has to run git arrives after — one command would make the todo list wait
	 *  for a status read on every clone.
	 * 
	 *  **It names its plane**, like every other command here. It used to resolve one out of the
	 *  process's working directory — `plane::resolve`, the singleton ADR 0034 removed — so a
	 *  window showing a project the launch had not opened drew the workspaces of the one it had.
	 *  A workspace name means nothing without its project; two projects can both have an `alpha`.
	 */
	workspacePanels: (plane: PlaneId, workspace: string) => typedError<Panels, string>(__TAURI_INVOKE("workspace_panels", { plane, workspace })),
	/**
	 *  One persona's memories, as rows of the same vocabulary a panel is drawn from.
	 * 
	 *  **It answers in `PanelRow`s, and that is the point rather than a convenience.** The window's
	 *  list primitive shortens a row, opens its card, bounds the count, offers more and grows a
	 *  search once there is more than a page of them — and it does all of that for these without
	 *  knowing what a memory is, because they arrive as rows. A panel body and a row's detail
	 *  surface are the same vocabulary drawn by the same code, which is the test of whether the
	 *  contract was worth defining.
	 * 
	 *  **Its own command, asked when a persona's card is opened.** `workspace_panels` carries the
	 *  *count*, which is a `read_dir`; this reads every memory file, and folding it in would read
	 *  every persona's whole store on every workspace focus for something nobody has asked to see —
	 *  `persona_details`' reason, at a larger size.
	 */
	personaMemories: (plane: PlaneId, persona: string) => typedError<PanelRow[], string>(__TAURI_INVOKE("persona_memories", { plane, persona })),
	/**
	 *  Make a workspace: `charter workspace create <name>`, with the vision when one was typed.
	 * 
	 *  **The name is checked by the core and by nothing in the window.** `wscmd::create` runs
	 *  `wscmd::ensure`, which is where `contain::workspace_name_ok` is, so the app refuses exactly
	 *  the names a terminal refuses and says the same sentence about them. A second alphabet in
	 *  the dialog would be a second answer to what a workspace may be called, and the two would
	 *  drift the first time either moved.
	 * 
	 *  LOCAL, never LIVE, and it selects nothing: `--live` commits a workspace's manifest and
	 *  memory into the plane's own git, and `--use` writes a session lock that belongs to a
	 *  terminal. Neither is a default the window may take on the operator's behalf; both are
	 *  `charter workspace live` and `charter workspace use`, which still exist.
	 */
	workspaceCreate: (plane: PlaneId, name: string, vision: string | null) => typedError<string[], string>(__TAURI_INVOKE("workspace_create", { plane, name, vision })),
	/**
	 *  What deleting this workspace would discard, for the dialog to show **before** anything is
	 *  pressed.
	 * 
	 *  The core's own guard, read for drawing. It decides nothing: [`workspace_remove`] asks again,
	 *  inside `wscmd::remove`, against the disk as it is at the moment of the delete. A window that
	 *  treated this answer as the decision would be deciding on a reading that is already old — and
	 *  worse, one taken while the operator read a dialog.
	 */
	workspaceAtRisk: (plane: PlaneId, workspace: string) => typedError<AtRisk[], string>(__TAURI_INVOKE("workspace_at_risk", { plane, workspace })),
	/**
	 *  Delete a workspace and its clones: `charter workspace remove <name> [--force]`.
	 * 
	 *  **This is the one delete, and the guard is inside it.** See this module's header. `force` is
	 *  the operator saying to discard work the core found — it is never passed on their behalf, and
	 *  the window asks for it only after showing them the refusal the core gave.
	 */
	workspaceRemove: (plane: PlaneId, workspace: string, force: boolean) => typedError<string[], Refused>(__TAURI_INVOKE("workspace_remove", { plane, workspace, force })),
	/**
	 *  What one persona's definition says about it: its role, when to delegate to it, its tools,
	 *  the vault it names and what it extends.
	 * 
	 *  **Its own command, asked when a row is clicked, and not part of `workspace_panels`.** The
	 *  panels are the hot path of focusing a workspace — the spec gives that 100 ms — and folding
	 *  this in would read every persona's definition, and every definition up every `extends:`
	 *  chain, on every focus, for something nobody has asked to see. A plane with twenty personas
	 *  would pay for twenty file reads per click on the workspace strip.
	 * 
	 *  **It names its plane**, like every other command here: a persona belongs to a plane, and a
	 *  window holds several.
	 * 
	 *  It answers with `charter_core::personas::name_refusal`'s own sentence where it will not
	 *  answer — the same words the CLI gives for the same name.
	 */
	personaDetails: (plane: PlaneId, persona: string) => typedError<PersonaDetails, string>(__TAURI_INVOKE("persona_details", { plane, persona })),
	/**
	 *  What git says about each of the focused workspace's clones, and what the forge cache
	 *  last recorded for the branch each is on.
	 * 
	 *  On a blocking thread and never the one that draws: a status read is bounded at five
	 *  seconds per clone, and a window that waited on it would miss the 100 ms a workspace
	 *  switch is allowed. **Nothing here crosses a network** — the forge state comes out of
	 *  `.charter/cache/glstate.json`, which charter-app reads and never writes.
	 */
	workspaceRepos: (plane: PlaneId, workspace: string) => typedError<RepoStates, string>(__TAURI_INVOKE("workspace_repos", { plane, workspace })),
	/**
	 *  What is wrong in every project this process holds, project by project, for the alerts
	 *  drawer.
	 * 
	 *  **Every project, never one**: an alert is about a plane rather than the workspace on
	 *  screen, and the drawer exists because alerts cross projects — so the command takes no plane,
	 *  and cannot be wired to the one in front by mistake.
	 * 
	 *  On a blocking thread, because the plane-root alert asks git for a status per project and a
	 *  window that waited on eight of them would miss its frame.
	 */
	alertsEverywhere: () => typedError<PlaneAlerts[], string>(__TAURI_INVOKE("alerts_everywhere")),
	/**
	 *  What the picker draws: every profile this machine has, every one charter will not use,
	 *  and the plane's personas.
	 * 
	 *  Read fresh every time it is opened, like the sidebar: `charter.local.toml` is a file the
	 *  operator edits by hand and a chat can write, so a cache here would be a second answer to
	 *  "what is on disk" that nothing invalidates.
	 */
	startOptions: (plane: PlaneId) => typedError<StartOptions, string>(__TAURI_INVOKE("start_options", { plane })),
	/**
	 *  Records that the operator approved running this profile's command — **the one they were
	 *  shown**.
	 * 
	 *  `shown` is the exact line the dialog drew. It is checked against the file again here,
	 *  and a mismatch refuses: between the picker reading the profile and the operator pressing
	 *  the button, `charter.local.toml` can change — it is gitignored, so an edit to it leaves
	 *  no diff for a reviewer to catch, and nothing stops a chat writing plane config. Without
	 *  this check the approval recorded whatever was on disk at CLICK time, so the operator
	 *  could approve, and charter could run, a command they never read. A review probe found
	 *  it, and it defeats the one prompt ADR 0022 exists to put in front of a launch.
	 * 
	 *  Its own command, and a separate click from the one that starts the chat: this IS the
	 *  approval, and a command that both asked and ran would be asking nothing.
	 */
	approveProfile: (plane: PlaneId, name: string, shown: string) => typedError<null, string>(__TAURI_INVOKE("approve_profile", { plane, name, shown })),
	/**
	 *  Starts a chat on a harness profile, with a persona.
	 * 
	 *  A command of its own rather than a flag on `open_session`, so neither can be mistaken
	 *  for the other by a caller passing null: this one goes through every gate a launch has,
	 *  and that one opens the operator's shell.
	 * 
	 *  `show_footer` is the picker's footer checkbox, and it is a property of THIS chat
	 *  (charter ADR 0029). It reaches the harness as an environment variable set at the exec, so
	 *  it is decided here and nowhere later: Claude Code's footer command inherits the
	 *  environment its harness was started with, and no later click can change it.
	 */
	startChat: (plane: PlaneId, profile: string, persona: string | null, cwd: string | null, name: string, showFooter: boolean, columns: number, rows: number) => typedError<Started, string>(__TAURI_INVOKE("start_chat", { plane, profile, persona, cwd, name, showFooter, columns, rows })),
	/**
	 *  The piece a chat's working directory sits in, or `None`.
	 * 
	 *  Called for every chat the sidebar draws. `worktree::locate` is path arithmetic and spawns
	 *  nothing; the one git call is the listing, made once per repo and only for chats that are
	 *  in a piece at all.
	 */
	worktreeOfChat: (plane: PlaneId, cwd: string) => typedError<{
	workspace: string,
	repo: string,
	piece: string,
	branch: string | null,
	wired: boolean,
	stale: boolean,
} | null, string>(__TAURI_INVOKE("worktree_of_chat", { plane, cwd })),
	/**  This workspace's pieces for one repo. */
	worktreeList: (plane: PlaneId, workspace: string, repo: string) => typedError<Piece[], string>(__TAURI_INVOKE("worktree_list", { plane, workspace, repo })),
	/**
	 *  Remove a piece. The refusal is the core's sentence, unchanged.
	 * 
	 *  `force` is the operator saying to discard work the guards found — it is never passed on
	 *  their behalf, and the window asks for it only after showing them what the refusal said.
	 */
	worktreeRemove: (plane: PlaneId, workspace: string, repo: string, piece: string, force: boolean) => typedError<null, string>(__TAURI_INVOKE("worktree_remove", { plane, workspace, repo, piece, force })),
	/**  Land a piece in its clone, fast-forward only. Never pushes. */
	worktreeMerge: (plane: PlaneId, workspace: string, repo: string, piece: string) => typedError<Merged, string>(__TAURI_INVOKE("worktree_merge", { plane, workspace, repo, piece })),
	/**  Which channel this machine takes charter from: `stable` or `dev`. */
	updateChannel: () => __TAURI_INVOKE<string>("update_channel"),
	/**  Put this machine on a channel. A word charter does not know is refused, not guessed at. */
	setUpdateChannel: (channel: string) => typedError<null, string>(__TAURI_INVOKE("set_update_channel", { channel })),
	/**  Look for a newer charter now. The answer arrives as [`CHECKED`] or [`FAILED`]. */
	checkForUpdate: () => __TAURI_INVOKE<void>("check_for_update"),
	/**
	 *  Install the newer charter. The answer arrives as [`INSTALLED`] or [`FAILED`]; charter has
	 *  to be relaunched after it, and says so rather than doing it under the operator's sessions.
	 */
	installUpdate: () => __TAURI_INVOKE<void>("install_update"),
	/**
	 *  What has contributed what to this window.
	 * 
	 *  It reads the disk — every installed extension's whole directory, to re-take the fingerprint
	 *  — because an approval is of bytes and the bytes are what may have changed since. ADR 0041
	 *  names that cost: *the fingerprint is a hash of code, checked at each launch*, and
	 *  charter-app#152 widened it from the declared list to the tree. Off the UI thread for exactly
	 *  that reason, and the cost is measured in #152's PR body rather than left as an estimate.
	 */
	installedExtensions: () => typedError<InstalledExtensions, string>(__TAURI_INVOKE("installed_extensions")),
	/**
	 *  The folder picker, for an extension this machine does not have.
	 * 
	 *  **By path, by the operator, from nowhere.** ADR 0041 rejects a registry and a fetch by name
	 *  — *the moment charter resolves an extension name over the network it owns a supply chain* —
	 *  so this is the only way one arrives, and it is the same picker `pick_project` uses.
	 */
	pickExtension: () => typedError<string | null, string>(__TAURI_INVOKE("pick_extension")),
	/**
	 *  Read the extension at `path`, write it into the record **unapproved**, and hand back the
	 *  question to ask about it.
	 * 
	 *  An extension charter cannot read is an error here rather than a silent nothing: the
	 *  operator pointed at a directory and is owed the reason it is not one.
	 */
	installExtension: (path: string) => typedError<ExtensionAsk, string>(__TAURI_INVOKE("install_extension", { path })),
	/**
	 *  The operator's answer to [`ExtensionAsk`]: yes.
	 * 
	 *  `fingerprint` is the one the dialog drew, handed straight back — charter-app#123's fix
	 *  applied before the defect can be copied. What is recorded is the bytes that were on screen,
	 *  so a write between the drawing and the click is not consented to; it makes the next launch
	 *  ask again, which is the whole of the mechanism.
	 * 
	 *  **This is a separate click from the one that installed it, and it has to be.**
	 */
	approveExtension: (id: string, path: string, fingerprint: string) => typedError<null, string>(__TAURI_INVOKE("approve_extension", { id, path, fingerprint })),
	/**
	 *  Take an extension out of the record.
	 * 
	 *  Its own files are not charter's and are not deleted: ADR 0041's *an extension is
	 *  re-installable by name; its state is its own problem*. What goes is the path and the
	 *  approval, which is exactly what ADR 0034 says deleting this machine's state must cost.
	 */
	forgetExtension: (id: string) => typedError<null, string>(__TAURI_INVOKE("forget_extension", { id })),
	/**
	 *  Every theme in force: the ones approved extensions contribute, and nothing else.
	 * 
	 *  An extension that is new, changed or unreadable contributes nothing here. That is the
	 *  registry doing its one job — [`extension::Surveyed::themes_in_force`] is what answers, and
	 *  this command only shapes it.
	 */
	extensionThemes: () => typedError<ExtensionTheme[], string>(__TAURI_INVOKE("extension_themes")),
	/**
	 *  Every panel an approved extension contributes to this window's side region.
	 * 
	 *  **Its own command, asked once per window and never per workspace focus.** A survey reads
	 *  every installed extension's whole directory to re-take the fingerprint — ADR 0041's named
	 *  cost of fingerprinting code — and folding that into `workspace_panels` would put it on the
	 *  path that has 100 ms to draw, once per click on the workspace strip.
	 * 
	 *  It is the same shape as [`extension_themes`] one row down, and for the same reason: an
	 *  extension that is new, changed or unreadable contributes nothing here. That is the registry
	 *  doing its one job, and a contributed panel rests on it entirely.
	 */
	extensionPanels: () => typedError<PanelView[], string>(__TAURI_INVOKE("extension_panels")),
	/**
	 *  Every row `charter doctor` would print for this plane, run inside the app.
	 * 
	 *  On a blocking thread: every git question a row asks has a five-second deadline
	 *  (`doctor::CHECK_TIMEOUT`), and the full doctor runs a harness per profile. A window that
	 *  waited on that would stop drawing.
	 */
	planeDoctor: (plane: PlaneId, full: boolean) => typedError<DoctorReport, string>(__TAURI_INVOKE("plane_doctor", { plane, full })),
	/**
	 *  What one chat's recorded usage says, or nothing.
	 * 
	 *  **`None` is the ordinary answer and it draws nothing**: a chat on a harness with no
	 *  `statusLine` (Codex, a shell), a Claude Code chat before its first turn, a chat whose
	 *  record charter would not read. `frame/slots.py`'s rule, which `recorded_context_gauge`
	 *  keeps: a gauge silently reading zero is worse than no gauge.
	 * 
	 *  Not on a blocking thread: it is one bounded read of a sixteen-line file.
	 */
	chatUsage: (plane: PlaneId, session: number) => typedError<{
	/**  `ctx NN%`: how full the context window was at the last turn that said. */
	context: Percent | null,
	/**  `cache NN%`: the share of the last turn's input served from cache. */
	cache: Percent | null,
	rebuilds: Rebuilds | null,
	/**
	 *  The session's recorded turns, oldest first, at most sixteen — the trend charter ADR
	 *  0038 names beside the gauge: the whole history rather than this turn.
	 */
	turns: UsageTurn[],
	/**
	 *  How many turns in a row the cache has been cold, once that is three or more
	 *  (`_cache_hint`'s threshold) — the prefix churning, which is the expensive failure.
	 */
	cold: number | null,
} | null, string>(__TAURI_INVOKE("chat_usage", { plane, session })),
	/**  The pin report for this plane. */
	planePin: (plane: PlaneId) => typedError<PinReport, string>(__TAURI_INVOKE("plane_pin", { plane })),
	/**
	 *  The About dialog's content.
	 * 
	 *  No plane, no disk, no state: the version is the bundle's and the changelog is compiled in.
	 *  A dialog that needed a project open could not be on the window's chrome, and the window
	 *  holds no project for the first moments of every launch.
	 */
	aboutCharter: () => __TAURI_INVOKE<About>("about_charter"),
	/**
	 *  Keeps the window's layout, replacing what the file held.
	 * 
	 *  `text` is the document as JSON text; the core parses it and writes it back out itself, so
	 *  what lands on disk is always a document charter wrote.
	 */
	writeLayout: (text: string) => typedError<null, string>(__TAURI_INVOKE("write_layout", { text })),
	/**
	 *  Moves the arrangement web storage held into the layout file — **only when there is no file
	 *  yet**. Answers whether it did, so the window knows the old key can go.
	 */
	adoptLayout: (text: string) => typedError<boolean, string>(__TAURI_INVOKE("adopt_layout", { text })),
};

/* Types */
/**  What charter says about itself. */
export type About = {
	/**  The version this build announces, dev suffix and all. */
	version: string,
	/**  Whether that version is released, a dev build, or not in the changelog. */
	build: Build,
	/**
	 *  The section shown: the version's own for a release, `[Unreleased]` otherwise. `None`
	 *  only when there is no such section to show.
	 */
	notes: Notes | null,
};

/**  One alert, as the drawer draws it. */
export type AlertRow = {
	/**
	 *  `warn` or `bad` — charter's two accents above plain text. `bad` is the one that loses
	 *  work if it is left: a nested plane, a memory commit that reached no remote.
	 */
	severity: string,
	/**
	 *  What it is about, in charter's word for it: `charter`, `front door`, `reinit`,
	 *  `nested plane`, `plane root`.
	 */
	subject: string,
	/**  What is wrong. */
	detail: string,
	/**  The command, or the step, that fixes it. */
	remedy: string,
};

/**
 *  The trust ask: what this plane will put in force, in the words the operator reads.
 * 
 *  **In the app the prompt IS the prompt** (ADR 0035). charter's CLI asks by printing a second
 *  command to type, because `util.py` has nothing that reads stdin and a hook blocked on stdin
 *  hangs a turn — a constraint about the CLI and about nothing else. Here there is a window
 *  and a person looking at it, so the question is asked where the answer is given.
 */
export type Ask = {
	/**
	 *  The plane charter resolved, which is what the approval is recorded against.
	 * 
	 *  Shown, and not merely carried: a picker pointed at a subdirectory opens the plane above
	 *  it, and an operator approving a directory they did not choose is the whole failure this
	 *  dialog exists to prevent, arrived at from the friendly end.
	 */
	path: string,
	/**
	 *  What it contributes. It goes back to [`approve_plane`] untouched, and that is what
	 *  makes the approval an answer to the question that was asked.
	 */
	contributes: PlaneContribution,
	/**
	 *  Empty when nothing has approved this plane. Otherwise every way it now differs from
	 *  what WAS approved, in charter's own words (`machine::Change`'s own `Display`).
	 */
	changes: string[],
	/**  Whether this is a first approval rather than a re-ask, so the dialog can say which. */
	first: boolean,
};

/**
 *  One reason a workspace holds work that deleting it would discard.
 * 
 *  A mirror of [`wscmd::AtRisk`] rather than the thing itself, because `charter-core` never
 *  depends on the app and the app's wire types are generated into TypeScript.
 */
export type AtRisk = {
	/**  What to look at: a clone's name, or `<repo>/<piece>` for a worktree. */
	what: string,
	/**  charter's own sentence about it, name included: `svc: 2 unpushed commit(s)`. */
	said: string,
};

/**  What kind of build this is, which decides which section is shown. */
export type Build = 
/**  The changelog has a section for this version. */
{ kind: "release" } | 
/**  A prerelease of `of`, the next version: `0.2.0-dev.42` is a dev build of `0.2.0`. */
{ kind: "dev"; of: string } | 
/**  A version with no section and no prerelease suffix. A local build of `main` is one. */
{ kind: "unlisted" };

/**  Everything the chat's gauge draws. Every part is absent when charter does not know it. */
export type ChatUsage = {
	/**  `ctx NN%`: how full the context window was at the last turn that said. */
	context: Percent | null,
	/**  `cache NN%`: the share of the last turn's input served from cache. */
	cache: Percent | null,
	rebuilds: Rebuilds | null,
	/**
	 *  The session's recorded turns, oldest first, at most sixteen — the trend charter ADR
	 *  0038 names beside the gauge: the whole history rather than this turn.
	 */
	turns: UsageTurn[],
	/**
	 *  How many turns in a row the cache has been cold, once that is three or more
	 *  (`_cache_hint`'s threshold) — the prefix churning, which is the expensive failure.
	 */
	cold: number | null,
};

/**  Where a chat is working, when it is working in a piece. */
export type ChatWorktree = {
	workspace: string,
	repo: string,
	piece: string,
	branch: string | null,
	wired: boolean,
	stale: boolean,
};

/**  What the doctor said, and what it was asked with. */
export type DoctorReport = {
	/**  Every row, in the order `charter doctor` prints them. */
	rows: DoctorRow[],
	/**  Whether the harness profiles were probed — the full doctor, not the preflight. */
	full: boolean,
	/**  Rows about THIS APP that `charter doctor` does not print. See the module note. */
	app_rows: DoctorRow[],
	/**
	 *  The `PATH` this process has, which is the one every row that looks for a program was
	 *  answered with.
	 * 
	 *  **Not a row, and not the doctor's**: `charter doctor` prints no such line, and this is
	 *  not dressed as one. It is here for the incident this module exists for — a Finder
	 *  launch hands the app a four-directory `PATH`, and a built-in profile the doctor does
	 *  not list (it lists one only when it finds its program) makes no sense until you can see
	 *  the `PATH` it was looked for on. `None` when the process has none at all, which is
	 *  itself the answer.
	 */
	path: string | null,
};

/**  One doctor row: the four fields `charter doctor --json` prints, and one it does not. */
export type DoctorRow = {
	name: string,
	status: DoctorStatus,
	detail: string,
	hint: string,
	/**
	 *  Whether this build runs this check at all ([`Row::deferred`]).
	 * 
	 *  `false` is about twenty rows on every plane, each a WARN that says *not checked (…not
	 *  ported…)*. They are drawn, because a doctor that dropped them would read as those
	 *  problems being fixed — but a summary that COUNTED them would draw a warning count that
	 *  never moves, and the one real warning among them would be invisible on its first day.
	 */
	checked: boolean,
};

/**  A row's verdict, as the window draws it. */
export type DoctorStatus = "ok" | "warn" | "fail";

/**
 *  The question charter asks before an extension contributes anything.
 * 
 *  A mirror of [`extension::Prompt`] rather than the thing itself, because `charter-core` never
 *  depends on the app and the app's wire types are generated into TypeScript.
 * 
 *  **charter's own sentences travel with it rather than being written in the dialog.** That is
 *  the point of carrying them: a window that composed its own words about what an extension can
 *  reach could drift kinder than the truth one edit at a time, and the truth here is
 *  uncomfortable enough that kinder is the likely direction. Since charter-app#152 there are
 *  three of them, because the fingerprint note acquired an exception and an exception the window
 *  worded itself would be the same drift through a smaller door.
 */
export type ExtensionAsk = {
	/**  The id the record is keyed by, and the id the yes is recorded against. */
	id: string,
	/**  What to call it, as its own manifest does. */
	name: string,
	/**
	 *  Where it is. Shown and not merely carried: an extension is approved at a path, and one
	 *  re-installed from another directory is a different question.
	 */
	path: string,
	/**  Every contribution it declares, in charter's own words, one line each. */
	declares: string[],
	/**
	 *  The fingerprint of the bytes that were read to build this question. It goes back to
	 *  [`approve_extension`] untouched, so the yes is for what was shown.
	 */
	fingerprint: string,
	/**  Whether this is a first ask rather than a re-ask. */
	first: boolean,
	/**
	 *  `extension::RUNS_AS_YOU` — that a plugin runs with the operator's own access and that
	 *  the list above is a declaration, not a limit.
	 */
	runs_as_you: string,
	/**
	 *  `extension::FINGERPRINTED` — that the fingerprint catches a change and is not a
	 *  boundary.
	 */
	fingerprint_note: string,
	/**
	 *  `extension::state_note` — which one directory charter does NOT read, when this
	 *  extension declares one, and `null` when it declares none (charter-app#152).
	 * 
	 *  It travels for the same reason the other two do. The fingerprint note says charter read
	 *  every file in the directory; the exception to that sentence belongs on the same screen
	 *  as the sentence, in the core's words, or the wording has the defect #152 was opened over
	 *  one carve-out later.
	 */
	state_note: string | null,
};

/**  One row of "what has contributed what to this window". */
export type ExtensionRow = {
	id: string,
	/**  What to call it: its manifest's name when charter could read one, else its id. */
	name: string,
	path: string,
	/**  `approved`, `new` or `changed`. */
	standing: string,
	/**
	 *  The themes it is contributing **right now** — empty unless it is approved, so the row
	 *  says what is in force rather than what was asked for.
	 */
	themes_in_force: string[],
	/**  Every contribution it declares, whether or not any of it is in force. */
	declares: string[],
	/**
	 *  Why charter could not read it, when it could not. A row that contributes nothing says
	 *  why rather than going quiet.
	 */
	refused: string | null,
	/**  The question to ask about it, when there is one to ask. */
	ask: ExtensionAsk | null,
};

/**  One theme an approved extension is contributing, as the window receives it. */
export type ExtensionTheme = {
	/**  The extension it came from, so the window can say whose theme it is drawing. */
	extension: string,
	/**  What to call it, as the manifest does. */
	name: string,
	/**
	 *  The file's **text**, unparsed.
	 * 
	 *  **The vocabulary is `theme.ts`'s and the parser is `theme.ts`'s**, and this crate
	 *  deliberately does not grow a second one. `TOKENS` is the closed vocabulary charter owns
	 *  (ADR 0041 property 1) and `load` is the parse-and-re-emit that keeps a theme's bytes out
	 *  of a stylesheet (property 4); both are already written and already tested. A Rust parser
	 *  here would be a second vocabulary, and two vocabularies drift — which is property 1
	 *  turning into a lie by accident rather than by decision.
	 * 
	 *  It is the text the fingerprint was taken over, handed on rather than fetched again.
	 */
	text: string,
};

/**  How a number reads, as the window colours it — `charter_core::usage::Tone`. */
export type GaugeTone = "ok" | "warn" | "bad";

/**
 *  What has contributed what to this window — charter ADR 0041's item 2, and the thing every
 *  later decision about extensions is read off.
 */
export type InstalledExtensions = {
	/**
	 *  charter's own themes, which are compiled into the window and are never asked about.
	 *  Listed so that the answer to "what is contributing" is one list rather than one per
	 *  source.
	 */
	built_in_themes: string[],
	extensions: ExtensionRow[],
	/**
	 *  Why the record could not be read, when it could not — in which case nothing an
	 *  extension declares is in force and `extensions` is empty.
	 */
	unreadable: string | null,
	/**  Rows the record held and charter dropped, with the reason for each. */
	dropped: string[],
};

/**
 *  What a launch had to go on, and what came of it.
 * 
 *  **Three states, and none of them is an error.** The app has to come up holding no plane at
 *  all and stay useful — that is what an opener attaches to — and "there is no plane where you
 *  launched me" is a different thing to tell an operator from "you have not opened one yet".
 *  A window double-clicked from the dock has a working directory of `/` and is the second;
 *  `charter` run in a directory that is in no plane is the first.
 * 
 *  They are told apart by shape rather than by reading a sentence: `plane` set is a plane in
 *  hand, `from` set without it is a directory that is in no plane, and neither is a launch
 *  that was given nothing to go on.
 */
export type Launch = {
	/**  The plane this launch opened, and the id every command for it names. */
	plane: PlaneId | null,
	/**
	 *  The directory the launch was given, when it could be read. A HINT and nothing more:
	 *  it is resolved once, here, and no command consults the working directory again.
	 */
	from: string | null,
	/**  Why no plane was opened, in the resolver's own words. */
	why: string | null,
};

/**  What a merge did, for the window to report. */
export type Merged = {
	branch: string,
	was: string,
	now: string,
};

/**
 *  The event the window listens for. One chat, its state, whether it is asking for you.
 * 
 *  **The plane travels with it, and that is not decoration.** Every plane numbers its chats
 *  from one, so a window holding two of them would be told "session 3 is waiting" twice about
 *  two different chats. The pair is the identity; one half of it is a guess.
 */
export type Moved = {
	plane: PlaneId,
	session: number,
	state: string,
	needs_you: boolean,
	/**
	 *  Every chat asking for you, so the queue is never assembled from a series of events
	 *  the window might have missed one of.
	 */
	queue: number[],
	/**
	 *  When this chat last moved, as a count of moves on its plane's board — bigger is
	 *  more recent. `charter_core::state::Board::moved_at` is the whole definition.
	 * 
	 *  **The window cannot work this out for itself, which is why it rides an event that
	 *  already fires.** Charter ADR 0039 sorts the chat strip's overflow menu by last
	 *  activity, and nothing in the window knows when a chat did anything: the strip is
	 *  `tabs.order`, which is an opening order, and the needs-you queue is oldest-first,
	 *  which is a different fact. An order computed in the window would also restart at
	 *  every launch and disagree between two windows on one plane, where this one is the
	 *  board's and the board is the plane's.
	 * 
	 *  A count rather than a clock, and a `u32` rather than a `u64`: both are argued where
	 *  the field is produced, and the second is not negotiable here — `specta` refuses to
	 *  export a `u64` and the app panics at startup in a debug build when one is reached
	 *  for.
	 */
	moved_at: number,
};

/**  One news entry, as the pin's dialog lists it. */
export type NewsItem = {
	version: string,
	headline: string,
};

/**  One section of the changelog, as the dialog draws it. */
export type Notes = {
	/**  The heading's version: `0.1.0`, or `Unreleased`. */
	version: string,
	/**  The date the heading gives, for a released version. */
	date: string | null,
	/**
	 *  The section as Markdown: `### Added`, `### Changed`, `### Fixed` and their bullets.
	 *  Empty for an `[Unreleased]` that has nothing in it yet.
	 */
	markdown: string,
};

/**  What a check found, for the window and for the notification. */
export type Offer = {
	/**  The version on offer. */
	version: string,
	/**  The version running now. */
	current: string,
	/**  The channel it came from, so a surface never has to guess which manifest was read. */
	channel: string,
	/**  The release notes, as the manifest carries them. */
	notes: string,
};

/**  One chat the app has open, as the UI draws it and as the quit warning lists it. */
export type OpenChat = {
	session: number,
	name: string,
	cwd: string | null,
	/**  The harness it runs, by the word the plane calls it — or none for a shell. */
	harness: string | null,
	/**  Whether it is the chat to show: at a launch, the one that was in front at the quit. */
	in_front: boolean,
	/**  The conversation it was resumed by, where it was. The UI says which happened. */
	resumed: string | null,
	/**  Why it is a new chat rather than the one it was, where it is. */
	fresh: string | null,
	/**  The harness profile it started on, where it started on one. */
	profile: string | null,
	/**  The persona it adopted. */
	persona: string | null,
	/**  What its harness cannot tell charter, said on the chat — none where it tells all. */
	unreported: string | null,
	/**
	 *  Whether the operator pinned it (charter ADR 0039). It rides the plane's own app
	 *  record, so a pinned chat comes back pinned at the next launch.
	 */
	pinned: boolean,
};

/**
 *  What came of asking to open a plane: it is open, or there is a question to answer first.
 * 
 *  Two nullable fields rather than a tagged union, and told apart by shape the way
 *  `plane_at_launch` is: exactly one of them is ever set, and a window that reads `plane`
 *  first cannot accidentally treat an ask as an open.
 */
export type Opened = {
	/**  The plane, once it is open. Null when the operator has to be asked first. */
	plane: PlaneId | null,
	/**  What to ask them. Null when the plane is open. */
	ask: Ask | null,
};

/**  One part of a panel's body. */
export type PanelBlock = { kind: "list"; rows: PanelRow[]; empty: PanelEmpty } | { kind: "note"; text: string; tone: string };

/**
 *  What opens when a row is opened, as the window receives it.
 * 
 *  A mirror of [`panel::Detail`] rather than the thing itself, for the reason
 *  [`crate::extensions::ExtensionAsk`] is one: `charter-core` never depends on the app, and the
 *  app's wire types are what generate `app/src/bindings.ts`.
 */
export type PanelDetail = 
/**  The row's own words, in full. The only kind a contributed panel may use. */
{ kind: "text"; text: string } | 
/**
 *  What this plane says this persona is. **A name and not an answer**: the window asks
 *  `persona_details` when the card opens, because a definition is a file an operator edits
 *  while charter is running, and because folding it in here would read every persona's
 *  definition on every workspace focus for something nobody has asked to see.
 */
{ kind: "persona"; persona: string };

/**  What a list says when it has no rows. */
export type PanelEmpty = {
	headline: string,
	body: string | null,
	/**
	 *  The catalogue row the empty state offers as a way out. charter's own, for `runs`'s
	 *  reason.
	 */
	offer: string | null,
};

/**  One row of a panel's list. */
export type PanelRow = {
	key: string,
	text: string,
	/**  A short trailing note — a date, a word like `default`. */
	note: string | null,
	/**
	 *  A word out of [`panel::Mark`]'s closed set. The window maps it to a glyph it already
	 *  ships; a word it does not know draws the plain one rather than nothing, because a
	 *  missing icon is cosmetic and a missing row is not.
	 */
	mark: string,
	/**  A word out of [`panel::Tone`]'s closed set. */
	tone: string,
	detail: PanelDetail | null,
	/**
	 *  The catalogue row this runs when pressed (`app/src/actions.ts`), or nothing.
	 * 
	 *  **Never set from a manifest** — `charter_core::panel`'s header has the whole of why, and
	 *  `panel::NO_VERB` is the sentence an extension that tried gets. What is here comes from
	 *  charter's own contributions, below, and the window looks the id up in the catalogue: a
	 *  row cannot invent a verb even here.
	 */
	runs: string | null,
};

/**  One open todo. There is no state field: a closed todo is a deleted file (ADR 0004). */
export type PanelTodo = {
	/**  The file stem, which is what a todo is closed by. */
	slug: string,
	title: string,
	/**  The date the todo was written, as the file records it. */
	stamp: string,
};

/**
 *  A panel, as the window receives it: a key, a title, an ordering and a body.
 * 
 *  **This is the whole of what a panel is**, and the window's renderer takes nothing else. That
 *  is the test of the contract: charter's own todos and personas arrive in this shape, an
 *  approved extension's declared panel arrives in this shape, and `app/src/Panels.tsx` cannot
 *  tell them apart except by [`Self::from`] — which it draws, because ADR 0041 item 5 says what
 *  is in force is shown after approval and not only at it.
 */
export type PanelView = {
	/**  `charter/<id>` or `ext/<extension>/<id>` — see `panel::Panel::key`. */
	key: string,
	title: string,
	order: number,
	mark: string,
	blocks: PanelBlock[],
	/**  The extension that contributed it, or `null` for charter's own. */
	from: string | null,
};

/**  Everything the panels can draw without running git. */
export type Panels = {
	/**
	 *  The workspace this is about, so a late answer can be matched to the ask and an answer
	 *  for a workspace that is no longer focused can be thrown away.
	 */
	workspace: string,
	/**  The clones on disk, by name, in the order the directory lists them. */
	repos: string[],
	/**  Repos `workspace.json` names that are not cloned here. Membership, not presence. */
	absent: string[],
	/**
	 *  What charter would not look at, by name and reason. Shown, never dropped: a row that
	 *  is missing is otherwise merely missing.
	 */
	refused: ([string, string])[],
	todos: PanelTodo[],
	/**
	 *  Why the todos could not be read, where they could not. A store that is a link out of
	 *  the plane is refused, and "no todos" would be the wrong thing to draw for it.
	 */
	todos_refused: string | null,
	/**  The plane's personas, and the one a chat started here would adopt. */
	personas: string[],
	persona: string | null,
	/**
	 *  **The same facts again, as contributions** — charter's own two panels, in the shape a
	 *  stranger's extension contributes one in (`charter_core::panel`).
	 * 
	 *  # Why the fields above survived, which is a decision and not an oversight
	 * 
	 *  `todos`, `personas` and `persona` are not panel bodies. They are facts about the
	 *  workspace that three other surfaces read: the status line counts the todos, the
	 *  catalogue builds a `persona.show:<name>` row per persona, and a test pins the default.
	 *  Deleting them would have moved those three onto a shape designed for drawing, which is
	 *  the opposite of the separation this change is for. **What moved is the drawing**:
	 *  `Panels.tsx` reads `contributed` and nothing else, so the panels on screen do come
	 *  through the seam.
	 * 
	 *  # And why they are in THIS call, when the brief said a contributed panel cannot be
	 * 
	 *  The thing a contributed panel cannot be is a *field*. `Panels` names `todos` and
	 *  `personas`; there is no field for a panel nobody has written yet, and there is no
	 *  honest way to add one. A *list* has room for every contributor. The round trip was never
	 *  the problem, and splitting it would cost something real: focusing a workspace has 100 ms
	 *  and this command is the one that has to answer inside it.
	 * 
	 *  **A contributed panel needs no round trip of its own, and that is a fact about stage 1.**
	 *  With no executor there is nothing to ask: an extension's panel is declared, so its rows
	 *  came off the disk at survey time, and charter's own are produced from the plane read
	 *  this command already does. The day an executor lands, a panel that wants live rows asks
	 *  its extension — and that is a second call, made when the panel is drawn, and it is stage
	 *  2's to design.
	 */
	contributed: PanelView[],
};

/**  One percentage on the gauge, and the tone its threshold gives it. */
export type Percent = {
	/**
	 *  A whole percentage. `i32`, because `specta` refuses the core's `i64`, and a recorded
	 *  value outside it is not a percentage anyone could read anyway.
	 */
	value: number,
	tone: GaugeTone,
};

/**
 *  What one persona says about itself, for the row a reader clicked.
 * 
 *  **The vault is a NAME and nothing else.** charter refuses a secret by kind and never
 *  echoes one, and a panel is the last place that rule should get a special case: this struct
 *  carries the word `vault: <name>` puts in the definition, so the window can say which vault
 *  a chat as this persona would open. Nothing here ever reads the vault.
 */
export type PersonaDetails = {
	name: string,
	/**  `role:`, inherited-inclusive. */
	role: string | null,
	/**
	 *  `delegate-when:` — the work that should come to this persona, which is what makes it
	 *  findable and what a router reads.
	 */
	delegate_when: string | null,
	/**  `tools:`, the union down the `extends:` chain. */
	tools: string[],
	/**  The vault's name, where the definition declares one. */
	vault: string | null,
	/**
	 *  Whether the definition declares `vault: none` — that it holds no credentials at all.
	 * 
	 *  **Separate from `vault` being absent, and the window must keep them apart.** charter's
	 *  own `vault_of` falls back to a vault tagged with this persona in the registry, and
	 *  nothing in Rust reads that registry yet — so "no `vault:` line" means charter-app has
	 *  not looked, not that there is nothing. Drawing the two the same way would have the
	 *  window claim a persona holds no credentials on the strength of a file nobody read.
	 */
	declares_no_vault: boolean,
	/**  The `extends:` chain, child first. One name long for a persona that extends nothing. */
	lineage: string[],
	/**  The definition file, relative to the plane. */
	file: string,
};

/**  One piece, as the window shows it. */
export type Piece = {
	piece: string,
	path: string,
	branch: string | null,
	/**
	 *  Whether charter's harness layer is in this tree.
	 * 
	 *  Since M1.x a worktree charter cuts is wired as it is cut, so `false` now means a tree
	 *  cut by plain git, one whose wire did not land, or a plane with no layer to carry. The
	 *  row still says so, because a chat in such a tree runs without the plane's ask/deny
	 *  rules, without its persona's agents and without `$CHARTER_HARNESS` — and starting one
	 *  there is what writes the layer or refuses.
	 */
	wired: boolean,
	/**  Set when git still has a registration whose directory is gone. */
	stale: boolean,
};

/**  What the plane's pin says against this charter. */
export type PinReport = {
	/**  `charter version`'s verdict: its exit status was 1. The only thing the line keys on. */
	drift: boolean,
	/**  This charter's version: the app's (`adopt::app_version`, ADR 0045). */
	brought: string,
	/**  `[charter] version` as written, or none. */
	pinned: string | null,
	/**  What `charter version` said, line by line, in its own words. */
	said: string[],
	/**  What the news corpus has between the pin and this charter's version — only on drift. */
	news: NewsItem[],
	/**  How many more entries there were than `news` carries. */
	more_news: number,
};

/**
 *  What the operator has pinned in one project (charter ADR 0039, stored per ADR 0040).
 * 
 *  The project's own pin and its pinned workspaces come from the machine store; a pinned
 *  CHAT is not here, because a chat pin rides that chat's own record and reaches the window
 *  on `OpenChat::pinned` with the chat it is about.
 */
export type Pins = {
	/**  Whether this project itself is pinned. */
	project: boolean,
	/**
	 *  Its pinned workspaces that still exist, in the plane's own order.
	 * 
	 *  The plane's order and never the pin's: a pin says WHICH workspaces come first, not in
	 *  what order they do, so two operators who pin the same two see the same arrangement.
	 */
	workspaces: string[],
	/**
	 *  Pins that no longer name a workspace on the plane — renamed, or removed.
	 * 
	 *  **Named rather than dropped silently**, and never drawn as a workspace: a window that
	 *  drew one would be offering a workspace the plane does not have. This is ADR 0034's
	 *  own hazard for a trust entry keyed on a path, one scope down.
	 */
	missing: string[],
};

/**  One open project's alerts. */
export type PlaneAlerts = {
	plane: PlaneId,
	alerts: AlertRow[],
	/**
	 *  Why charter stopped looking before the last alert, or null when it looked at every one.
	 *  **The alerts above stand, and their number is not this project's number of alerts** —
	 *  a count drawn from a reading that stopped would be smaller than the truth with nothing
	 *  on it saying so.
	 */
	stopped: string | null,
};

/**
 *  What a plane would contribute, as the trust prompt draws it — **and the exact value the
 *  operator's approval is checked against.**
 * 
 *  A mirror of [`machine::Contribution`] rather than the thing itself, because `charter-core`
 *  never depends on the app and the app's wire types are generated into TypeScript. Each of
 *  the four maps travels as pairs in the map's own order, which is `BTreeMap`'s and therefore
 *  sorted, so a value that comes back from the window compares against one taken from disk
 *  without either side having to sort anything.
 */
export type PlaneContribution = {
	/**
	 *  Each plugin the plane's committed settings enable, and what they enable it as. These
	 *  run inside the operator's harness.
	 */
	plugins: ([string, string])[],
	/**
	 *  Each environment variable those settings set, and its value. ADR 0022 measured where
	 *  these land: a variable set on the harness process reaches the shell the model runs.
	 */
	env: ([string, string])[],
	/**
	 *  One line per chat the plane's reopen record would start on a program of its own — the
	 *  program, its arguments and its directory, as the record names them.
	 */
	starts: ([string, string])[],
	/**
	 *  One line per chat that record would start on one of THIS machine's harness profiles.
	 *  Drawn beside the rest and weighed differently: the record chooses which of the
	 *  operator's own profiles runs, and `profiletrust` gates what any of them runs.
	 */
	profiles: ([string, string])[],
};

/**
 *  Which plane something is acting for.
 * 
 *  It is the plane's root as the registry resolved it, and it is minted by [`Planes::open`]
 *  alone — a caller hands one back, it never spells one. Two spellings of one directory would
 *  otherwise be two entries in the registry holding two boards for one plane on disk, which
 *  is the "acting on the wrong plane" defect wearing a different hat.
 */
export type PlaneId = string;

/**
 *  One row of the profile picker: what it runs, where charter read it, and what pressing
 *  Enter on it would do.
 */
export type ProfileRow = {
	name: string,
	kind: string,
	/**
	 *  The environment and the command as one line a person reads, already contained: a
	 *  profile is a file a chat can write, and a control byte in it must never redraw a row.
	 */
	shown: string,
	/**  `built-in` or `charter.local.toml`. */
	source: string,
	/**  The row the picker starts on. It launches nothing by itself. */
	is_default: boolean,
	/**
	 *  `new` or `changed` when this profile's command must be shown and approved before it
	 *  runs; absent when charter has already recorded running exactly this.
	 */
	approval: string | null,
};

/**  The prefix rebuilds this conversation has paid for (`↻N 696k`). */
export type Rebuilds = {
	count: number,
	/**
	 *  The total, already spelled as charter spells tokens (`696k`, `1.2M`), so the window
	 *  and the frame's panel cannot come to round it differently.
	 */
	cost: string,
	tone: GaugeTone,
};

/**
 *  One plane this machine remembers, as the opener draws it.
 * 
 *  **When it was last opened is not here**, though the store holds it: it is what puts the
 *  list in order, and the list is already in that order when it arrives. Carrying it would be
 *  carrying a `u64` across the wire for nobody to draw — and specta refuses to export one at
 *  all, to avoid the precision loss a JavaScript number would silently have. A row that says
 *  "three days ago" can have it as a number this side of that limit, when there is a row that
 *  says it.
 */
export type RecentPlane = {
	/**  The plane's root: the path it was approved under and the path it will be opened by. */
	path: string,
	/**
	 *  What to call it in a list — the directory's own name. Two projects can share one, so
	 *  the path is shown beside it and is what identifies the row.
	 */
	name: string,
	/**
	 *  Whether the operator has approved this plane before.
	 * 
	 *  **Not a promise that opening it will not ask.** Whether it still contributes what they
	 *  approved is a question about the plane's own files, and it is asked when the plane is
	 *  opened. This is only what the store holds, which costs no disk at all — sixty-four
	 *  rows each reading a settings file and a reopen record, to label a list, is a launch
	 *  spent answering a question the next click answers properly.
	 */
	approved: boolean,
};

/**  What the opener has to offer, and everything it had to leave out to offer it. */
export type Recents = {
	/**  Most recently opened first. */
	planes: RecentPlane[],
	/**
	 *  One line per row charter would not offer: a plane that has moved or gone, and an entry
	 *  the store itself would not take back.
	 * 
	 *  **Never an error, and never a dialog.** ADR 0034: the file is a convenience and the
	 *  plane is the truth, so a launch that showed a modal about a memory stick that is not
	 *  plugged in would be worse than the thing it was reporting.
	 */
	dropped: string[],
	/**
	 *  Why this machine remembers nothing at all, in charter's own words — a platform charter
	 *  keeps no store on (ADR 0031: `0600` has no expression on Windows, so the guard refuses
	 *  rather than degrades), or a store charter would not read. Null when it does remember.
	 * 
	 *  The app is a working app either way. It just opens every project by picking it.
	 */
	forgetful: string | null,
};

/**
 *  Why a delete made nothing — **and the reading it was refused on** (charter-app#182).
 * 
 *  Two fields and they are one answer. `said` is the core's sentence, verbatim, because it
 *  names the repair. `at_risk` is `work_at_risk`'s list as the core read it *inside* the
 *  delete, so the surface offering to discard that work names the same things the sentence
 *  above it names. Empty for every refusal that is not the guard's — a name that is not a
 *  workspace, a `workspaces/<ws>` that links out of the plane, a `remove_dir_all` that failed
 *  — and that is the honest shape: `--force` does not get past any of those, so a window that
 *  drew a force button beside one would be offering a way through that does not exist.
 */
export type Refused = {
	/**  The core's own words, unchanged and all of them. */
	said: string,
	/**  What the core refused on, in the order it said them. */
	at_risk: AtRisk[],
};

/**  One clone's git state, and what the forge cache last recorded for its branch. */
export type RepoState = {
	name: string,
	/**  The branch the checkout is on, where it is on one. */
	branch: string | null,
	/**  Whether that branch holds no commit yet. */
	unborn: boolean,
	/**  The commit HEAD sits on when it is on no branch. */
	detached: string | null,
	upstream: string | null,
	ahead: number,
	behind: number,
	/**  Changed files git is tracking. */
	tracked: number,
	/**  Files git is not tracking. */
	untracked: number,
	/**
	 *  Why charter could not read the tree. Every count above is zero when this is set, and
	 *  it means charter does not know — not that the tree is clean.
	 */
	unreadable: string | null,
	/**  What the forge cache last recorded, one of the seven states charter knows. */
	ci: string | null,
	change: number | null,
	sigil: string | null,
	/**  How long ago the cache entry was written, which is how old this answer is. */
	fetched_seconds_ago: number | null,
	/**
	 *  Why there is nothing from the forge to show. Absent when something was fetched, even
	 *  when what was fetched named no pipeline.
	 */
	not_fetched: string | null,
};

/**  Every clone of one workspace, as the panels draw them. */
export type RepoStates = {
	workspace: string,
	repos: RepoState[],
	/**
	 *  Why the forge cache was not read at all, where it was not. Reported once for the
	 *  listing rather than repeated on every row.
	 */
	cache_refused: string | null,
};

/**
 *  What a cold launch puts back: the projects that were open, and what it would not take back.
 * 
 *  **A project that has moved or is gone is dropped with a line saying so, never an error
 *  dialog** (ADR 0033). The window draws those lines where the operator is standing, the way
 *  the opener draws a recents row that went.
 */
export type Restore = {
	/**  The projects to open again, left to right as the tabs were. */
	planes: string[],
	/**
	 *  Which of them was in front, as an index into `planes` after the drops. Null when there
	 *  is nothing to put back.
	 */
	active: number | null,
	/**  One line per project charter would not take back. */
	dropped: string[],
};

/**
 *  The whole left-hand side: every workspace with its chats, and the focused workspace's
 *  persona and todos.
 */
export type Sidebar = {
	root: string,
	workspaces: SidebarWorkspace[],
	/**  The plane's personas, and the one a new chat here would adopt. */
	personas: string[],
	persona: string | null,
	/**  Chats whose directory is in no workspace, so the sidebar can still show them. */
	unfiled: OpenChat[],
};

/**
 *  One workspace as the sidebar draws it: what it is for, what it still means to do, and the
 *  chats working in it.
 */
export type SidebarWorkspace = {
	name: string,
	/**  Where the workspace is, so a chat can be started in it. */
	path: string,
	vision: string,
	todos: string[],
	chats: OpenChat[],
};

/**  Everything the picker draws, read from the plane when it is opened. */
export type StartOptions = {
	profiles: ProfileRow[],
	/**
	 *  Profiles charter read and will not use, by name and reason, so a row that is missing
	 *  is never merely missing.
	 */
	refused: ([string, string])[],
	personas: string[],
	/**  The plane's `[persona] default`, which is the persona row the picker starts on. */
	persona: string | null,
	/**
	 *  Set when git would carry `charter.local.toml`: every declared profile is refused
	 *  until it is fixed, and this is the one fix for that state.
	 */
	ignore_fix: string | null,
	/**
	 *  Whether this plane declares no profiles of its own. The built-ins still start, and
	 *  the picker says so rather than looking empty or broken.
	 */
	declares_none: boolean,
};

/**
 *  A chat that started: its session, and the one line to say if charter wired its profile
 *  on the way.
 */
export type Started = {
	session: number,
	wired: string | null,
};

/**  What the operating system has already spent of the window's own title bar. */
export type TitleBarRoom = {
	/**
	 *  Whether charter's bar is drawn UNDERNEATH the system's window controls.
	 * 
	 *  True only where `tauri.conf.json`'s `titleBarStyle: "Overlay"` is honoured, which is
	 *  macOS alone — every other platform ignores the key and keeps drawing its own title bar
	 *  above the webview, so charter's bar is a row inside the window rather than the title
	 *  bar itself, and nothing is reserved.
	 */
	overlaid: boolean,
	/**  How many CSS pixels at the leading edge the system's controls occupy, or zero. */
	reserved: number,
};

/**  One turn of the trend. */
export type UsageTurn = {
	/**  The share of that turn's input served from cache, in its tone. */
	cache: Percent | null,
	/**  The context percentage that turn recorded, in its tone. */
	context: Percent | null,
	/**  What that turn wrote to the cache, as charter spells tokens. */
	written: string | null,
};

/**
 *  A view a pane has open, and what its terminal has to match to show the session as it is:
 *  the size the screen was drawn for, so what was wrapped stays wrapped, and how much history
 *  the core is keeping, so the pane keeps the same.
 */
export type Watching = {
	view: number,
	columns: number,
	rows: number,
	scrollback: number,
};

/**
 *  What a window is holding, as it says so itself.
 * 
 *  One struct rather than two arguments, so that the tabs and the tab in front cannot be sent
 *  separately and disagree — and because a `Vec<PlaneId>` keeps its own name here, where a
 *  plane inside an `Option` argument does not.
 */
export type WindowTabs = {
	/**  The projects this window holds, left to right as its tabs show them. */
	planes: PlaneId[],
	/**
	 *  Which tab is in front. Null is the opener — the window is holding projects the
	 *  operator is not looking at, or holding none at all.
	 */
	active: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

