// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  The window says its first frame is on screen, which is where cold start ends.
	 * 
	 *  It is silent unless `CHARTER_BENCH_LOG` is set — only `tools/bench.mjs` sets it — so in
	 *  an ordinary run this is one IPC call at startup that does nothing.
	 */
	firstFrame: () => __TAURI_INVOKE<void>("first_frame"),
	/**  The plane the app was started in, or why there is none. */
	planeRoot: () => typedError<string, string>(__TAURI_INVOKE("plane_root")),
	/**
	 *  Starts a session, and remembers it as a chat so a quit can write it down. No program is
	 *  the operator's shell.
	 */
	openSession: (program: string | null, args: string[], cwd: string | null, name: string, columns: number, rows: number) => typedError<number, string>(__TAURI_INVOKE("open_session", { program, args, cwd, name, columns, rows })),
	/**  Ends a session and everything it started. It is no longer a chat a quit would record. */
	closeSession: (session: number) => typedError<null, string>(__TAURI_INVOKE("close_session", { session })),
	/**  Sends what a pane typed to the session's program. */
	sendInput: (session: number, text: string) => typedError<null, string>(__TAURI_INVOKE("send_input", { session, text })),
	/**  Tells a session how big the pane showing it now is. */
	resizeSession: (session: number, columns: number, rows: number) => typedError<null, string>(__TAURI_INVOKE("resize_session", { session, columns, rows })),
	/**
	 *  Opens a view of a session for a pane that is now on screen: the channel is sent the screen
	 *  as it already is, and then the session's output. Answers with the id that closes the view.
	 */
	watchSession: (session: number, output: Channel<string>) => typedError<Watching, string>(__TAURI_INVOKE("watch_session", { session, output })),
	/**  Closes a view, for a pane that has gone off screen. The session keeps running. */
	unwatchSession: (session: number, view: number) => typedError<null, string>(__TAURI_INVOKE("unwatch_session", { session, view })),
	/**  The sessions that are running, in the order they were opened. */
	runningSessions: () => __TAURI_INVOKE<number[]>("running_sessions"),
	/**
	 *  What every chat is doing, and which of them are asking for you.
	 * 
	 *  The window asks once, when it opens; after that it is told (`chat-moved`). A chat the app
	 *  has never heard from is `unknown`, which is what the spec says a harness with no state
	 *  hook shows.
	 */
	chatStates: () => __TAURI_INVOKE<Moved[]>("chat_states"),
	/**
	 *  Why this chat can never report its state, where it cannot.
	 * 
	 *  Codex is the case: its hooks live only in a machine-wide file, and it fires no
	 *  `Notification` at all. A chat showing `unknown` with no reason looks like charter is
	 *  broken rather than like the harness is different.
	 */
	whyUnknown: (session: number) => __TAURI_INVOKE<string | null>("why_unknown", { session }),
	/**
	 *  The chats the app already has open — at a launch, the ones put back from the record.
	 * 
	 *  The window asks this instead of opening its own: putting the record back happens before
	 *  there is a window, so that a relaunch does not depend on a webview having run.
	 */
	openedChats: () => __TAURI_INVOKE<OpenChat[]>("opened_chats"),
	/**
	 *  The chats this launch could not start, by name and reason. They are still recorded, and
	 *  will be tried again at the next launch.
	 */
	chatsThatWouldNotStart: () => __TAURI_INVOKE<([string, string])[]>("chats_that_would_not_start"),
	/**  Says which chat is in front, so the record brings that one back in front. */
	chatInFront: (session: number | null) => __TAURI_INVOKE<void>("chat_in_front", { session }),
	/**
	 *  Asks the app to quit, the way the menu's Quit and the tray's do.
	 * 
	 *  It is the same function they call, so what this goes through is the real path: the ask
	 *  is counted, the window is shown, and the window is sent `quit-asked`. The command
	 *  palette's own quit action is this too.
	 */
	askToQuit: () => __TAURI_INVOKE<void>("ask_to_quit"),
	/**  The window's answer to being asked to quit: go. */
	quit: () => __TAURI_INVOKE<void>("quit"),
	/**  The window's answer to being asked to quit: not now. The next ask warns again. */
	quitCancelled: () => __TAURI_INVOKE<void>("quit_cancelled"),
	/**  Hides the window, which is what its close button does. Every session keeps running. */
	hideWindow: () => __TAURI_INVOKE<void>("hide_window"),
	/**  Whether the window is on screen. The scenario tests ask; nothing in the UI does. */
	windowShowing: () => __TAURI_INVOKE<boolean>("window_showing"),
	/**
	 *  The sidebar, read from the plane on disk every time it is asked for.
	 * 
	 *  Read fresh rather than cached: the plane is a directory the operator also edits by hand
	 *  and another charter process writes, so a cache here would be a second answer to "what is
	 *  on disk" that nothing invalidates.
	 * 
	 *  The chats are the ones `Chats` already holds — one model of a chat, not a second derived
	 *  from the sessions. What files one under a workspace is the directory it works in, because
	 *  nothing on the plane records a chat: `.charter/frame/` belongs to the tmux frame and the
	 *  app stays out of it.
	 */
	planeSidebar: () => typedError<Sidebar, string>(__TAURI_INVOKE("plane_sidebar")),
	/**
	 *  What the picker draws: every profile this machine has, every one charter will not use,
	 *  and the plane's personas.
	 * 
	 *  Read fresh every time it is opened, like the sidebar: `charter.local.toml` is a file the
	 *  operator edits by hand and a chat can write, so a cache here would be a second answer to
	 *  "what is on disk" that nothing invalidates.
	 */
	startOptions: () => typedError<StartOptions, string>(__TAURI_INVOKE("start_options")),
	/**
	 *  Records that the operator approved running this profile's command, exactly as it stands.
	 * 
	 *  Its own command, and a separate click from the one that starts the chat: this IS the
	 *  approval, and a command that both asked and ran would be asking nothing.
	 */
	approveProfile: (name: string) => typedError<null, string>(__TAURI_INVOKE("approve_profile", { name })),
	/**
	 *  Starts a chat on a harness profile, with a persona.
	 * 
	 *  A command of its own rather than a flag on `open_session`, so neither can be mistaken
	 *  for the other by a caller passing null: this one goes through every gate a launch has,
	 *  and that one opens the operator's shell.
	 */
	startChat: (profile: string, persona: string | null, cwd: string | null, name: string, columns: number, rows: number) => typedError<Started, string>(__TAURI_INVOKE("start_chat", { profile, persona, cwd, name, columns, rows })),
};

/* Types */
/**  The event the window listens for. One chat, its state, whether it is asking for you. */
export type Moved = {
	session: number,
	state: string,
	needs_you: boolean,
	/**
	 *  Every chat asking for you, so the queue is never assembled from a series of events
	 *  the window might have missed one of.
	 */
	queue: number[],
};

/**  One chat the app has open, as the UI draws it and as the quit warning lists it. */
export type OpenChat = {
	session: number,
	name: string,
	cwd: string | null,
	/**  The harness it runs, by the word the plane calls it — or none for a shell. */
	harness: string | null,
	/**  Whether it is the chat to show: at a launch, the one that was in front at the quit. */
	in_front: boolean,
	/**  The conversation it was resumed by, where it was. The UI says which happened. */
	resumed: string | null,
	/**  Why it is a new chat rather than the one it was, where it is. */
	fresh: string | null,
	/**  The harness profile it started on, where it started on one. */
	profile: string | null,
	/**  The persona it adopted. */
	persona: string | null,
};

/**
 *  One row of the profile picker: what it runs, where charter read it, and what pressing
 *  Enter on it would do.
 */
export type ProfileRow = {
	name: string,
	kind: string,
	/**
	 *  The environment and the command as one line a person reads, already contained: a
	 *  profile is a file a chat can write, and a control byte in it must never redraw a row.
	 */
	shown: string,
	/**  `built-in` or `charter.local.toml`. */
	source: string,
	/**  The row the picker starts on. It launches nothing by itself. */
	is_default: boolean,
	/**
	 *  `new` or `changed` when this profile's command must be shown and approved before it
	 *  runs; absent when charter has already recorded running exactly this.
	 */
	approval: string | null,
};

/**
 *  The whole left-hand side: every workspace with its chats, and the focused workspace's
 *  persona and todos.
 */
export type Sidebar = {
	root: string,
	workspaces: SidebarWorkspace[],
	/**  The plane's personas, and the one a new chat here would adopt. */
	personas: string[],
	persona: string | null,
	/**  Chats whose directory is in no workspace, so the sidebar can still show them. */
	unfiled: OpenChat[],
};

/**
 *  One workspace as the sidebar draws it: what it is for, what it still means to do, and the
 *  chats working in it.
 */
export type SidebarWorkspace = {
	name: string,
	/**  Where the workspace is, so a chat can be started in it. */
	path: string,
	vision: string,
	todos: string[],
	chats: OpenChat[],
};

/**  Everything the picker draws, read from the plane when it is opened. */
export type StartOptions = {
	profiles: ProfileRow[],
	/**
	 *  Profiles charter read and will not use, by name and reason, so a row that is missing
	 *  is never merely missing.
	 */
	refused: ([string, string])[],
	personas: string[],
	/**  The plane's `[persona] default`, which is the persona row the picker starts on. */
	persona: string | null,
	/**
	 *  Set when git would carry `charter.local.toml`: every declared profile is refused
	 *  until it is fixed, and this is the one fix for that state.
	 */
	ignore_fix: string | null,
	/**
	 *  Whether this plane declares no profiles of its own. The built-ins still start, and
	 *  the picker says so rather than looking empty or broken.
	 */
	declares_none: boolean,
};

/**
 *  A chat that started: its session, and the one line to say if charter wired its profile
 *  on the way.
 */
export type Started = {
	session: number,
	wired: string | null,
};

/**
 *  A view a pane has open, and what its terminal has to match to show the session as it is:
 *  the size the screen was drawn for, so what was wrapped stays wrapped, and how much history
 *  the core is keeping, so the pane keeps the same.
 */
export type Watching = {
	view: number,
	columns: number,
	rows: number,
	scrollback: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

