//! Python's `repr()` — how charter quotes a value back in a refusal (`f"{name!r}"`), so a
//! sentence the two implementations print is one sentence.
//!
//! # One repr, for every shape charter quotes
//!
//! This module is the crate's only `repr()`. It grew four rivals while M2's tickets were
//! worked in parallel — `scaffold::text::py_repr`, `profiles::py_repr_str`,
//! `doctor::fsx`'s inline quoting inside `py_os_error`, and a second JSON one in
//! `charter-cli`'s `memory` — each written from the same Python and each stopping somewhere
//! else. They disagreed on real values: a `\u{a0}` in a name came back escaped from one and
//! literal from another, and a container came back as `['a', 'b']` from one and as JSON
//! `["a","b"]` from the next. A refusal that quotes a value back differently depending on
//! which command refused is the second answer this port exists to prevent.
//!
//! So: [`repr_str`] for a string, [`repr_json`]/[`str_json`] for a decoded JSON document, and
//! [`repr_toml`]/[`str_toml`] for a parsed TOML value. Everywhere else delegates here.
//!
//! # `repr()` is NOT [`crate::shown::one_line`], and must not be folded into it
//!
//! Both escape "characters with no glyph" and the two sets are nearly the same, which is
//! exactly why the distinction has to be written down. They answer different questions:
//!
//! * `repr()` is Python's own function, and charter uses it where Python uses it — inside an
//!   f-string's `!r`. Its job is to reproduce CPython byte for byte. It ADDS QUOTES, chooses
//!   between `'` and `"` by what the value holds, escapes the backslash, and escapes by
//!   `str.isprintable` — which is false for every UNASSIGNED codepoint as well, so it is a
//!   set that SHRINKS as Unicode grows.
//! * [`crate::shown::one_line`] is charter's own containment rule (`charter/contain.py`). It
//!   adds no quotes, never touches a backslash, clips at a budget, and escapes by general
//!   category — a set that GROWS as Unicode grows.
//!
//! Folding either into the other breaks both. Giving `one_line` `repr`'s rule would quote
//! every workspace name a TUI prints and stop escaping the private-use and unassigned
//! codepoints containment cares about; giving `repr` `one_line`'s rule would put a `…` in the
//! middle of a refusal and print the codepoints CPython escapes. The one thing they share is
//! the source of "which characters are which", and that is now one generated file
//! (`crate::tui::tables`) rather than two tables to keep in step.

/// `repr(s)`.
///
/// Single quotes unless the text holds one and no double quote. The backslash, the quote in
/// use, `\t`, `\n` and `\r` get their short escapes; any other character Python does not
/// count as printable gets `\xNN`, `\uNNNN` or `\UNNNNNNNN` by size. Letters of any script
/// stay themselves, as they do in Python.
pub fn repr_str(s: &str) -> String {
    let quote = if s.contains('\'') && !s.contains('"') {
        '"'
    } else {
        '\''
    };
    let mut out = String::new();
    out.push(quote);
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '\t' => out.push_str("\\t"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            c if c == quote => {
                out.push('\\');
                out.push(c);
            }
            c if !printable(c) => {
                let cp = c as u32;
                if cp < 0x100 {
                    out.push_str(&format!("\\x{cp:02x}"));
                } else if cp < 0x10000 {
                    out.push_str(&format!("\\u{cp:04x}"));
                } else {
                    out.push_str(&format!("\\U{cp:08x}"));
                }
            }
            c => out.push(c),
        }
    }
    out.push(quote);
    out
}

/// `str.isprintable()` for one character — the whole of it, as CPython answers it.
///
/// **It used to be a hand-written approximation, and the approximation was wrong in both
/// directions.** It read "controls, every separator but the ASCII space, and the format
/// characters that render as nothing", with a note conceding that a codepoint it called
/// printable and Python did not would be quoted as itself where Python escapes it. Measured
/// against CPython 3.13, that was nine `Cf` ranges (U+0890, U+08E2, U+110BD, U+110CD,
/// U+13430–U+1343F, U+1BCA0–U+1BCA3, U+1D173–U+1D17A, U+E0001, U+E0020–U+E007F), two
/// private-use planes (U+F0000 and U+100000 up) and every UNASSIGNED codepoint — all of which
/// `str.isprintable` is false for and none of which this escaped. `crate::shown` carried a
/// table for the neighbouring question with the first nine of those in it, so the two ports
/// in one crate already disagreed about U+0890.
///
/// Now it is [`crate::tui::tables::NONPRINTABLE`], generated by running
/// `str.isprintable` over every codepoint in the CPython the differential oracle runs
/// (`tools/gen-unicode-tables.py`). There is no approximation left to be wrong.
///
/// The cost is stated: `isprintable` is false for unassigned codepoints, so this table is the
/// one in the crate that goes stale in the DIRECTION of escaping too much — a codepoint
/// assigned after the generated Unicode version prints as itself in a newer CPython and comes
/// back as `\uNNNN` here, until the table is regenerated. That is a byte of difference in a
/// refusal, in a value nobody could have typed when the table was cut.
fn printable(c: char) -> bool {
    !crate::tui::in_table(c, &crate::tui::tables::NONPRINTABLE)
}

/// A float as `repr()` spells it, which is **not** how `json.dumps` spells it.
///
/// [`crate::pyjson::float_repr`] is the writer's rule, and the writer says `Infinity`, `-Infinity`
/// and `NaN` — the JSON spellings `allow_nan` emits. `repr(float("inf"))` is `inf`. The digits
/// are the same rule for every finite value, so only the three non-finite names are decided
/// here rather than a second copy of the shortest-round-trip logic.
fn float(value: f64) -> String {
    match crate::pyjson::float_repr(value).as_str() {
        "Infinity" => "inf".to_owned(),
        "-Infinity" => "-inf".to_owned(),
        "NaN" => "nan".to_owned(),
        finite => finite.to_owned(),
    }
}

/// `repr(value)` for a document `json.loads` produced — a string gains quotes, `true` is
/// `True`, `null` is `None`, and a container is Python's, not JSON's.
///
/// The one this crate keeps. `inventory` had a copy that handed a container to
/// `serde_json`'s own `to_string`, so a refusal naming a list quoted it back as `["a","b"]`
/// where Python writes `['a', 'b']`, and `charter-cli`'s `memory` had a second copy that got
/// that right — the same sentence, quoted two ways, depending on which command refused.
pub fn repr_json(value: &serde_json::Value) -> String {
    match value {
        serde_json::Value::String(s) => repr_str(s),
        serde_json::Value::Null => "None".to_owned(),
        serde_json::Value::Bool(true) => "True".to_owned(),
        serde_json::Value::Bool(false) => "False".to_owned(),
        serde_json::Value::Number(n) => number(n),
        serde_json::Value::Array(items) => format!(
            "[{}]",
            items.iter().map(repr_json).collect::<Vec<_>>().join(", ")
        ),
        serde_json::Value::Object(pairs) => format!(
            "{{{}}}",
            pairs
                .iter()
                .map(|(k, v)| format!("{}: {}", repr_str(k), repr_json(v)))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

/// `str(value)` for the same document. Identical to [`repr_json`] except at the top level,
/// where a string is itself and not a quoted one — which is the whole of the difference
/// Python has, because `str` of a container calls `repr` on its elements.
pub fn str_json(value: &serde_json::Value) -> String {
    match value {
        serde_json::Value::String(s) => s.clone(),
        other => repr_json(other),
    }
}

/// A JSON number as Python prints the value `json.loads` made of it.
///
/// [`crate::pyjson::number`] already decides int-or-float from the literal — which is the
/// part `arbitrary_precision` exists for, since an integer wider than `u64` must come back as
/// its own digits and not as the `f64` nearest it. Only the non-finite names differ between
/// the writer and `repr`, and [`float`] is where that is said once.
fn number(n: &serde_json::Number) -> String {
    match crate::pyjson::number(n).as_str() {
        "Infinity" => "inf".to_owned(),
        "-Infinity" => "-inf".to_owned(),
        "NaN" => "nan".to_owned(),
        finite => finite.to_owned(),
    }
}

/// `repr(value)` for a value `tomllib` produced.
///
/// **A `TOML` datetime is the one shape this does not reproduce, and it is declared rather
/// than quietly wrong.** `tomllib` hands back a `datetime.datetime`, whose `repr` is
/// `datetime.datetime(2026, 5, 4, 11, 32, 17)` — a constructor call, not a timestamp. What is
/// written here is the value as TOML spells it. It reaches a reader only where a refusal
/// quotes back a `schema =` or a `[section] default` somebody set to a date, which is a value
/// charter refuses either way and for the same stated reason; porting CPython's `datetime`
/// repr for it would be more code than the sentence is worth. Named here so the next person
/// to hit it finds a decision rather than a bug.
pub fn repr_toml(value: &toml::Value) -> String {
    match value {
        toml::Value::String(s) => repr_str(s),
        toml::Value::Integer(i) => i.to_string(),
        toml::Value::Float(f) => float(*f),
        toml::Value::Boolean(true) => "True".to_owned(),
        toml::Value::Boolean(false) => "False".to_owned(),
        toml::Value::Array(items) => format!(
            "[{}]",
            items.iter().map(repr_toml).collect::<Vec<_>>().join(", ")
        ),
        toml::Value::Table(pairs) => format!(
            "{{{}}}",
            pairs
                .iter()
                .map(|(k, v)| format!("{}: {}", repr_str(k), repr_toml(v)))
                .collect::<Vec<_>>()
                .join(", ")
        ),
        toml::Value::Datetime(d) => d.to_string(),
    }
}

/// `str(value)` for a `tomllib` value — [`repr_toml`] but for a bare string, as with JSON.
pub fn str_toml(value: &toml::Value) -> String {
    match value {
        toml::Value::String(s) => s.clone(),
        other => repr_toml(other),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_name_is_quoted_back_the_way_python_quotes_it() {
        // Each verified against CPython 3.14 `repr(...)`.
        assert_eq!(repr_str("widget"), "'widget'");
        assert_eq!(repr_str("../escape"), "'../escape'");
        assert_eq!(repr_str("it's"), "\"it's\"");
        assert_eq!(repr_str("both'\""), "'both\\'\"'");
        assert_eq!(repr_str("a\nb\tc\\d"), "'a\\nb\\tc\\\\d'");
        assert_eq!(repr_str("x\u{1b}[2J"), "'x\\x1b[2J'");
        assert_eq!(repr_str("zw\u{200b}j"), "'zw\\u200bj'");
        assert_eq!(repr_str("nb\u{a0}sp"), "'nb\\xa0sp'");
        assert_eq!(repr_str("line\u{2028}sep"), "'line\\u2028sep'");
        assert_eq!(repr_str("café"), "'café'");
    }

    /// The codepoints the hand-written `printable` called printable and CPython does not.
    ///
    /// Every one of these came back as ITSELF before the table was generated, and every one
    /// is a character `crate::shown` was already escaping — so before this the same value put
    /// through the crate's two answers came out two ways. Each expectation is CPython 3.14's
    /// `repr(...)`, and the test is the one that goes red if the table is dropped again.
    #[test]
    fn the_codepoints_the_hand_written_table_missed_are_escaped_as_python_escapes_them() {
        // A `Cf` range assigned after the old list was written: ARABIC POUND MARK ABOVE.
        assert_eq!(repr_str("fmt\u{890}x"), "'fmt\\u0890x'");
        // Private use — inside the one plane the old list had…
        assert_eq!(repr_str("priv\u{f8ff}z"), "'priv\\uf8ffz'");
        // …and in the two supplementary planes it did not.
        assert_eq!(repr_str("pua2\u{f0000}y"), "'pua2\\U000f0000y'");
        // Unassigned (`Cn`), which the old rule had no clause for at all.
        assert_eq!(repr_str("unassigned\u{378}q"), "'unassigned\\u0378q'");
        // A language tag character: `Cf`, astral, and the shape a spoofed name hides in.
        assert_eq!(repr_str("tag\u{e0041}"), "'tag\\U000e0041'");
    }

    /// The two ports in this crate answer one question, so they cannot disagree about a
    /// character the way `shown` and `pyrepr` did about U+0890.
    ///
    /// They are not the SAME set — `repr` escapes the private-use and unassigned codepoints
    /// that have a category `one_line` leaves alone — so this asserts the containment that
    /// actually matters: **everything `one_line` escapes, `repr` escapes too.** A glyph
    /// charter's containment rule calls line-forging can never be printed raw inside a
    /// refusal.
    #[test]
    fn nothing_one_line_escapes_is_printable_to_repr() {
        for &(lo, hi) in &crate::tui::tables::INVISIBLE {
            for cp in lo..=hi {
                let Some(c) = char::from_u32(cp) else {
                    continue;
                };
                assert!(
                    !printable(c),
                    "U+{cp:04X} is invisible and repr would print it"
                );
            }
        }
    }

    #[test]
    fn a_json_document_is_quoted_back_as_python_quotes_the_value_it_read() {
        // Verified against CPython 3.14: `repr(json.loads(...))` / `str(json.loads(...))`.
        let doc: serde_json::Value =
            serde_json::from_str(r#"{"a": [1, 2.5, true, null, "x"]}"#).unwrap();
        assert_eq!(repr_json(&doc), "{'a': [1, 2.5, True, None, 'x']}");
        assert_eq!(str_json(&doc), "{'a': [1, 2.5, True, None, 'x']}");

        let list: serde_json::Value =
            serde_json::from_str(r#"[1, 2.5, true, null, "it's"]"#).unwrap();
        assert_eq!(repr_json(&list), "[1, 2.5, True, None, \"it's\"]");

        // The one place `str` and `repr` part: a bare string.
        let plain = serde_json::Value::String("plain".to_owned());
        assert_eq!(repr_json(&plain), "'plain'");
        assert_eq!(str_json(&plain), "plain");
    }

    #[test]
    fn a_json_number_is_the_number_python_read_and_not_the_literal() {
        let n =
            |literal: &str| repr_json(&serde_json::from_str::<serde_json::Value>(literal).unwrap());
        // An integer wider than `u64` keeps its digits; `-0` is the int `0`.
        assert_eq!(n("18446744073709551616"), "18446744073709551616");
        assert_eq!(n("-0"), "0");
        // A literal with an exponent or a fraction is a float, printed as `repr` prints one.
        assert_eq!(n("1E5"), "100000.0");
        assert_eq!(n("1e-7"), "1e-07");
        assert_eq!(n("2.50"), "2.5");
        // And an overflow is `inf` — `repr`'s spelling, where `json.dumps` writes `Infinity`.
        assert_eq!(n("1e400"), "inf");
    }

    #[test]
    fn a_toml_value_is_quoted_back_as_python_quotes_what_tomllib_read() {
        // Verified against CPython 3.14 `repr(tomllib.loads(...)[k])`.
        let table: toml::Table = "a = 1\nb = 1.5\nc = true\nd = [\"x\", \"y\"]\n\
                                  e = { k = 1 }\nf = inf\ng = nan\nh = 1e300\ni = \"it's\"\n"
            .parse()
            .unwrap();
        let at = |k: &str| repr_toml(&table[k]);
        assert_eq!(at("a"), "1");
        assert_eq!(at("b"), "1.5");
        assert_eq!(at("c"), "True");
        assert_eq!(at("d"), "['x', 'y']");
        assert_eq!(at("e"), "{'k': 1}");
        assert_eq!(at("f"), "inf");
        assert_eq!(at("g"), "nan");
        assert_eq!(at("h"), "1e+300");
        assert_eq!(at("i"), "\"it's\"");
        assert_eq!(str_toml(&table["i"]), "it's");
    }
}
