//! The generated persona-roster block inside the plane's own README — who exists, and who
//! work is actually routed to. A port of `charter/render.py`'s `personas_md` and
//! `splice_personas`.
//!
//! **Every column comes from COMMITTED state** — the persona definitions, their memory
//! files, the dispatch log. Vault health is deliberately absent: vaults are gitignored and
//! per-engineer, so a column drawn from one would churn the README and conflict between
//! checkouts.
//!
//! **The plane's README is an operator's file.** charter owns the bytes between the two
//! markers and nothing else: [`splice`] replaces that span and returns `None` when either
//! marker is missing, so a hand-written README is never appended to by surprise. That is
//! the whole contract, and `docs generate` is tested against it.

use std::collections::BTreeMap;
use std::path::Path;

use crate::memstore;

/// The markers delimiting the generated block. `render.PERSONAS_BEGIN` / `PERSONAS_END`.
pub const BEGIN: &str =
    "<!-- BEGIN personas — GENERATED by `charter docs`; do not edit by hand. -->";
pub const END: &str = "<!-- END personas -->";

/// How wide the dispatch bar is drawn. `render._bar`'s `width`.
const BAR: u64 = 12;

/// One roster row, before it is sorted and rendered.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Row {
    pub name: String,
    /// Times this persona was dispatched as a sub-agent.
    pub dispatches: u64,
    /// How many memory files it holds.
    pub memories: usize,
    /// `tools:` from its frontmatter, stripped.
    pub tools: String,
    /// `activity:` from its frontmatter, stripped — the fallback when it declares no tools.
    pub activity: String,
}

/// A memory directory the roster could not list, with the errno.
///
/// `len(persona.memories(n))` raises rather than answering zero (charter #1084), and a
/// count charter did not take has no business being written into a committed file. The
/// caller names these and leaves the README alone.
pub type Unread = memstore::Unread;

/// The roster's rows, or the FIRST memory store that stopped them being taken.
///
/// Both halves of the answer, because the caller does two different things with them: the
/// rows render, and an unread store is named and the write abandoned.
///
/// It stops at the first such store rather than surveying every persona, because Python
/// does: `len(persona.memories(n))` raises out of the loop, so the sentence an operator
/// reads names one directory. A second one they cannot see yet is a second run away, and a
/// list of them is not what either charter prints.
pub fn rows(root: &Path, names: &[String], counts: &BTreeMap<String, u64>) -> (Vec<Row>, Unread) {
    let mut rows = Vec::new();
    let mut unread = Unread::new();
    for name in names {
        if !unread.is_empty() {
            break;
        }
        let meta: BTreeMap<String, String> = crate::personas::load(root, name)
            .unwrap_or_default()
            .into_iter()
            // `dict(pairs)`: a key written twice keeps the LAST value.
            .collect();
        let (files, could_not) = memstore::read_files(root, &memory_dir(root, name));
        unread.extend(could_not);
        rows.push(Row {
            name: name.clone(),
            dispatches: counts.get(name).copied().unwrap_or(0),
            memories: files.len(),
            tools: field(&meta, "tools"),
            activity: field(&meta, "activity"),
        });
    }
    // Most-dispatched first, ties by name — `rows.sort(key=lambda r: (-r["disp"], r["name"]))`.
    rows.sort_by(|a, b| b.dispatches.cmp(&a.dispatches).then(a.name.cmp(&b.name)));
    (rows, unread)
}

fn memory_dir(root: &Path, name: &str) -> std::path::PathBuf {
    root.join("personas").join(name).join("memory")
}

fn field(meta: &BTreeMap<String, String>, key: &str) -> String {
    memstore::py_strip(meta.get(key).map(String::as_str).unwrap_or_default()).to_string()
}

/// Python's `round()` — half to EVEN, not half away from zero.
///
/// The bar is the one arithmetic in this file, and the two rules disagree on exactly the
/// value a twelve-cell bar hits often: `round(6.5)` is 6 in Python and 7 in Rust. A README
/// is a committed file, so one cell of difference is a diff on every plane that regenerates
/// it with the other charter.
fn round_half_even(x: f64) -> u64 {
    let down = x.floor();
    let frac = x - down;
    let n = if frac > 0.5 {
        down + 1.0
    } else if frac < 0.5 {
        down
    } else if (down as i64) % 2 == 0 {
        down
    } else {
        down + 1.0
    };
    n.max(0.0) as u64
}

/// The unicode bar for one row. `render._bar`.
///
/// Rendered from committed counts so every engineer sees the same one. A non-zero count
/// always fills at least one cell — a persona that was dispatched once must not draw as a
/// persona that never was, which is the distinction the ⚑ below is about.
pub fn bar(n: u64, peak: u64) -> String {
    if peak == 0 {
        return "░".repeat(BAR as usize);
    }
    let filled = if n == 0 {
        0
    } else {
        round_half_even(BAR as f64 * n as f64 / peak as f64).max(1)
    };
    let filled = filled.min(BAR) as usize;
    format!(
        "{}{}",
        "█".repeat(filled),
        "░".repeat(BAR as usize - filled)
    )
}

/// The whole generated block, markers included. `render.personas_md`.
pub fn block(rows: &[Row], generic: u64, total: u64) -> String {
    let peak = rows.iter().map(|r| r.dispatches).max().unwrap_or(0);
    let mut out: Vec<String> = vec![
        BEGIN.to_string(),
        String::new(),
        "## Personas — roster & routing health".to_string(),
        String::new(),
    ];
    if total == 0 {
        out.push(
            "_No dispatches recorded yet._ The tally fills as sub-agents are dispatched; seed \
             it from past sessions with `charter persona dispatch-backfill`."
                .to_string(),
        );
        out.push(String::new());
    } else {
        // Integer division, as Python's `//` is: the headline never rounds a 49% share up.
        let pct = 100 * generic / total;
        out.push(format!(
            "**{} of {total} dispatches went to a persona**; {generic} went to a generic agent \
             (**{pct}%**). A rising generic share means work a persona owns is being done \
             without it.",
            total - generic
        ));
        out.push(String::new());
        out.push("```mermaid".to_string());
        out.push("pie showData".to_string());
        out.push(format!(
            "    \"dispatched to a persona\" : {}",
            total - generic
        ));
        out.push(format!("    \"dispatched to a generic agent\" : {generic}"));
        out.push("```".to_string());
        out.push(String::new());
    }
    out.push("| Persona | Dispatches | | Memory | Capability |".to_string());
    out.push("| --- | ---: | --- | ---: | --- |".to_string());
    let mut flagged = false;
    for r in rows {
        let cap = if !r.tools.is_empty() {
            format!("`{}`", r.tools)
        } else if !r.activity.is_empty() {
            format!("_{}_", r.activity)
        } else {
            "—".to_string()
        };
        // Only once there is a tally to be absent from: on a plane with no dispatches at
        // all, every persona would carry the mark and it would mean nothing.
        let flag = if r.dispatches == 0 && total > 0 {
            flagged = true;
            " ⚑"
        } else {
            ""
        };
        out.push(format!(
            "| `{}`{flag} | {} | `{}` | {} | {cap} |",
            r.name,
            r.dispatches,
            bar(r.dispatches, peak),
            r.memories
        ));
    }
    out.push(String::new());
    if flagged {
        out.push(
            "⚑ = **never dispatched**: the persona exists and lints green, but nothing has ever \
             been routed to it. A persona earns its place by carrying a capability a generic \
             sub-agent can't have — a credential/tool, or a domain narrow enough to name."
                .to_string(),
        );
        out.push(String::new());
    }
    out.push(
        "Regenerate with `make docs` (also refreshed once per session). Detail: `charter persona \
         stats` · `docs/personas.md`."
            .to_string(),
    );
    out.push(String::new());
    out.push(END.to_string());
    out.join("\n")
}

/// `readme` with the marked block replaced, or `None` when the markers are not both there
/// in that order. `render.splice_personas`.
///
/// The FIRST of each marker, as Python's `str.find` takes them, and the span between them
/// is the only thing that changes: everything before `BEGIN` and everything after `END` is
/// handed back byte for byte. A README that carries no block is left entirely alone —
/// appending one would be charter writing into a file it was not invited into.
pub fn splice(readme: &str, block: &str) -> Option<String> {
    let (i, j) = span(readme)?;
    Some(format!(
        "{}{block}{}",
        &readme[..i],
        &readme[j + END.len()..]
    ))
}

/// Whether `readme` carries a block at all — the question `splice` asks FIRST.
///
/// Separate because the order is behaviour: Python's `splice_personas` returns before it
/// calls `personas_md`, so a plane with no block never reads a persona, never counts a
/// memory, and cannot be stopped by a memory store it could not list.
pub fn has_block(readme: &str) -> bool {
    span(readme).is_some()
}

/// `(begin, end)` byte offsets of the block, or `None` — the FIRST of each marker, as
/// Python's `str.find` takes them.
fn span(readme: &str) -> Option<(usize, usize)> {
    let i = readme.find(BEGIN)?;
    let j = readme.find(END)?;
    (j >= i).then_some((i, j))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn row(name: &str, dispatches: u64) -> Row {
        Row {
            name: name.into(),
            dispatches,
            memories: 0,
            tools: String::new(),
            activity: String::new(),
        }
    }

    #[test]
    fn a_bar_is_filled_from_the_peak_and_rounds_the_way_python_rounds() {
        assert_eq!(bar(0, 0), "░░░░░░░░░░░░", "no dispatches anywhere");
        assert_eq!(bar(4, 4), "████████████");
        assert_eq!(bar(0, 4), "░░░░░░░░░░░░", "never dispatched draws empty");
        // One dispatch out of forty is 0.3 cells; it still draws one, because "dispatched
        // once" and "never dispatched" are the two states this column exists to separate.
        assert_eq!(bar(1, 40), "█░░░░░░░░░░░");
        // 12 * 13 / 24 = 6.5 — Python's `round` gives 6, Rust's `f64::round` gives 7.
        assert_eq!(bar(13, 24), "██████░░░░░░");
    }

    #[test]
    fn the_headline_counts_personas_against_generics_and_truncates_the_share() {
        let rows = [row("devops", 1), row("steward", 0)];
        let block = block(&rows, 1, 3);

        assert!(
            block.contains(
                "**2 of 3 dispatches went to a persona**; 1 went to a generic agent (**33%**)"
            ),
            "{block}"
        );
        assert!(block.contains("\"dispatched to a persona\" : 2"), "{block}");
        assert!(block.contains("| `steward` ⚑ | 0 |"), "{block}");
        assert!(block.contains("⚑ = **never dispatched**"), "{block}");
    }

    #[test]
    fn a_plane_that_has_dispatched_nothing_flags_nobody() {
        // Every persona is at zero, so the mark would be on every row and would say nothing
        // about any of them.
        let block = block(&[row("devops", 0), row("steward", 0)], 0, 0);

        assert!(block.contains("_No dispatches recorded yet._"), "{block}");
        assert!(!block.contains('⚑'), "{block}");
        assert!(!block.contains("```mermaid"), "{block}");
    }

    #[test]
    fn a_capability_is_the_tools_then_the_activity_then_a_dash() {
        let mut with_tools = row("a", 0);
        with_tools.tools = "Bash, Read".into();
        let mut with_activity = row("b", 0);
        with_activity.activity = "ships releases".into();
        let block = block(&[with_tools, with_activity, row("c", 0)], 0, 0);

        assert!(block.contains("| `Bash, Read` |"), "{block}");
        assert!(block.contains("| _ships releases_ |"), "{block}");
        assert!(block.contains("| — |"), "{block}");
    }

    #[test]
    fn only_the_span_between_the_markers_is_ever_rewritten() {
        let readme = format!("# My plane\n\nMine.\n\n{BEGIN}\nOLD\n{END}\n\n## Also mine\n");
        let spliced = splice(&readme, "NEW").expect("both markers, in order");

        assert_eq!(spliced, "# My plane\n\nMine.\n\nNEW\n\n## Also mine\n");
    }

    #[test]
    fn a_readme_without_the_block_is_left_exactly_as_it_is() {
        assert_eq!(splice("# My plane\n", "NEW"), None);
        assert_eq!(splice(&format!("{BEGIN}\n"), "NEW"), None, "no end marker");
        assert_eq!(splice(&format!("{END}\n"), "NEW"), None, "no begin marker");
        // End before begin is not a block either; splicing it would delete the file's middle.
        assert_eq!(splice(&format!("{END}\nx\n{BEGIN}\n"), "NEW"), None);
    }

    #[test]
    fn a_rows_count_comes_from_the_plane_and_a_store_it_cannot_list_is_named() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        std::fs::write(root.join("charter.toml"), "").unwrap();
        let mem = root.join("personas/devops/memory");
        std::fs::create_dir_all(&mem).unwrap();
        std::fs::write(mem.join("MEMORY.md"), "# index\n").unwrap();
        std::fs::write(mem.join("a-fact.md"), "# a fact\n").unwrap();
        std::fs::write(
            root.join("personas/devops/persona.md"),
            "---\nname: devops\ntools: Bash\n---\n\n# DevOps\n",
        )
        .unwrap();

        let mut counts = BTreeMap::new();
        counts.insert("devops".to_string(), 3);
        let (rows, unread) = rows(root, &["devops".to_string()], &counts);

        assert!(unread.is_empty());
        assert_eq!(rows[0].memories, 1, "the index is not a memory");
        assert_eq!(rows[0].dispatches, 3);
        assert_eq!(rows[0].tools, "Bash");
    }
}
