//! `charter change push` on GitLab (GL-3b): the same scenes as the GitHub ones above, with each
//! member's origin on GitLab, in a nested group, and each question spelt as GitLab's REST API
//! (v4) spells it. Recorded against the GitLab 19.4 documentation, `doc/api/merge_requests.md`:
//! "List project merge requests", "Create a merge request", "Get single MR" and "Update a
//! merge request". The bare remotes are local, and nothing reaches a network.

use super::*;

/// The group every GitLab member is in, a subgroup so the project path has two slashes.
const GROUP: &str = "acme/plat";

/// A self-managed GitLab, declared in `charter.toml`.
const SELF_MANAGED: &str =
    "schema = 1\n\n[[forge]]\nkind = \"gitlab\"\nhost = \"gitlab.acme.test\"\n";

/// `projects/<id>/merge_requests`, the project named by its URL-encoded path.
fn mrs(repo: &str) -> String {
    format!("projects/acme%2Fplat%2F{repo}/merge_requests")
}

fn web(host: &str, repo: &str, n: u64) -> String {
    format!("https://{host}/{GROUP}/{repo}/-/merge_requests/{n}")
}

/// `by_head`'s lookup, answered with `listing`.
fn from_the_branch(repo: &str, listing: Value) -> Value {
    get(
        &format!(
            "{}?source_branch=change%2Fapi-2&state=all&per_page=100",
            mrs(repo)
        ),
        listing,
    )
}

fn none_from_the_branch(repo: &str) -> Value {
    from_the_branch(repo, json!([]))
}

/// An MR record as GitLab lists it: from the project itself unless `source` says otherwise.
fn mr(host: &str, repo: &str, n: u64, state: &str, source: u64, extra: Value) -> Value {
    let mut record = json!({"iid": n, "id": 900 + n, "web_url": web(host, repo, n),
                            "state": state, "sha": SHA, "source_branch": BRANCH,
                            "source_project_id": source, "target_project_id": 3});
    for (k, v) in extra.as_object().unwrap() {
        record[k] = v.clone();
    }
    record
}

fn open_from_the_branch(repo: &str, n: u64) -> Value {
    from_the_branch(
        repo,
        json!([mr("gitlab.com", repo, n, "opened", 3, json!({}))]),
    )
}

/// The open-or-update of an MR that does not exist yet: the lookup, then the `POST`.
fn opened_on(host: &str, repo: &str, n: u64, body: &str) -> [Value; 2] {
    [
        get(
            &format!(
                "{}?state=opened&source_branch=change%2Fapi-2&target_branch=main&per_page=100",
                mrs(repo)
            ),
            json!([]),
        ),
        write(
            "POST",
            &mrs(repo),
            json!([{"text": ["source_branch", BRANCH]}, {"text": ["target_branch", "main"]},
                   {"text": ["title", format!("api-2: {repo}")]},
                   {"text": ["description", body]}]),
            json!({"iid": n, "id": 900 + n, "web_url": web(host, repo, n), "state": "opened"}),
        ),
    ]
}

fn opened(repo: &str, n: u64, body: &str) -> [Value; 2] {
    opened_on("gitlab.com", repo, n, body)
}

/// `body`: the MR's own record, its `description` as GitLab answers it.
fn description_is(repo: &str, n: u64, description: Value) -> Value {
    get(
        &format!("{}/{n}", mrs(repo)),
        json!({"iid": n, "description": description}),
    )
}

fn body_is(repo: &str, n: u64, body: &str) -> Value {
    description_is(repo, n, json!(body))
}

/// `set_body`: a `PUT` carrying the description and nothing else, so a draft's title, its
/// labels and its reviewers are never touched.
fn body_set(repo: &str, n: u64, body: &str) -> Value {
    write(
        "PUT",
        &format!("{}/{n}", mrs(repo)),
        json!([{"text": ["description", body]}]),
        json!({"iid": n}),
    )
}

/// The same once both MRs are open: a GitLab cross-project reference names the full path.
const BOTH: &str = "bump the api

<!-- BEGIN charter change — GENERATED by `charter change push`; do not edit by hand. -->
**Cross-repo change: `api-2`** — bump the api

| repo | request | needs |
|---|---|---|
| widget | acme/plat/widget!7 | — |
| gadget | acme/plat/gadget!9 | widget |
<!-- END charter change -->";

/// The block with only `widget`, before and after its MR is open.
const LONE_NEW: &str = "bump the api

<!-- BEGIN charter change — GENERATED by `charter change push`; do not edit by hand. -->
**Cross-repo change: `api-2`** — bump the api

| repo | request | needs |
|---|---|---|
| widget | — | — |
<!-- END charter change -->";

fn lone() -> String {
    LONE_NEW.replace("| widget | — |", "| widget | acme/plat/widget!7 |")
}

impl World {
    fn gitlab_clone(&self, repo: &str) -> PathBuf {
        self.clone_on("gitlab.com", GROUP, repo)
    }
}

fn first_push(world: &World) -> (u8, String, Arc<Recorded>) {
    let [w1, w2] = opened("widget", 7, NEW_BODY);
    let [g1, g2] = opened("gadget", 9, NEW_BODY);
    world.push(json!([
        none_from_the_branch("widget"),
        w1,
        w2,
        none_from_the_branch("gadget"),
        g1,
        g2,
        body_is("gadget", 9, NEW_BODY),
        body_set("gadget", 9, BOTH),
        body_is("widget", 7, NEW_BODY),
        body_set("widget", 7, BOTH),
    ]))
}

#[test]
fn every_members_branch_is_pushed_and_its_merge_request_opened_carrying_the_cross_link_block() {
    let world = World::new("schema = 1\n");
    let widget = world.gitlab_clone("widget");
    world.gitlab_clone("gadget");
    world.change(&[("widget", &[]), ("gadget", &["widget"])]);
    let (code, said, recorded) = first_push(&world);
    assert_eq!(code, 0, "{said}");
    assert_eq!(recorded.unspent(), Vec::new(), "{said}");
    let head = run(&widget, &["rev-parse", BRANCH]).trim().to_string();
    assert_eq!(world.remote_in_has(GROUP, "widget", BRANCH), Some(head));
    assert!(world.remote_in_has(GROUP, "gadget", BRANCH).is_some());
    assert!(
        said.contains(
            "widget  change/api-2 → https://gitlab.com/acme/plat/widget.git, its request into main"
        ),
        "{said}"
    );
    assert!(said.contains("opened → !7"), "{said}");
    assert!(said.contains("cross-link block written into 2"), "{said}");
}

#[test]
fn the_push_to_gitlab_is_one_refspec_to_the_projects_https_url_with_no_force() {
    let world = World::new("schema = 1\n");
    let widget = world.gitlab_clone("widget");
    world.change(&[("widget", &[])]);
    let before = crate::worktree::git::tally::asked(&widget).len();
    let [w1, w2] = opened("widget", 7, LONE_NEW);
    let (code, said, _) = world.push(json!([
        none_from_the_branch("widget"),
        w1,
        w2,
        body_is("widget", 7, LONE_NEW),
        body_set("widget", 7, &lone()),
    ]));
    assert_eq!(code, 0, "{said}");
    let asked = crate::worktree::git::tally::asked(&widget)[before..].to_vec();
    let refspec = format!("refs/heads/{BRANCH}:refs/heads/{BRANCH}");
    let push = asked
        .iter()
        .find(|argv| argv.iter().any(|a| a == "push"))
        .unwrap_or_else(|| panic!("no push in {asked:?}"));
    assert_eq!(
        push,
        &[
            "-c",
            "push.followTags=false",
            "-c",
            "push.pushOption=",
            "-c",
            "push.recurseSubmodules=no",
            "push",
            "https://gitlab.com/acme/plat/widget.git",
            refspec.as_str(),
        ]
        .map(String::from)
    );
}

#[test]
fn a_second_push_opens_no_second_merge_request_and_writes_no_description_that_is_current() {
    let world = World::new("schema = 1\n");
    world.gitlab_clone("widget");
    world.gitlab_clone("gadget");
    world.change(&[("widget", &[]), ("gadget", &["widget"])]);
    let (code, said, _) = first_push(&world);
    assert_eq!(code, 0, "{said}");
    // No POST and no PUT is recorded: either one fails the run as a request nobody wrote down.
    let (code, said, recorded) = world.push(json!([
        open_from_the_branch("widget", 7),
        open_from_the_branch("gadget", 9),
        body_is("gadget", 9, BOTH),
        body_is("widget", 7, BOTH),
    ]));
    assert_eq!(code, 0, "{said}");
    assert_eq!(recorded.unspent(), Vec::new(), "{said}");
    assert!(said.contains("already current in 2"), "{said}");
}

#[test]
fn when_membership_changes_the_block_in_a_merge_request_is_replaced_in_place() {
    let world = World::new("schema = 1\n");
    world.gitlab_clone("widget");
    world.change(&[("widget", &[])]);
    let theirs = format!("Reviewed by Ann.\n\n{BOTH}\n\nShip after Friday.");
    let ours = format!("Reviewed by Ann.\n\n{}\n\nShip after Friday.", lone());
    let (code, said, recorded) = world.push(json!([
        open_from_the_branch("widget", 7),
        body_is("widget", 7, &theirs),
        body_set("widget", 7, &ours),
    ]));
    assert_eq!(code, 0, "{said}");
    assert_eq!(recorded.unspent(), Vec::new(), "{said}");
}

#[test]
fn a_draft_merge_request_is_adopted_and_only_its_description_is_written() {
    // GitLab keeps a draft in its title (`Draft: `) and its `draft` flag. Charter writes the
    // description alone, so the MR stays a draft and keeps the title its author gave it.
    let world = World::new("schema = 1\n");
    world.gitlab_clone("widget");
    world.change(&[("widget", &[])]);
    let draft = mr(
        "gitlab.com",
        "widget",
        7,
        "opened",
        3,
        json!({"draft": true, "work_in_progress": true, "title": "Draft: widget api"}),
    );
    let (code, said, recorded) = world.push(json!([
        from_the_branch("widget", json!([draft])),
        body_is("widget", 7, LONE_NEW),
        body_set("widget", 7, &lone()),
    ]));
    assert_eq!(code, 0, "{said}");
    assert_eq!(recorded.unspent(), Vec::new(), "{said}");
    assert!(said.contains("pushed → !7"), "{said}");
}

#[test]
fn a_merge_request_from_a_fork_with_the_same_branch_name_is_never_adopted() {
    // GitLab matches `source_branch` by name in forks too. A stranger's MR from their fork's
    // `change/api-2` is not this member's: charter opens the member's own, and writes nothing
    // into the stranger's.
    let world = World::new("schema = 1\n");
    world.gitlab_clone("widget");
    world.change(&[("widget", &[])]);
    let fork = mr("gitlab.com", "widget", 5, "opened", 41, json!({}));
    let [w1, w2] = opened("widget", 7, LONE_NEW);
    let (code, said, recorded) = world.push(json!([
        from_the_branch("widget", json!([fork])),
        w1,
        w2,
        body_is("widget", 7, LONE_NEW),
        body_set("widget", 7, &lone()),
    ]));
    assert_eq!(code, 0, "{said}");
    assert_eq!(recorded.unspent(), Vec::new(), "{said}");
    assert!(!said.contains("!5"), "{said}");
}

#[test]
fn a_merged_merge_request_is_adopted_and_said_as_merged() {
    let world = World::new("schema = 1\n");
    world.gitlab_clone("widget");
    world.change(&[("widget", &[])]);
    let merged = mr(
        "gitlab.com",
        "widget",
        7,
        "merged",
        3,
        json!({"merge_commit_sha": "e5bd3914e2e596debea16f433f57875b5b90bcd6"}),
    );
    let (code, said, recorded) = world.push(json!([
        from_the_branch("widget", json!([merged])),
        body_is("widget", 7, LONE_NEW),
        body_set("widget", 7, &lone()),
    ]));
    assert_eq!(code, 0, "{said}");
    assert_eq!(recorded.unspent(), Vec::new(), "{said}");
    assert!(said.contains("pushed → !7 (merged as e5bd391"), "{said}");
}

#[test]
fn a_merge_request_with_no_description_is_left_alone_and_named() {
    // GitLab answers `"description": null` for an MR opened with none: there is no block in it
    // for charter to write into.
    let world = World::new("schema = 1\n");
    world.gitlab_clone("widget");
    world.change(&[("widget", &[])]);
    let (code, said, recorded) = world.push(json!([
        open_from_the_branch("widget", 7),
        description_is("widget", 7, Value::Null),
    ]));
    assert_eq!(code, 1, "{said}");
    assert_eq!(recorded.unspent(), Vec::new(), "{said}");
    assert!(
        said.contains("!7's description has no single charter block"),
        "{said}"
    );
}

#[test]
fn a_self_managed_gitlab_is_pushed_to_and_asked_at_its_own_host() {
    let world = World::new(SELF_MANAGED);
    let widget = world.clone_on("gitlab.acme.test", GROUP, "widget");
    world.change(&[("widget", &[])]);
    let [w1, w2] = opened_on("gitlab.acme.test", "widget", 7, LONE_NEW);
    let (code, said, recorded) = world.push(json!([
        none_from_the_branch("widget"),
        w1,
        w2,
        body_is("widget", 7, LONE_NEW),
        body_set("widget", 7, &lone()),
    ]));
    assert_eq!(code, 0, "{said}");
    assert_eq!(recorded.unspent(), Vec::new(), "{said}");
    assert!(
        said.contains("widget  change/api-2 → https://gitlab.acme.test/acme/plat/widget.git"),
        "{said}"
    );
    let head = run(&widget, &["rev-parse", BRANCH]).trim().to_string();
    assert_eq!(world.remote_in_has(GROUP, "widget", BRANCH), Some(head));
}

#[test]
fn a_member_on_another_host_is_linked_by_its_requests_url_not_by_a_reference() {
    // `acme/widget#7` in a GitLab description is GitLab's own issue 7 of a GitLab project
    // `acme/widget`, and `acme/plat/gadget!9` in a GitHub description is no link at all. A
    // reference only means the member's request on the description's own host, so a member
    // elsewhere is named by the URL its forge gave.
    let world = World::new(SELF_MANAGED);
    world.clone("widget");
    world.clone_on("gitlab.acme.test", GROUP, "gadget");
    world.change(&[("widget", &[]), ("gadget", &["widget"])]);
    let github_new = NEW_BODY;
    let [w1, w2] = super::opened("widget", 7, github_new);
    let [g1, g2] = opened_on("gitlab.acme.test", "gadget", 9, github_new);
    let in_github = "bump the api

<!-- BEGIN charter change — GENERATED by `charter change push`; do not edit by hand. -->
**Cross-repo change: `api-2`** — bump the api

| repo | request | needs |
|---|---|---|
| widget | acme/widget#7 | — |
| gadget | https://gitlab.acme.test/acme/plat/gadget/-/merge_requests/9 | widget |
<!-- END charter change -->";
    let in_gitlab = "bump the api

<!-- BEGIN charter change — GENERATED by `charter change push`; do not edit by hand. -->
**Cross-repo change: `api-2`** — bump the api

| repo | request | needs |
|---|---|---|
| widget | https://github.com/acme/widget/pull/7 | — |
| gadget | acme/plat/gadget!9 | widget |
<!-- END charter change -->";
    let (code, said, recorded) = world.push(json!([
        super::none_from_the_branch("widget"),
        w1,
        w2,
        none_from_the_branch("gadget"),
        g1,
        g2,
        body_is("gadget", 9, github_new),
        body_set("gadget", 9, in_gitlab),
        super::body_is("widget", 7, github_new),
        super::body_set("widget", 7, in_github),
    ]));
    assert_eq!(code, 0, "{said}");
    assert_eq!(recorded.unspent(), Vec::new(), "{said}");
}
