//! Compiles `docs/` into the binary.
//!
//! The documentation pages follow one rule: *the page a user reads should come from the same
//! install as the behaviour, so `charter docs show secrets` cannot describe a vault the running
//! CLI does not have.* An app installed from a signed bundle has no checkout to fall back to, so
//! the pages are `include_str!`ed and there is no second source to drift from. They are this
//! app's own, written here (M2.21, ADR 0044).
//!
//! **The file list is read from the directory rather than written down.** A checked-in list of
//! `include_str!` lines would be a second statement of what is in `docs/`, free to disagree with
//! the directory the day somebody adds a page.
//!
//! The order is the topic's, sorted: `docsrc.topics()` is `sorted(...)` of the stems, and a stem
//! differs from its filename only by a suffix every page shares.
//!
//! `templates/` is compiled in the same way and for the same reason: a project template is data
//! (FR-17), and the template a first run lays out has to be the one this install ships. Its
//! files are nested, so they are walked rather than listed.
//!
//! (`news/`, the Python charter's frozen news corpus, was compiled in here too until `charter
//! news` became the app's own CHANGELOG.md, #352.)

use std::fmt::Write as _;
use std::path::Path;

fn main() {
    // `charter news` compiles the repository's CHANGELOG.md in with `include_str!`, which
    // cargo already tracks; nothing to generate for it.
    compile(
        "docs",
        "docs_pages.rs",
        "PAGES",
        "Every documentation page, as `(topic, text)`, in topic order.",
        // The TOPIC, which is `Path.stem`: `charter docs show secrets`, never `secrets.md`.
        // `strip_suffix` and not `trim_end_matches`, which takes the suffix off REPEATEDLY
        // and would key `a.md.md` as `a` where Python keys it `a.md`.
        |name| name.strip_suffix(".md").unwrap_or(name).to_string(),
    );
    compile_tree(
        "templates",
        "template_files.rs",
        "FILES",
        "Every project template's files, as `(<template>/<path>, text)`, sorted by path.",
    );
    println!("cargo:rustc-env=PURLIS_BUILD_PROFILE={}", profile());
}

/// The Cargo profile this build is made with, by the name Cargo files it under: `release`,
/// `dev-release`, and `debug` for `dev` and `test` (ADR 0092, #1429).
///
/// Cargo hands a build script `PROFILE`, but that is only ever `debug` or `release`: a custom
/// profile reports the one it inherits from, so a `dev-release` build would call itself
/// `release`, which is the one thing the version line exists to tell apart. The directory is
/// the name. `OUT_DIR` is `<target>[/<triple>]/<profile>/build/<crate>-<hash>/out`, and when
/// it is not that shape the answer falls back to `PROFILE` rather than to a guess.
fn profile() -> String {
    let out = std::env::var("OUT_DIR").expect("cargo sets OUT_DIR");
    let mut above = Path::new(&out).ancestors().skip(2);
    let build = above.next().and_then(Path::file_name);
    let named = above.next().and_then(Path::file_name);
    match (
        build.and_then(|b| b.to_str()),
        named.and_then(|n| n.to_str()),
    ) {
        (Some("build"), Some(name)) if !name.is_empty() => name.to_owned(),
        _ => std::env::var("PROFILE").expect("cargo sets PROFILE"),
    }
}

/// Every file under `<crate>/<dir>`, at any depth, as a `&[(&str, &str)]` named `konst` keyed
/// by its path below `dir` with `/` between segments, written to `OUT_DIR`.
fn compile_tree(dir: &str, out: &str, konst: &str, doc: &str) {
    fn walk(at: &Path, under: &str, found: &mut Vec<(String, std::path::PathBuf)>) {
        println!("cargo:rerun-if-changed={}", at.display());
        let entries =
            std::fs::read_dir(at).unwrap_or_else(|e| panic!("cannot read {}: {e}", at.display()));
        for entry in entries {
            let entry =
                entry.unwrap_or_else(|e| panic!("cannot read an entry of {}: {e}", at.display()));
            let name = entry.file_name().to_string_lossy().into_owned();
            let key = if under.is_empty() {
                name
            } else {
                format!("{under}/{name}")
            };
            let path = entry.path();
            if path.is_dir() {
                walk(&path, &key, found);
            } else {
                found.push((key, path));
            }
        }
    }
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join(dir);
    let mut found = Vec::new();
    walk(&root, "", &mut found);
    found.sort();
    assert!(!found.is_empty(), "{} holds no files", root.display());

    let mut text =
        format!("/// {doc} Generated by `build.rs`.\npub static {konst}: &[(&str, &str)] = &[\n");
    for (key, path) in &found {
        println!("cargo:rerun-if-changed={}", path.display());
        writeln!(
            text,
            "    ({key:?}, include_str!({:?})),",
            path.to_string_lossy()
        )
        .expect("writing to a String cannot fail");
    }
    text.push_str("];\n");
    let target = Path::new(&std::env::var("OUT_DIR").expect("cargo sets OUT_DIR")).join(out);
    std::fs::write(&target, text)
        .unwrap_or_else(|e| panic!("cannot write {}: {e}", target.display()));
}

/// Every `*.md` in `<crate>/<dir>` as a `&[(&str, &str)]` named `konst`, written to `OUT_DIR`.
///
/// `key` is what each entry is looked up by: the topic, for docs.
fn compile(dir: &str, out: &str, konst: &str, doc: &str, key: impl Fn(&str) -> String) {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join(dir);
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut names: Vec<String> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()))
        .map(|entry| {
            entry
                .unwrap_or_else(|e| panic!("cannot read an entry of {}: {e}", dir.display()))
                .file_name()
                .to_string_lossy()
                .into_owned()
        })
        .filter(|name| name.ends_with(".md"))
        .collect();
    names.sort();
    assert!(!names.is_empty(), "{} holds no entries", dir.display());

    let mut text =
        format!("/// {doc} Generated by `build.rs`.\npub static {konst}: &[(&str, &str)] = &[\n");
    for name in &names {
        let path = dir.join(name);
        println!("cargo:rerun-if-changed={}", path.display());
        // Rust string escapes for a path and a key. Real names are `[0-9a-z.-]` and the
        // directory is the crate's own, but a generator that assumes its input is quote-free
        // is a generator that emits code that will not compile the day it is not.
        writeln!(
            text,
            "    ({:?}, include_str!({:?})),",
            key(name),
            path.to_string_lossy()
        )
        .expect("writing to a String cannot fail");
    }
    text.push_str("];\n");

    let target = Path::new(&std::env::var("OUT_DIR").expect("cargo sets OUT_DIR")).join(out);
    std::fs::write(&target, text)
        .unwrap_or_else(|e| panic!("cannot write {}: {e}", target.display()));
}
