//! ADR 0085: a chat that starts in its own worktree gets a git-excluded, redacted `AGENTS.md`
//! where the repository has none. Never in a shared clone, never over somebody else's file,
//! and never at the cost of the chat starting. V35: every `AGENTS.md` that charter's exclude
//! line hides and charter did not write is named, by `charter doctor` and by each chat's
//! briefing.

mod support;

use std::path::{Path, PathBuf};

use charter_core::{briefing, doctor, files, guest, start, worktree};

/// A plane whose default persona is `ops`, with a second persona `qa`, and one clone.
fn plane() -> support::Fixture {
    let f = support::plane_with_clone("svc");
    std::fs::write(
        f.plane.join("charter.toml"),
        "schema = 1\n\n[persona]\ndefault = \"ops\"\n",
    )
    .unwrap();
    for (name, role) in [("ops", "Ops Engineer"), ("qa", "QA")] {
        let dir = f.plane.join("personas").join(name);
        std::fs::create_dir_all(dir.join("memory")).unwrap();
        std::fs::write(
            dir.join("persona.md"),
            format!("---\nname: {name}\nrole: {role}\ndelegate-when: {name} work\n---\n"),
        )
        .unwrap();
        // A memory whose title must never reach a repository.
        std::fs::write(
            dir.join("memory/secret.md"),
            "# The staging password rotates Fridays\n",
        )
        .unwrap();
        std::fs::write(
            dir.join("memory/MEMORY.md"),
            format!("# {name}\n\n- [The staging password rotates Fridays](secret.md)\n"),
        )
        .unwrap();
    }
    f
}

fn cut(f: &support::Fixture, piece: &str) -> PathBuf {
    worktree::add(&f.plane, &f.ws, &f.repo, piece, None)
        .expect("a piece is cut")
        .path
}

fn read(path: &Path) -> String {
    std::fs::read_to_string(path).unwrap_or_default()
}

#[test]
fn a_chat_starting_in_its_own_piece_is_given_an_agents_md_hidden_from_git() {
    charter_core::unsteered!();
    let f = plane();
    let piece = cut(&f, "p1");

    start::layered_or_refusal(&piece, &f.plane, Some("ops")).expect("the chat starts");

    let file = read(&piece.join("AGENTS.md"));
    assert!(file.starts_with("<!-- GENERATED by charter"), "{file}");
    assert!(file.contains("You are the `ops` persona"), "{file}");
    assert!(file.contains("> role: Ops Engineer"), "{file}");
    assert!(
        file.contains("You hold piece **p1** of `svc` (workspace `alpha`)"),
        "{file}"
    );
    assert!(!file.contains("staging password"), "no memory: {file}");
    assert!(
        !file.contains(&f.plane.display().to_string()),
        "no path on this machine: {file}"
    );
    assert_eq!(
        f.status(&piece),
        "",
        "nothing charter wrote shows in git status"
    );
    assert!(
        guest::marker_at(&piece).contains_key("AGENTS.md"),
        "it is charter's, by its record"
    );
}

#[test]
fn a_chat_starting_in_the_shared_clone_is_given_no_agents_md() {
    charter_core::unsteered!();
    let f = plane();

    start::layered_or_refusal(&f.clone, &f.plane, Some("ops")).expect("the chat starts");

    assert!(!f.clone.join("AGENTS.md").exists());
    assert_eq!(f.status(&f.clone), "");
}

#[test]
fn the_next_chat_in_the_piece_gets_its_own_persona() {
    charter_core::unsteered!();
    let f = plane();
    let piece = cut(&f, "p1");

    start::layered_or_refusal(&piece, &f.plane, Some("ops")).unwrap();
    start::layered_or_refusal(&piece, &f.plane, Some("qa")).unwrap();

    let file = read(&piece.join("AGENTS.md"));
    assert!(file.contains("You are the `qa` persona"), "{file}");
    assert!(!file.contains("`ops` persona"), "{file}");
    assert_eq!(f.status(&piece), "");
}

#[test]
fn a_repository_that_tracks_its_own_agents_md_keeps_it_and_the_chat_still_starts() {
    charter_core::unsteered!();
    let f = plane();
    std::fs::write(f.clone.join("AGENTS.md"), "# the repo's own\n").unwrap();
    support::git(&f.clone, &["add", "AGENTS.md"]);
    support::git(&f.clone, &["commit", "-q", "-m", "agents"]);
    let piece = cut(&f, "p1");

    start::layered_or_refusal(&piece, &f.plane, Some("ops")).expect("the chat starts");

    assert_eq!(read(&piece.join("AGENTS.md")), "# the repo's own\n");
    assert!(!guest::marker_at(&piece).contains_key("AGENTS.md"));
    assert_eq!(f.status(&piece), "");
    // Even a tracked file holding exactly charter's words is the repository's.
    assert_eq!(
        guest::wire_for_chat(&f.plane, &piece, Some("# the repo's own\n")).1,
        Some(guest::Guidance::Tracked)
    );
}

#[test]
fn an_agents_md_charter_did_not_write_is_left_as_it_is_and_the_chat_still_starts() {
    charter_core::unsteered!();
    let f = plane();
    let piece = cut(&f, "p1");
    std::fs::write(piece.join("AGENTS.md"), "# mine\n").unwrap();

    start::layered_or_refusal(&piece, &f.plane, Some("ops")).expect("the chat starts");

    assert_eq!(read(&piece.join("AGENTS.md")), "# mine\n");
    assert_eq!(
        guest::wire_for_chat(&f.plane, &piece, Some("x\n")).1,
        Some(guest::Guidance::Theirs)
    );
    assert!(
        f.status(&piece).contains("?? AGENTS.md"),
        "and it is not hidden from its owner"
    );
}

#[test]
fn it_is_withheld_where_its_line_would_hide_an_operators_file_in_the_clone() {
    charter_core::unsteered!();
    // charter#1072: the line `/AGENTS.md` in the common exclude would hide the clone's too.
    let f = plane();
    std::fs::write(f.clone.join("AGENTS.md"), "# the operator's draft\n").unwrap();
    let piece = cut(&f, "p1");

    start::layered_or_refusal(&piece, &f.plane, Some("ops")).expect("the chat starts");

    assert!(
        !piece.join("AGENTS.md").exists(),
        "withheld, not left showing"
    );
    assert!(matches!(
        guest::wire_for_chat(&f.plane, &piece, Some("x\n")).1,
        Some(guest::Guidance::Withheld(_))
    ));
    assert!(
        f.status(&f.clone).contains("?? AGENTS.md"),
        "theirs still shows"
    );
}

#[cfg(unix)]
#[test]
fn it_is_withheld_where_the_exclude_cannot_be_written_and_the_chat_still_starts() {
    charter_core::unsteered!();
    use std::os::unix::fs::PermissionsExt;
    // A plane with no other layer, so nothing but this file wants the exclude: a guard would
    // refuse here, and guidance must not.
    let f = plane();
    let piece = cut(&f, "p1");
    let info = f.clone.join(".git/info");
    std::fs::create_dir_all(&info).unwrap();
    std::fs::set_permissions(&info, std::fs::Permissions::from_mode(0o500)).unwrap();

    let started = start::layered_or_refusal(&piece, &f.plane, Some("ops"));
    std::fs::set_permissions(&info, std::fs::Permissions::from_mode(0o755)).unwrap();

    started.expect("the chat starts");
    assert!(!piece.join("AGENTS.md").exists());
    assert_eq!(f.status(&piece), "");
}

#[test]
fn a_merge_that_brings_the_repositorys_own_takes_the_path_back_and_charter_steps_aside() {
    charter_core::unsteered!();
    let f = plane();
    let piece = cut(&f, "p1");
    start::layered_or_refusal(&piece, &f.plane, Some("ops")).unwrap();
    support::git(&f.clone, &["switch", "-q", "-c", "docs"]);
    std::fs::write(f.clone.join("AGENTS.md"), "# the repo's own\n").unwrap();
    // `-f`: charter's line hides it here too, which is what V35's report is for.
    support::git(&f.clone, &["add", "-f", "AGENTS.md"]);
    support::git(&f.clone, &["commit", "-q", "-m", "agents"]);
    support::git(&piece, &["merge", "-q", "docs"]);

    start::layered_or_refusal(&piece, &f.plane, Some("qa")).expect("the chat starts");

    assert_eq!(read(&piece.join("AGENTS.md")), "# the repo's own\n");
    assert_eq!(f.status(&piece), "");
}

// ---- V35: an AGENTS.md charter's line hides is named ------------------------------------

/// A piece holding charter's own `AGENTS.md`, and an `AGENTS.md` the operator then made in
/// the clone, which charter's line in the common exclude hides.
fn hidden_in_the_clone() -> (support::Fixture, PathBuf) {
    let f = plane();
    let piece = cut(&f, "p1");
    start::layered_or_refusal(&piece, &f.plane, Some("ops")).unwrap();
    std::fs::write(f.clone.join("AGENTS.md"), "# the operator's, made later\n").unwrap();
    assert_eq!(f.status(&f.clone), "", "the precondition: git hides it");
    (f, piece)
}

#[test]
fn an_agents_md_charters_line_hides_is_named_and_charters_own_is_not() {
    charter_core::unsteered!();
    let (f, piece) = hidden_in_the_clone();

    assert_eq!(
        guest::hidden_agents_md(&piece).found,
        vec![f.clone.join("AGENTS.md")]
    );
    assert_eq!(
        guest::hidden_agents_md(&f.clone).found,
        vec![f.clone.join("AGENTS.md")]
    );
}

#[test]
fn nothing_is_named_where_charters_line_hides_nothing_of_anyones() {
    charter_core::unsteered!();
    let f = plane();
    let piece = cut(&f, "p1");
    start::layered_or_refusal(&piece, &f.plane, Some("ops")).unwrap();

    assert!(guest::hidden_agents_md(&piece).is_empty());
    assert!(guest::hidden_agents_md(&f.clone).is_empty());
}

#[test]
fn charter_doctor_names_an_agents_md_its_line_hides() {
    charter_core::unsteered!();
    let (f, _piece) = hidden_in_the_clone();

    let rows = doctor::Doctor::at(&f.plane, &f.plane, false, false).run();

    let row = rows
        .iter()
        .find(|r| r.name == "hidden AGENTS.md")
        .expect("a row for it");
    assert_eq!(row.status, doctor::Status::Warn);
    assert!(row.detail.contains("alpha/svc/AGENTS.md"), "{}", row.detail);
}

#[test]
fn charter_doctor_has_no_such_row_when_nothing_is_hidden() {
    charter_core::unsteered!();
    let f = plane();
    let piece = cut(&f, "p1");
    start::layered_or_refusal(&piece, &f.plane, Some("ops")).unwrap();

    let rows = doctor::Doctor::at(&f.plane, &f.plane, false, false).run();

    assert!(!rows.iter().any(|r| r.name == "hidden AGENTS.md"));
}

#[test]
fn a_chat_starting_beside_it_is_told_to_name_it_to_the_operator() {
    charter_core::unsteered!();
    let (f, _piece) = hidden_in_the_clone();
    let lookup = |name: &str| (name == "CHARTER_WORKSPACE").then(|| "alpha".to_owned());
    let payload = serde_json::json!({"cwd": f.clone.display().to_string()});

    let told = briefing::parts(
        &briefing::Ask {
            root: &f.plane,
            cwd: &f.clone,
            payload: &payload,
            env: &lookup,
            now: chrono::Utc::now(),
        },
        None,
    )
    .join("\n\n");

    assert!(
        told.contains(&f.clone.join("AGENTS.md").display().to_string()),
        "{told}"
    );
    assert!(told.contains("Tell the operator"), "{told}");
}

// ---- review of #819 -----------------------------------------------------------------------

/// The `info/exclude` every checkout of the fixture's repository reads.
fn exclude(f: &support::Fixture) -> String {
    read(&f.clone.join(".git/info/exclude"))
}

#[test]
fn a_start_that_is_refused_writes_no_agents_md() {
    charter_core::unsteered!();
    let f = plane();
    f.give_the_plane_a_layer();
    let piece = cut(&f, "p1");
    // Somebody else's settings where the layer wants charter's: the guard refuses the chat.
    std::fs::write(piece.join(".claude/settings.json"), "{\"mine\": true}\n").unwrap();

    start::layered_or_refusal(&piece, &f.plane, Some("ops")).expect_err("no chat starts");

    assert!(!piece.join("AGENTS.md").exists());
    assert!(!exclude(&f).contains("/AGENTS.md"), "{}", exclude(&f));
}

#[cfg(unix)]
#[test]
fn a_record_that_cannot_be_published_leaves_no_line_behind_and_says_why() {
    charter_core::unsteered!();
    use std::os::unix::fs::PermissionsExt;
    let f = plane();
    let piece = cut(&f, "p1");
    std::fs::set_permissions(&piece, std::fs::Permissions::from_mode(0o555)).unwrap();

    let started = start::layered_or_refusal(&piece, &f.plane, Some("ops"));
    std::fs::set_permissions(&piece, std::fs::Permissions::from_mode(0o755)).unwrap();

    let notices = started.expect("the chat starts");
    assert!(!piece.join("AGENTS.md").exists());
    assert!(!exclude(&f).contains("/AGENTS.md"), "{}", exclude(&f));
    assert!(
        notices
            .iter()
            .any(|n| n.contains("AGENTS.md") && n.contains("EACCES")),
        "the reason reaches the operator: {notices:?}"
    );
}

#[test]
fn a_withheld_agents_md_says_why_at_the_start() {
    charter_core::unsteered!();
    let f = plane();
    std::fs::write(f.clone.join("AGENTS.md"), "# the operator's draft\n").unwrap();
    let piece = cut(&f, "p1");

    let notices = start::layered_or_refusal(&piece, &f.plane, Some("ops")).unwrap();

    assert!(
        notices
            .iter()
            .any(|n| n.contains(&f.clone.join("AGENTS.md").display().to_string())),
        "{notices:?}"
    );
}

#[test]
fn wire_for_chat_writes_nothing_into_a_tree_that_is_not_a_piece() {
    charter_core::unsteered!();
    let f = plane();

    let (_, guided) = guest::wire_for_chat(&f.plane, &f.clone, Some("x\n"));

    assert_eq!(guided, None);
    assert!(!f.clone.join("AGENTS.md").exists());
}

#[test]
fn two_chats_starting_in_one_piece_at_once_leave_charters_own_file() {
    charter_core::unsteered!();
    let f = plane();
    let piece = cut(&f, "p1");
    for round in 0..12 {
        let barrier = std::sync::Barrier::new(2);
        std::thread::scope(|s| {
            for who in ["ops", "qa"] {
                let (plane, piece, barrier) = (&f.plane, &piece, &barrier);
                s.spawn(move || {
                    barrier.wait();
                    start::layered_or_refusal(piece, plane, Some(who)).unwrap();
                });
            }
        });
        // Whichever won, the file is charter's by its record, and the next start can still
        // rewrite it.
        let again = start::layered_or_refusal(&piece, &f.plane, Some("ops")).unwrap();
        assert!(
            read(&piece.join("AGENTS.md")).contains("`ops` persona"),
            "round {round}: {again:?}"
        );
    }
}

/// Where a chat in the clone starts: the plane's own profile, so `start::ready` itself runs.
fn with_a_profile(f: &support::Fixture) {
    let program = stand_in::program(&f.plane, "claude-stand-in", "#!/bin/sh\nexit 0\n");
    std::fs::write(
        f.plane.join(charter_core::profiles::LOCAL_FILE),
        format!(
            "[harness.work]\nkind = \"claude\"\ncommand = [{:?}]\n",
            program.display().to_string()
        ),
    )
    .unwrap();
    let set = charter_core::profiles::current(&f.plane);
    let p = set.get("work").expect("the profile is declared");
    charter_core::profiletrust::record_launched(
        &f.plane,
        "work",
        &charter_core::profiletrust::fingerprint(p),
    )
    .unwrap();
}

#[test]
fn every_chat_start_hands_the_window_a_notice_naming_a_hidden_agents_md() {
    charter_core::unsteered!();
    let (f, piece) = hidden_in_the_clone();
    with_a_profile(&f);
    let starting = |cwd: &Path| start::Start {
        profile: Some("work".into()),
        persona: Some("ops".into()),
        name: "1".into(),
        cwd: Some(cwd.to_path_buf()),
        ..Default::default()
    };

    for cwd in [&f.clone, &piece] {
        let ready = start::ready(&starting(cwd), &f.plane).expect("it starts");
        assert!(
            ready
                .notices
                .iter()
                .any(|n| n.contains(&f.clone.join("AGENTS.md").display().to_string())),
            "{cwd:?}: {:?}",
            ready.notices
        );
    }
}

#[test]
fn a_chat_start_with_nothing_hidden_has_no_notice() {
    charter_core::unsteered!();
    let f = plane();
    let piece = cut(&f, "p1");
    with_a_profile(&f);
    let ready = start::ready(
        &start::Start {
            profile: Some("work".into()),
            persona: Some("ops".into()),
            name: "1".into(),
            cwd: Some(piece.clone()),
            ..Default::default()
        },
        &f.plane,
    )
    .expect("it starts");

    assert_eq!(ready.notices, Vec::<String>::new());
    assert!(piece.join("AGENTS.md").exists());
}

// ---- V35 never misses a file silently -----------------------------------------------------

#[cfg(unix)]
fn mode(path: &Path, bits: u32) {
    use std::os::unix::fs::PermissionsExt;
    std::fs::set_permissions(path, std::fs::Permissions::from_mode(bits)).unwrap();
}

#[cfg(unix)]
#[test]
fn a_worktree_list_charter_cannot_read_is_a_doubt_not_a_clean_answer() {
    charter_core::unsteered!();
    let f = plane();
    let piece = cut(&f, "p1");
    start::layered_or_refusal(&piece, &f.plane, Some("ops")).unwrap();
    let admin = f.clone.join(".git/worktrees");
    mode(&admin, 0o000);

    let hidden = guest::hidden_agents_md(&f.clone);
    let rows = doctor::Doctor::at(&f.plane, &f.plane, false, false).run();
    mode(&admin, 0o755);

    assert!(!hidden.unsure.is_empty(), "{hidden:?}");
    let row = rows
        .iter()
        .find(|r| r.name == "hidden AGENTS.md")
        .expect("a row");
    assert_eq!(row.status, doctor::Status::Warn);
}

#[cfg(unix)]
#[test]
fn an_agents_md_charter_cannot_look_at_is_a_doubt() {
    charter_core::unsteered!();
    let f = plane();
    let piece = cut(&f, "p1");
    let sibling = cut(&f, "p2");
    start::layered_or_refusal(&piece, &f.plane, Some("ops")).unwrap();
    mode(&sibling, 0o600);

    let hidden = guest::hidden_agents_md(&piece);
    mode(&sibling, 0o755);

    assert!(
        hidden
            .unsure
            .iter()
            .any(|why| why.contains(&sibling.display().to_string())),
        "{hidden:?}"
    );
}

#[cfg(unix)]
#[test]
fn a_recorded_agents_md_charter_cannot_read_is_a_doubt_not_charters() {
    charter_core::unsteered!();
    let f = plane();
    let piece = cut(&f, "p1");
    start::layered_or_refusal(&piece, &f.plane, Some("ops")).unwrap();
    let file = piece.join("AGENTS.md");
    mode(&file, 0o000);

    let hidden = guest::hidden_agents_md(&piece);
    mode(&file, 0o644);

    assert!(
        hidden
            .unsure
            .iter()
            .any(|why| why.contains(&file.display().to_string())),
        "{hidden:?}"
    );
}

#[cfg(unix)]
#[test]
fn workspaces_doctor_cannot_read_are_a_warning_not_a_missing_row() {
    charter_core::unsteered!();
    let f = plane();
    let workspaces = f.plane.join("workspaces");
    mode(&workspaces, 0o000);
    let rows = doctor::Doctor::at(&f.plane, &f.plane, false, false).run();
    mode(&workspaces, 0o755);
    let row = rows
        .iter()
        .find(|r| r.name == "hidden AGENTS.md")
        .expect("a row");
    assert_eq!(row.status, doctor::Status::Warn);

    let ws = f.workspace();
    mode(&ws, 0o000);
    let rows = doctor::Doctor::at(&f.plane, &f.plane, false, false).run();
    mode(&ws, 0o755);
    let row = rows
        .iter()
        .find(|r| r.name == "hidden AGENTS.md")
        .expect("a row");
    assert_eq!(row.status, doctor::Status::Warn);
    assert!(row.detail.contains("alpha"), "{}", row.detail);
}

// ---- NO-4: the operator's AGENTS.md gets its way out --------------------------------------

#[test]
fn a_start_names_the_branch_whose_agents_md_charters_line_hides() {
    charter_core::unsteered!();
    let (f, piece) = hidden_in_the_clone();
    with_a_profile(&f);

    let ready = start::ready(
        &start::Start {
            profile: Some("work".into()),
            persona: Some("ops".into()),
            name: "1".into(),
            cwd: Some(piece),
            ..Default::default()
        },
        &f.plane,
    )
    .expect("it starts");

    assert_eq!(
        ready.agents_md,
        vec![start::TheirAgentsMd {
            workspace: "alpha".into(),
            repo: "svc".into(),
            piece: None,
        }]
    );
}

#[test]
fn move_aside_puts_the_operators_agents_md_where_git_status_shows_it() {
    charter_core::unsteered!();
    let (f, _piece) = hidden_in_the_clone();

    let moved = guest::move_agents_md_aside(&f.plane, files::Branch::repo("alpha", "svc"))
        .expect("it is moved");

    assert_eq!(moved, "AGENTS.aside.md");
    assert!(!f.clone.join("AGENTS.md").exists());
    assert_eq!(
        read(&f.clone.join("AGENTS.aside.md")),
        "# the operator's, made later\n"
    );
    assert_eq!(
        f.status(&f.clone),
        "?? AGENTS.aside.md\n",
        "no longer hidden"
    );
}

#[test]
fn move_aside_never_moves_onto_a_file_already_there() {
    charter_core::unsteered!();
    let (f, _piece) = hidden_in_the_clone();
    std::fs::write(f.clone.join("AGENTS.aside.md"), "an earlier one\n").unwrap();

    let moved = guest::move_agents_md_aside(&f.plane, files::Branch::repo("alpha", "svc"))
        .expect("it is moved");

    assert_eq!(moved, "AGENTS.aside-2.md");
    assert_eq!(read(&f.clone.join("AGENTS.aside.md")), "an earlier one\n");
    assert_eq!(
        read(&f.clone.join("AGENTS.aside-2.md")),
        "# the operator's, made later\n"
    );
}

#[test]
fn move_aside_refuses_charters_own_agents_md_and_touches_nothing() {
    charter_core::unsteered!();
    let f = plane();
    let piece = cut(&f, "p1");
    start::layered_or_refusal(&piece, &f.plane, Some("ops")).expect("charter writes its own");
    let before = read(&piece.join("AGENTS.md"));

    let refused = guest::move_agents_md_aside(&f.plane, files::Branch::piece("alpha", "svc", "p1"))
        .expect_err("not the operator's");

    assert!(refused.contains("charter wrote"), "{refused}");
    assert_eq!(read(&piece.join("AGENTS.md")), before);
    assert!(!piece.join("AGENTS.aside.md").exists());
}

#[test]
fn move_aside_refuses_a_tracked_agents_md() {
    charter_core::unsteered!();
    let f = plane();
    std::fs::write(f.clone.join("AGENTS.md"), "committed\n").unwrap();
    support::git(&f.clone, &["add", "AGENTS.md"]);
    support::git(&f.clone, &["commit", "-q", "-m", "agents"]);

    let refused = guest::move_agents_md_aside(&f.plane, files::Branch::repo("alpha", "svc"))
        .expect_err("a tracked file is the repository's");

    assert!(refused.contains("tracks"), "{refused}");
    assert_eq!(read(&f.clone.join("AGENTS.md")), "committed\n");
}

#[test]
fn the_operators_agents_md_opens_in_their_editor_though_charters_line_hides_it() {
    charter_core::unsteered!();
    let (f, _piece) = hidden_in_the_clone();

    let launch = guest::their_agents_md_in_your_editor(
        &f.plane,
        files::Branch::repo("alpha", "svc"),
        charter_core::youreditor::Editor::VsCode,
        &|_| None,
    )
    .expect("it opens");

    let charter_core::youreditor::Launch::Url(url) = launch else {
        panic!("a URL: {launch:?}")
    };
    assert!(url.ends_with("svc/AGENTS.md:1:1"), "{url}");
}

/// Both of NO-4's actions on the clone's `AGENTS.md`, as their refusals, or a panic naming
/// which one went through.
fn both_refused(f: &support::Fixture) -> (String, String) {
    let open = guest::their_agents_md_in_your_editor(
        &f.plane,
        files::Branch::repo("alpha", "svc"),
        charter_core::youreditor::Editor::VsCode,
        &|_| None,
    )
    .expect_err("Open file is refused");
    let moved = guest::move_agents_md_aside(&f.plane, files::Branch::repo("alpha", "svc"))
        .expect_err("Move aside is refused");
    (open, moved)
}

#[test]
fn an_agents_md_hidden_by_the_operators_own_rule_is_neither_opened_nor_moved() {
    charter_core::unsteered!();
    let f = plane();
    std::fs::write(f.clone.join(".gitignore"), "AGENTS.md\n").unwrap();
    std::fs::write(f.clone.join("AGENTS.md"), "# mine\n").unwrap();

    let (open, moved) = both_refused(&f);

    assert!(open.contains("charter's"), "{open}");
    assert!(moved.contains("charter's"), "{moved}");
    assert_eq!(read(&f.clone.join("AGENTS.md")), "# mine\n");
    assert!(!f.clone.join("AGENTS.aside.md").exists());
}

#[test]
fn an_agents_md_the_operators_rule_also_hides_is_theirs_to_handle() {
    charter_core::unsteered!();
    // Charter's line is there too, but the operator's `.gitignore` is the rule git applies.
    let (f, _piece) = hidden_in_the_clone();
    std::fs::write(f.clone.join(".gitignore"), "AGENTS.md\n").unwrap();

    both_refused(&f);

    assert_eq!(
        read(&f.clone.join("AGENTS.md")),
        "# the operator's, made later\n"
    );
}

#[test]
fn an_agents_md_nothing_hides_is_not_this_exceptions() {
    charter_core::unsteered!();
    let f = plane();
    std::fs::write(f.clone.join("AGENTS.md"), "# shows in git status\n").unwrap();

    both_refused(&f);

    assert!(f.clone.join("AGENTS.md").exists());
}

#[cfg(unix)]
#[test]
fn a_linked_agents_md_is_neither_opened_nor_moved() {
    charter_core::unsteered!();
    let (f, _piece) = hidden_in_the_clone();
    std::fs::remove_file(f.clone.join("AGENTS.md")).unwrap();
    std::fs::write(f.clone.join("notes.md"), "elsewhere\n").unwrap();
    std::os::unix::fs::symlink("notes.md", f.clone.join("AGENTS.md")).unwrap();

    both_refused(&f);

    assert!(
        f.clone
            .join("AGENTS.md")
            .symlink_metadata()
            .unwrap()
            .file_type()
            .is_symlink()
    );
    assert!(!f.clone.join("AGENTS.aside.md").exists());
}

#[cfg(unix)]
#[test]
fn an_agents_md_with_a_second_name_is_neither_opened_nor_moved() {
    charter_core::unsteered!();
    let (f, _piece) = hidden_in_the_clone();
    std::fs::remove_file(f.clone.join("AGENTS.md")).unwrap();
    std::fs::write(f.clone.join(".gitignore"), ".env\n").unwrap();
    std::fs::write(f.clone.join(".env"), "TOKEN=x\n").unwrap();
    std::fs::hard_link(f.clone.join(".env"), f.clone.join("AGENTS.md")).unwrap();

    let (open, _moved) = both_refused(&f);

    assert!(open.contains("name"), "{open}");
    assert!(f.clone.join("AGENTS.md").exists());
}

#[test]
fn move_aside_reaches_the_operators_agents_md_in_a_sibling_piece() {
    charter_core::unsteered!();
    let f = plane();
    let piece = cut(&f, "p1");
    let sibling = cut(&f, "p2");
    start::layered_or_refusal(&piece, &f.plane, Some("ops")).unwrap();
    std::fs::write(sibling.join("AGENTS.md"), "# mine, in p2\n").unwrap();

    let moved = guest::move_agents_md_aside(&f.plane, files::Branch::piece("alpha", "svc", "p2"))
        .expect("charter's line is what hides it");

    assert_eq!(moved, "AGENTS.aside.md");
    assert_eq!(read(&sibling.join("AGENTS.aside.md")), "# mine, in p2\n");
}
