#!/usr/bin/env python3
"""Regenerate `crates/charter-core/src/tui/tables.rs` from CPython's own `unicodedata`.

Every Unicode table the core carries is generated here, because the core has exactly one
Unicode question per table and two hand-written answers to one question is how the two
implementations come to render one line differently.

Four tables, from three questions charter's Python asks:

* `charter/tui.py:_char_width` — how many cells does this character claim?

      if ch < "\\x80":                 return 1
      if unicodedata.combining(ch):   return 0
      return 2 if unicodedata.east_asian_width(ch) in ("W", "F") else 1

* `charter/contain.py:one_line` — has this character no glyph, so that printing it could
  restructure a line of a report?

      unicodedata.category(ch) in {"Cc", "Cf", "Cs", "Zl", "Zp"} or (ch.isspace() and ch != " ")

* `repr()` — would Python escape this character rather than print it?

      not ch.isprintable()

The Rust port must answer each of them the same way for every codepoint, and the only source
that cannot drift from Python is Python. So the ranges are *generated from the oracle* rather
than taken from a crate with its own opinion (`unicode-width` deviates deliberately: it widens
emoji presentation sequences and zeroes default-ignorables, neither of which
`east_asian_width` says).

Run it with a CPython whose Unicode version is the one the header of `tables.rs` names (the
recorded answers in `tests/fixtures/recorded/` were taken under it, ADR 0046), and paste the
output into `crates/charter-core/src/tui/tables.rs`. The header line records which Unicode
version the tables are of, so a future reader can tell whether a disagreement is a bug or a
version. It is a generator for a checked-in file, run by hand: nothing in CI or in a build runs
it.

    python3 tools/gen-unicode-tables.py > crates/charter-core/src/tui/tables.rs
    rustfmt --edition 2024 crates/charter-core/src/tui/tables.rs

The `rustfmt` is not optional: CI checks formatting over every file, generated or not, and
this one prints four ranges to a line where `rustfmt` wants one.
"""

import sys
import unicodedata


def ranges(pred, first=0x80):
    """`pred` as inclusive ranges, from `first` up.

    The surrogates are never asked: `chr(0xD800)` is a `str` in CPython and is not a `char`
    in Rust at all, so whatever Python says about one is unreachable from the port. They are
    reported as False and so split a range, which is why WIDE and COMBINING — which start
    above them — read the same as before this note was written.
    """
    out, start, prev = [], None, None
    for cp in range(first, 0x110000):
        ok = False if 0xD800 <= cp <= 0xDFFF else pred(chr(cp))
        if ok:
            if start is None:
                start = cp
            prev = cp
        elif start is not None:
            out.append((start, prev))
            start = None
    if start is not None:
        out.append((start, prev))
    return out


def fmt(name, rs):
    lines = [f"pub static {name}: [(u32, u32); {len(rs)}] = ["]
    row = []
    for a, b in rs:
        row.append(f"(0x{a:04X}, 0x{b:04X}),")
        if len(row) == 4:
            lines.append("    " + " ".join(row))
            row = []
    if row:
        lines.append("    " + " ".join(row))
    lines.append("];")
    return "\n".join(lines)


wide = ranges(lambda c: unicodedata.east_asian_width(c) in ("W", "F"))
comb = ranges(lambda c: unicodedata.combining(c) != 0)
# From 0, not from 0x80: these two decide about the ASCII controls, which are the characters
# that can actually forge a line, and about DEL.
invisible = ranges(
    lambda c: unicodedata.category(c) in {"Cc", "Cf", "Cs", "Zl", "Zp"}
    or (c.isspace() and c != " "),
    first=0,
)
nonprintable = ranges(lambda c: not c.isprintable(), first=0)

print(f"//! Generated by `tools/gen-unicode-tables.py` from Unicode {unicodedata.unidata_version}.")
print("//!")
print("//! Do not hand-edit: regenerate, so the tables and the oracle stay one answer.")
print()
print("/// Codepoints whose `east_asian_width` is `W` or `F` — two terminal cells.")
print(fmt("WIDE", wide))
print()
print("/// Codepoints with a non-zero canonical combining class — zero terminal cells.")
print(fmt("COMBINING", comb))
print()
print("/// Codepoints `charter/contain.py`'s `one_line` replaces with an escape: general")
print("/// category `Cc`, `Cf`, `Cs`, `Zl` or `Zp`, or `str.isspace()` and not the space.")
print(fmt("INVISIBLE", invisible))
print()
print("/// Codepoints `str.isprintable()` is false for, which is what `repr()` escapes:")
print("/// `Cc`, `Cf`, `Cs`, `Co`, `Cn`, `Zl`, `Zp` and `Zs` other than the space.")
print(fmt("NONPRINTABLE", nonprintable))
print()
print(f"wide={len(wide)} combining={len(comb)} invisible={len(invisible)} "
      f"nonprintable={len(nonprintable)}", file=sys.stderr)
