#!/usr/bin/env python3
"""Regenerate `crates/charter-core/src/tui/tables.rs` from CPython's own `unicodedata`.

`charter/tui.py:_char_width` is three questions and two of them are Unicode table lookups:

    if ch < "\x80":                 return 1
    if unicodedata.combining(ch):   return 0
    return 2 if unicodedata.east_asian_width(ch) in ("W", "F") else 1

The Rust port must answer them the same way for every codepoint, and the only source that
cannot drift from Python is Python. So the ranges are *generated from the oracle* rather
than taken from a crate with its own opinion (`unicode-width` deviates deliberately: it
widens emoji presentation sequences and zeroes default-ignorables, neither of which
`east_asian_width` says).

Run it with the same CPython the differential oracle runs on, and paste the output into
`crates/charter-core/src/tui/tables.rs`. The header line records which Unicode version the
tables are of, so a future reader can tell whether a disagreement is a bug or a version.
"""

import sys
import unicodedata


def ranges(pred):
    out, start, prev = [], None, None
    for cp in range(0x80, 0x110000):
        ok = False if 0xD800 <= cp <= 0xDFFF else pred(chr(cp))
        if ok:
            if start is None:
                start = cp
            prev = cp
        elif start is not None:
            out.append((start, prev))
            start = None
    if start is not None:
        out.append((start, prev))
    return out


def fmt(name, rs):
    lines = [f"pub static {name}: [(u32, u32); {len(rs)}] = ["]
    row = []
    for a, b in rs:
        row.append(f"(0x{a:04X}, 0x{b:04X}),")
        if len(row) == 4:
            lines.append("    " + " ".join(row))
            row = []
    if row:
        lines.append("    " + " ".join(row))
    lines.append("];")
    return "\n".join(lines)


wide = ranges(lambda c: unicodedata.east_asian_width(c) in ("W", "F"))
comb = ranges(lambda c: unicodedata.combining(c) != 0)
print(f"//! Generated by `tools/gen-width-tables.py` from Unicode {unicodedata.unidata_version}.")
print("//!")
print("//! Do not hand-edit: regenerate, so the tables and the oracle stay one answer.")
print()
print("/// Codepoints whose `east_asian_width` is `W` or `F` — two terminal cells.")
print(fmt("WIDE", wide))
print()
print("/// Codepoints with a non-zero canonical combining class — zero terminal cells.")
print(fmt("COMBINING", comb))
print(f"wide={len(wide)} combining={len(comb)}", file=sys.stderr)
