// charter's opencode plugin, generated by charter. Do not edit.
// The app loads this file for one chat, and names its own `charter` in the chat's environment.
//
// No policy lives here. Each tool call goes to the `charter hook` word that guards it, with
// the payload a Claude Code hook gets, and every decision is charter's. A tool call is
// refused by throwing: opencode then runs nothing and hands the model the message.
//
// A guard that cannot answer does not allow. A `charter` that is missing, crashed, timed out
// or said something this cannot read refuses the call, as charter's own guard refuses when
// it crashes.

const BINARY = process.env.CHARTER_HOOK_BINARY || ""

const ROUTES = {
  "bash": {
    "name": "Bash",
    "pre": "pretooluse",
    "post": null
  },
  "read": {
    "name": "Read",
    "pre": "pretooluse-read",
    "post": null
  },
  "grep": {
    "name": "Grep",
    "pre": "pretooluse-read",
    "post": null
  },
  "glob": {
    "name": "Glob",
    "pre": null,
    "post": null
  },
  "write": {
    "name": "Write",
    "pre": "pretooluse-edit",
    "post": "posttooluse"
  },
  "edit": {
    "name": "Edit",
    "pre": "pretooluse-edit",
    "post": "posttooluse"
  },
  "task": {
    "name": "Task",
    "pre": "pretooluse-dispatch",
    "post": "posttooluse-dispatch"
  },
  "skill": {
    "name": "Skill",
    "pre": null,
    "post": "posttooluse-skill"
  },
  "webfetch": {
    "name": "WebFetch",
    "pre": null,
    "post": null
  }
}

const TIMEOUTS = {"sessionstart":5,"userpromptsubmit":5,"pretooluse":10,"pretooluse-read":5,"pretooluse-edit":5,"pretooluse-dispatch":5,"posttooluse":5,"posttooluse-skill":5,"posttooluse-dispatch":5,"posttooluse-message":5,"notification":5,"stop":5,"subagentstop":5,"sessionend":5}

const DEFAULT_PRE = "pretooluse"

const EFFECTFUL = ["bash","edit","write"]

// Taken when this file loads, so a plugin loaded after it that replaces one of these does not
// reach the guard. opencode loads every plugin into one realm; this narrows that and does not
// close it (charter reports the other plugins opencode loads).
const hasOwn = Object.hasOwn
const parse = JSON.parse
const stringify = JSON.stringify
const spawn = Bun.spawn
const env = { ...process.env }

// A table is asked for its OWN key, so a tool id such as `constructor` or `toString` is not
// found on the prototype and routed to a function.
const route = (tool, field) => {
  if (typeof tool !== "string" || !hasOwn(ROUTES, tool)) return undefined
  const value = ROUTES[tool][field]
  return typeof value === "string" ? value : undefined
}

const toolId = (input) => (typeof input?.tool === "string" ? input.tool : "")

// What a hook said, as its JSON, or `undefined` for nothing or for something unreadable.
const answer = (said) => {
  const text = said.out.trim()
  if (!text) return null
  try {
    return parse(text)
  } catch {
    return undefined
  }
}

// The context a hook asked to add to the conversation, or "".
const context = (said) => {
  if (said.code !== 0) return ""
  const extra = answer(said)?.hookSpecificOutput?.additionalContext
  return typeof extra === "string" ? extra : ""
}

// Why a tool call is refused, or null when it may run.
const refusal = (said) => {
  if (said.code === 2) return said.err.trim() || "charter refused this tool call"
  if (said.code !== 0) {
    return `charter's guard could not answer (${said.err.trim() || `exit ${said.code}`}), and a guard that could not answer does not allow`
  }
  const got = answer(said)
  if (got === undefined) return "charter's guard answered something it cannot have meant, so this tool call is refused"
  const decision = got?.hookSpecificOutput
  if (decision?.permissionDecision !== "deny") return null
  return typeof decision.permissionDecisionReason === "string" && decision.permissionDecisionReason
    ? decision.permissionDecisionReason
    : "charter refused this tool call"
}

// Everything below is per opencode instance: one server may host several directories.
export const CharterPlugin = async (plugin) => {
  const directory = typeof plugin?.directory === "string" ? plugin.directory : process.cwd()

  // Sessions this process created, and each sub-agent session's parent: a sub-agent's events are
  // its chat's, and its prompts are not the operator's.
  const created = new Set()
  const started = new Set()
  const parents = new Map()

  const rootOf = (sid) => {
    let at = typeof sid === "string" ? sid : ""
    for (let hops = 0; parents.has(at) && hops < 64; hops++) at = parents.get(at)
    return at
  }

  // `charter hook <word>` with `payload` on stdin: its exit status, stdout and stderr.
  const run = async (word, payload, sid) => {
    if (!BINARY) return { code: -1, out: "", err: "no charter to run (CHARTER_HOOK_BINARY is not set)" }
    let child
    try {
      child = spawn([BINARY, "hook", word], {
        cwd: directory,
        env: { ...env, CHARTER_SESSION_ID: rootOf(sid) },
        stdin: new Blob([stringify(payload)]),
        stdout: "pipe",
        stderr: "pipe",
      })
    } catch (e) {
      return { code: -1, out: "", err: `could not start charter: ${e}` }
    }
    const seconds = hasOwn(TIMEOUTS, word) ? TIMEOUTS[word] : 10
    const timer = setTimeout(() => child.kill(), seconds * 1000)
    try {
      const [out, err, code] = await Promise.all([
        new Response(child.stdout).text(),
        new Response(child.stderr).text(),
        child.exited,
      ])
      return { code, out, err }
    } catch (e) {
      return { code: -1, out: "", err: String(e) }
    } finally {
      clearTimeout(timer)
    }
  }

  // Awaited before the tool runs; throwing is what refusing is.
  const before = async (input, output) => {
    const tool = toolId(input)
    const args = output?.args ?? {}
    const workdir = typeof args?.workdir === "string" && args.workdir ? args.workdir : directory
    const why = refusal(await run(route(tool, "pre") ?? DEFAULT_PRE, {
      hook_event_name: "PreToolUse",
      session_id: rootOf(input?.sessionID),
      cwd: tool === "bash" ? workdir : directory,
      tool_name: route(tool, "name") ?? tool,
      tool_input: args,
    }, input?.sessionID))
    if (why !== null) throw new Error(why)
  }

  return {
    // `$CHARTER_SESSION_ID` in every shell a tool opens, so a `charter` command run there
    // knows its conversation, as `$CLAUDE_CODE_SESSION_ID` tells it in a Claude Code chat.
    "shell.env": async (input, output) => {
      const sid = rootOf(input?.sessionID)
      if (sid && output?.env) output.env.CHARTER_SESSION_ID = sid
    },

    "tool.execute.before": before,

    // The tallies and nudges charter keeps after a tool ran. A note rides the tool's own
    // output, fenced, and only for a tool that reports an action rather than content.
    "tool.execute.after": async (input, output) => {
      const tool = toolId(input)
      const word = route(tool, "post")
      if (!word) return
      const said = await run(word, {
        hook_event_name: "PostToolUse",
        session_id: rootOf(input?.sessionID),
        cwd: directory,
        tool_name: route(tool, "name") ?? tool,
        tool_input: input?.args ?? {},
        tool_response: { output: String(output?.output ?? "") },
      }, input?.sessionID)
      const note = context(said)
      if (!note || !EFFECTFUL.includes(tool) || !output) return
      output.output = `${output.output ?? ""}\n\n--- charter ---\n${note}\n--- end charter ---`
    },

    // Once per prompt, before the model is asked. The session's first prompt is its start:
    // opencode creates a session at the first prompt and names no hook for it, so the
    // briefing is asked for here. What charter says rides the prompt as one more text part.
    "chat.message": async (input, output) => {
      const sid = input?.sessionID
      if (typeof sid !== "string" || parents.has(sid)) return
      const notes = []
      if (!started.has(sid)) {
        started.add(sid)
        notes.push(context(await run("sessionstart", {
          hook_event_name: "SessionStart",
          session_id: sid,
          cwd: directory,
          source: created.has(sid) ? "startup" : "resume",
        }, sid)))
      }
      const prompt = (output?.parts ?? [])
        .filter((part) => part?.type === "text" && typeof part.text === "string")
        .map((part) => part.text)
        .join("\n")
      notes.push(context(await run("userpromptsubmit", {
        hook_event_name: "UserPromptSubmit",
        session_id: sid,
        cwd: directory,
        prompt,
      }, sid)))
      const text = notes.filter(Boolean).join("\n\n")
      if (!text || !Array.isArray(output?.parts)) return
      output.parts.push({
        id: `prt_charter${Date.now().toString(36)}${Math.random().toString(36).slice(2)}`,
        sessionID: sid,
        messageID: output.message?.id,
        type: "text",
        text,
        synthetic: true,
      })
    },

    // What a turn does, as the app draws it. Not awaited: a report must never hold opencode up.
    event: async ({ event }) => {
      const props = event?.properties
      switch (event?.type) {
        case "session.created": {
          const info = props?.info
          if (typeof info?.id !== "string") return
          if (typeof info.parentID === "string") parents.set(info.id, info.parentID)
          else created.add(info.id)
          return
        }
        case "session.idle": {
          const sid = props?.sessionID
          if (typeof sid !== "string" || parents.has(sid)) return
          void run("stop", { hook_event_name: "Stop", session_id: sid, cwd: directory }, sid)
          return
        }
        case "permission.asked": {
          // A sub-agent's question is the chat's: the operator answers it in the same pane.
          const sid = rootOf(props?.sessionID)
          if (!sid) return
          void run("notification", {
            hook_event_name: "Notification",
            session_id: sid,
            cwd: directory,
            notification_type: "permission_prompt",
            message: `opencode asks permission to use ${String(props?.permission ?? "a tool")}`,
          }, sid)
          return
        }
      }
    },
  }
}
