"""The opencode plugin charter generates, and nothing else about opencode.

charter ships to PyPI; opencode loads JS/TS through Bun. Publishing an npm package would
add a third artifact with a third version number to a repo that has paid for version skew
in four of its last five releases, so `charter init` **writes** the plugin instead (ADR
0015). One artifact, one version, nothing to keep in sync.

The shim carries no policy. It answers one question — which harness is this — by putting
`$CHARTER_HARNESS` into every shell opencode spawns, so `harness.current()` has something
to read. Decisions stay in Python, where they are tested.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

from .. import __version__
from .base import Deficit, Harness

NAME = "opencode"

#: ``opencode tool id -> the tool name charter's guards match on``.
#:
#: charter's `PreToolUse` handler asks `tool_name == "Bash"` and reads
#: `tool_input["command"]`; opencode calls the same tool `bash`. Rather than keep a table
#: in TypeScript and another here, the mapping lives in Python and is generated into the
#: shim — the repo's own lesson that "if two paths answer the same question, call the same
#: function".
#:
#: A tool NOT in this map is forwarded under its own id. That is deliberate: charter's
#: guards ignore names they do not know, and inventing a CamelCase name for a tool charter
#: has never heard of would be guessing.
TOOL_NAMES = {
    "bash": "Bash",
    "read": "Read",
    "write": "Write",
    "edit": "Edit",
    "glob": "Glob",
    "grep": "Grep",
    "webfetch": "WebFetch",
    "task": "Task",
}

#: Tools whose output charter may append to. Deliberately NOT the ones that return
#: content: a `read` whose output carries charter's nudge is a false record of that file,
#: and the agent may write it back. These three report an action instead, so a note
#: appended to them adds to the record rather than corrupting it.
#:
#: Claude Code needs no such list — its `additionalContext` arrives BESIDE the result.
#: This restriction is the price of opencode having no channel of its own.
EFFECTFUL_TOOLS = ("bash", "edit", "write")

def global_dir() -> Path:
    """Where opencode reads plugins, commands and config for EVERY project.

    Verified by putting a probe in `~/.config/opencode/plugin/` and booting `opencode
    serve` from an unrelated directory, where it loaded. The per-tree design existed
    because opencode does not walk upwards for *project* plugins — true, and irrelevant
    once the plugin is installed where every project already looks.

    `$XDG_CONFIG_HOME` first, for the same reason `$CODEX_HOME` is honoured: writing to a
    path the tool does not read is indistinguishable from not installing at all.
    """
    xdg = os.environ.get("XDG_CONFIG_HOME")
    return (Path(xdg) if xdg else Path.home() / ".config") / "opencode"


#: Relative to :func:`global_dir`.
SHIM_PATH = Path("plugin") / "charter.ts"

#: The on-demand status line. opencode has no status-bar socket, so the plane state is a
#: command instead of an ambient row. `.opencode/command/<name>.md` is the location, from
#: the binary's own docs table: "Project commands | `.opencode/command/<name>.md`".
COMMAND_PATH = Path("command") / "charter.md"

#: A command body may embed shell output with ``!`…` ``, so `/charter` prints the REAL
#: status line. Describing it to a model instead would spend a turn to get a worse answer.
COMMAND = """\
---
description: The control plane — active workspace, open todos, pieces, repos and CI.
---

The control plane's current state:

!`echo '{}' | charter statusline`

Read it and continue; nothing here needs a reply.
"""

#: The session context, for the harness that has no SessionStart hook. Named in the
#: tree's ``instructions`` so opencode reads it at startup.
CONTEXT_PATH = Path("charter-context.md")

#: The generated plugin. No imports, deliberately: `@opencode-ai/plugin` exists only for
#: type checking, and depending on it would send Bun to the network before charter's own
#: hook can run — a failure that would look like charter being broken.
_SHIM_TEMPLATE = '''\
// charter-version: %(version)s
// Generated by `charter init`. Safe to edit: charter writes this file only when it is
// absent and never repairs one it finds, so your changes survive (ADR 0015).
//
// Charter is a Python CLI. This plugin holds no policy of its own — it names the harness
// to every shell, and forwards tool calls to `charter hook pretooluse`, which is the same
// handler Claude Code calls. Every decision stays in Python, where it has tests.
//
// `input` is read on every call rather than cached: one opencode server hosts many
// sessions, so a module-level "current session" would have no correct value.

const TOOL_NAMES = %(tool_names)s

const EFFECTFUL = %(effectful)s

export const CharterPlugin = async ({ $, directory }) => {
  return {
    "shell.env": async (input, output) => {
      output.env.CHARTER_HARNESS = "opencode"
      if (input?.sessionID) output.env.CHARTER_SESSION_ID = input.sessionID
    },

    // Awaited before the tool runs, and `Plugin.trigger` wraps each hook in
    // `Effect.promise` with no try/catch — so throwing here is what denial IS.
    "tool.execute.before": async (input, output) => {
      const payload = {
        hook_event_name: "PreToolUse",
        session_id: input?.sessionID ?? "",
        cwd: directory,
        tool_name: TOOL_NAMES[input?.tool] ?? input?.tool ?? "",
        tool_input: output?.args ?? {},
      }
      let parsed
      try {
        // `< ${blob}` is how Bun's shell takes stdin; there is no such
        // METHOD on it. An earlier version called one, threw on every tool
        // call, and failed OPEN silently — the guard never fired while
        // everything looked wired. Verified against opencode 1.18.18.
        const res = await $`charter hook pretooluse < ${new Blob([JSON.stringify(payload)])}`
          .env({ ...process.env, CHARTER_HARNESS: "opencode",
                 CHARTER_SESSION_ID: input?.sessionID ?? "" })
          .quiet()
          .nothrow()
        const out = res.stdout.toString().trim()
        parsed = out ? JSON.parse(out) : null
      } catch (e) {
        // Charter absent, or it answered something this cannot read. A guard that
        // cannot run must not block the session — `doctor` is what reports an unwired
        // plane, and failing open here is the difference between a missing guard and an
        // unusable harness.
        return
      }
      const decision = parsed?.hookSpecificOutput?.permissionDecision
      if (decision === "deny") {
        throw new Error(parsed?.hookSpecificOutput?.permissionDecisionReason
          ?? "charter denied this command")
      }
    },

    // charter's mid-session nudges. On Claude Code they arrive beside the result; here
    // there is no such channel, so they ride the result itself — and only for EFFECTFUL
    // tools, because a `read` carrying appended text is a false record of that file.
    "tool.execute.after": async (input, output) => {
      if (!EFFECTFUL.includes(input?.tool)) return
      const payload = {
        hook_event_name: "PostToolUse",
        session_id: input?.sessionID ?? "",
        cwd: directory,
        tool_name: TOOL_NAMES[input?.tool] ?? input?.tool ?? "",
        tool_input: input?.args ?? {},
        tool_response: { output: String(output?.output ?? "") },
      }
      let note
      try {
        // `< ${blob}` is how Bun's shell takes stdin; there is no such
        // METHOD on it. An earlier version called one, threw on every tool
        // call, and failed OPEN silently — the guard never fired while
        // everything looked wired. Verified against opencode 1.18.18.
        const res = await $`charter hook posttooluse < ${new Blob([JSON.stringify(payload)])}`
          .env({ ...process.env, CHARTER_HARNESS: "opencode",
                 CHARTER_SESSION_ID: input?.sessionID ?? "" })
          .quiet()
          .nothrow()
        const out = res.stdout.toString().trim()
        note = out ? JSON.parse(out)?.hookSpecificOutput?.additionalContext : null
      } catch (e) {
        return
      }
      if (!note) return
      // Fenced, so nothing here can be read back as the tool's own output.
      output.output = `${output?.output ?? ""}\n\n--- charter ---\n${note}\n--- end charter ---`
    },
  }
}
'''

#: The generated plugin. No imports beyond what opencode hands the factory, deliberately:
#: `@opencode-ai/plugin` exists only for type checking, and depending on it would send Bun
#: to the network before charter's own hook can run — a failure that would look like
#: charter being broken.
#: The marker `shim_version` reads. First line of the file, so the read is cheap and a
#: truncated file still answers honestly.
_STAMP = "// charter-version: "

SHIM = _SHIM_TEMPLATE % {
    "version": __version__,
    "tool_names": json.dumps(TOOL_NAMES, indent=2, sort_keys=True),
    "effectful": json.dumps(list(EFFECTFUL_TOOLS)),
}


def shim_version(tree: Path) -> str | None:
    """Which charter wrote the shim in *tree*, or ``None``.

    ``None`` covers three cases that must not be told apart optimistically: no shim, a
    shim from before the stamp existed, and one somebody rewrote. Each means "not
    something this charter can vouch for", and the dangerous one — a 0.40.0 plugin whose
    guard threw on every tool call and failed open — is exactly the middle case.
    """
    p = Path(tree) / SHIM_PATH
    try:
        head = p.read_text().splitlines()[0]
    except (OSError, UnicodeDecodeError, IndexError):
        return None
    return head[len(_STAMP):].strip() if head.startswith(_STAMP) else None


def refresh_shim(tree: Path) -> str:
    """Regenerate the shim in *tree* when charter can still recognise it as its own.

    ``"created"`` (absent), ``"refreshed"`` (charter's, replaced), ``"not-ours"`` (no
    stamp — left untouched), ``"current"`` (already this version).

    The stamp is what makes this safe. `ensure_shim` may never repair, because it cannot
    ask whether the file is charter's; this can, and still refuses the moment the answer
    is no. An operator who edited the shim keeps their edit and gets told about it, which
    is the same trade `_load_settings` makes for a file charter half-owns.
    """
    p = Path(tree) / SHIM_PATH
    if not p.exists():
        return ensure_shim(tree) and "created"
    stamped = shim_version(tree)
    if stamped is None:
        return "not-ours"
    if stamped == __version__:
        return "current"
    p.write_text(SHIM)
    return "refreshed"


def ensure_shim(root: Path) -> str:
    """Write the plugin under *root* IF ABSENT. Returns ``"created"`` or ``"present"``.

    Never repairs a file it finds, which is `_load_settings`'s restraint for
    `.claude/settings.json` applied to a file charter has even less claim on: someone who
    edited the shim made a deliberate choice, and silently reverting it is worse than
    leaving a stale one — `doctor` is what notices staleness, and it can say why.
    """
    p = Path(root) / SHIM_PATH
    if p.exists():
        return "present"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(SHIM)
    return "created"


def write_context(base: Path) -> str:
    """Regenerate the session context under *base*. Always overwrites.

    The one generated file charter DOES repair, and the exception is the point: the shim
    is the operator's to edit, while this is derived state. A stale context file is a lie
    about which workspace you are standing in, and a lie is worse than a missing file
    because nothing about it looks wrong.
    """
    from .. import hooks

    p = Path(base) / CONTEXT_PATH
    p.parent.mkdir(parents=True, exist_ok=True)
    body = hooks.context_block(None).strip()
    p.write_text("<!-- Generated by charter. Do not edit: rewritten whenever the plane's "
                 "state changes. -->\n\n" + (body or "_No control-plane context._") + "\n")
    return "created"


def ensure_instructions(base: Path) -> str:
    """Name :data:`CONTEXT_PATH` in *base*'s ``opencode.json`` ``instructions``.

    IF ABSENT, and additively: opencode combines every entry, so somebody else's
    `AGENTS.md` keeps working beside charter's. An unparseable config is theirs to fix —
    charter reports and never repairs.
    """
    p = Path(base) / "opencode.json"
    doc: dict = {}
    if p.exists():
        try:
            doc = json.loads(p.read_text())
        except (OSError, UnicodeDecodeError, json.JSONDecodeError):
            return "malformed"
        if not isinstance(doc, dict):
            return "malformed"
    entries = doc.setdefault("instructions", [])
    if not isinstance(entries, list):
        return "malformed"
    want = str(Path(base) / CONTEXT_PATH)
    if want in entries:
        return "present"
    entries.append(want)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(doc, indent=2) + "\n")
    return "created"


class OpenCodeHarness(Harness):
    name = NAME

    deficits = (
        Deficit("status-bar",
                "no status-bar socket: opencode has no `statusLine` config, so the plane "
                "state renders on demand via `/charter` rather than ambiently.", "charter statusline --watch"),
        Deficit("prompt-hook",
                "no per-turn prompt hook: charter's mid-session nudges ride the output of "
                "effectful tools (write/edit/bash) instead of arriving beside them."),
    )

    def detect(self) -> bool:
        """Nothing native to detect.

        opencode sets no environment variable of its own that a shell can see —
        ``$CHARTER_HARNESS`` here comes from :data:`SHIM`, which is charter's own code.
        So an opencode session in an unwired plane is genuinely undetectable, and saying
        so is better than guessing from a path that might mean something else.
        """
        return False

    def wire(self, root: Path) -> list[tuple[str, str]]:
        """Install once, where opencode reads for every project.

        *root* is ignored: nothing is written into the plane. A plane is somebody's repo,
        and charter's housekeeping has no business in its `git status` — which is what the
        per-tree design cost, along with a `.git/info/exclude` entry per checkout to hide
        the evidence.
        """
        g = global_dir()
        out = [(ensure_shim(g), str(g / SHIM_PATH))]
        cmd = g / COMMAND_PATH
        if not cmd.exists():
            cmd.parent.mkdir(parents=True, exist_ok=True)
            cmd.write_text(COMMAND)
            out.append(("created", str(g / COMMAND_PATH)))
        write_context(g)
        if ensure_instructions(g) == "created":
            out.append(("created", f"{g / 'opencode.json'} (instructions)"))
        return out

    def ask_rule(self, pattern: str) -> tuple[str, str]:
        """``(tool, glob)``. opencode's permissions are `{tool: {pattern: decision}}` with
        `*`/`?` wildcards — not Claude Code's `Tool(pattern)` string, so the same operator
        sentence has to come apart differently here."""
        p = (pattern or "").strip()
        for oc_id, name in TOOL_NAMES.items():
            for prefix in (f"{name}(", f"{oc_id}("):
                if p.startswith(prefix) and p.endswith(")"):
                    return oc_id, p[len(prefix):-1]
        return "bash", p

    def apply_ask_rule(self, root: Path, pattern: str) -> tuple[str, str]:
        """Write it into `opencode.json`, IF ABSENT and never repairing.

        A `permission` block of the wrong shape is somebody's deliberate structure, and
        an unparseable file is theirs to fix — the same restraint `_load_settings` keeps
        for the file charter half-owns.
        """
        tool, glob = self.ask_rule(pattern)
        p = Path(root) / "opencode.json"
        doc: dict = {}
        if p.exists():
            try:
                doc = json.loads(p.read_text())
            except (OSError, UnicodeDecodeError, json.JSONDecodeError):
                return "malformed", str(p)
            if not isinstance(doc, dict):
                return "malformed", str(p)
        perms = doc.setdefault("permission", {})
        if not isinstance(perms, dict):
            return "malformed", f"{p} (`permission` is not an object)"
        block = perms.setdefault(tool, {})
        if not isinstance(block, dict):
            return "malformed", f"{p} (`permission.{tool}` is not an object)"
        if block.get(glob) == "ask":
            return "present", str(p)
        block[glob] = "ask"
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(json.dumps(doc, indent=2) + "\n")
        return "added", str(p)
