"""The opencode plugin charter generates, and nothing else about opencode.

charter ships to PyPI; opencode loads JS/TS through Bun. Publishing an npm package would
add a third artifact with a third version number to a repo that has paid for version skew
in four of its last five releases, so `charter init` **writes** the plugin instead (ADR
0015). One artifact, one version, nothing to keep in sync.

The shim carries no policy. It answers one question — which harness is this — by putting
`$CHARTER_HARNESS` into every shell opencode spawns, so `harness.current()` has something
to read. Decisions stay in Python, where they are tested.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

from .base import Deficit, Harness

NAME = "opencode"

#: ``opencode tool id -> the tool name charter's guards match on``.
#:
#: charter's `PreToolUse` handler asks `tool_name == "Bash"` and reads
#: `tool_input["command"]`; opencode calls the same tool `bash`. Rather than keep a table
#: in TypeScript and another here, the mapping lives in Python and is generated into the
#: shim — the repo's own lesson that "if two paths answer the same question, call the same
#: function".
#:
#: A tool NOT in this map is forwarded under its own id. That is deliberate: charter's
#: guards ignore names they do not know, and inventing a CamelCase name for a tool charter
#: has never heard of would be guessing.
TOOL_NAMES = {
    "bash": "Bash",
    "read": "Read",
    "write": "Write",
    "edit": "Edit",
    "glob": "Glob",
    "grep": "Grep",
    "webfetch": "WebFetch",
    "task": "Task",
}

#: Where opencode looks for project-local plugins.
SHIM_PATH = Path(".opencode") / "plugin" / "charter.ts"

#: The generated plugin. No imports, deliberately: `@opencode-ai/plugin` exists only for
#: type checking, and depending on it would send Bun to the network before charter's own
#: hook can run — a failure that would look like charter being broken.
_SHIM_TEMPLATE = '''\
// Generated by `charter init`. Safe to edit: charter writes this file only when it is
// absent and never repairs one it finds, so your changes survive (ADR 0015).
//
// Charter is a Python CLI. This plugin holds no policy of its own — it names the harness
// to every shell, and forwards tool calls to `charter hook pretooluse`, which is the same
// handler Claude Code calls. Every decision stays in Python, where it has tests.
//
// `input` is read on every call rather than cached: one opencode server hosts many
// sessions, so a module-level "current session" would have no correct value.

const TOOL_NAMES = %(tool_names)s

export const CharterPlugin = async ({ $, directory }) => {
  return {
    "shell.env": async (input, output) => {
      output.env.CHARTER_HARNESS = "opencode"
      if (input?.sessionID) output.env.CHARTER_SESSION_ID = input.sessionID
    },

    // Awaited before the tool runs, and `Plugin.trigger` wraps each hook in
    // `Effect.promise` with no try/catch — so throwing here is what denial IS.
    "tool.execute.before": async (input, output) => {
      const payload = {
        hook_event_name: "PreToolUse",
        session_id: input?.sessionID ?? "",
        cwd: directory,
        tool_name: TOOL_NAMES[input?.tool] ?? input?.tool ?? "",
        tool_input: output?.args ?? {},
      }
      let parsed
      try {
        const res = await $`charter hook pretooluse`
          .env({ ...process.env, CHARTER_HARNESS: "opencode",
                 CHARTER_SESSION_ID: input?.sessionID ?? "" })
          .stdin(new Response(JSON.stringify(payload)))
          .quiet()
          .nothrow()
        const out = res.stdout.toString().trim()
        parsed = out ? JSON.parse(out) : null
      } catch (e) {
        // Charter absent, or it answered something this cannot read. A guard that
        // cannot run must not block the session — `doctor` is what reports an unwired
        // plane, and failing open here is the difference between a missing guard and an
        // unusable harness.
        return
      }
      const decision = parsed?.hookSpecificOutput?.permissionDecision
      if (decision === "deny") {
        throw new Error(parsed?.hookSpecificOutput?.permissionDecisionReason
          ?? "charter denied this command")
      }
    },
  }
}
'''

#: The generated plugin. No imports beyond what opencode hands the factory, deliberately:
#: `@opencode-ai/plugin` exists only for type checking, and depending on it would send Bun
#: to the network before charter's own hook can run — a failure that would look like
#: charter being broken.
SHIM = _SHIM_TEMPLATE % {"tool_names": json.dumps(TOOL_NAMES, indent=2, sort_keys=True)}


def ensure_shim(root: Path) -> str:
    """Write the plugin under *root* IF ABSENT. Returns ``"created"`` or ``"present"``.

    Never repairs a file it finds, which is `_load_settings`'s restraint for
    `.claude/settings.json` applied to a file charter has even less claim on: someone who
    edited the shim made a deliberate choice, and silently reverting it is worse than
    leaving a stale one — `doctor` is what notices staleness, and it can say why.
    """
    p = Path(root) / SHIM_PATH
    if p.exists():
        return "present"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(SHIM)
    return "created"


def _exclude_locally(tree: Path) -> None:
    """Keep charter's generated plugin out of the repo's ``git status``, locally.

    ``.git/info/exclude`` rather than ``.gitignore``: the ignore file is the repo owners'
    to maintain and is committed, so charter editing it would push its own housekeeping
    into their history. The exclude file is untracked and per-checkout — the right place
    for "this checkout has a tool's file in it".

    **Git is asked where that file is, never told.** A linked worktree's ``.git`` is a
    *file* pointing into the clone, so testing it as a directory skipped the exclude for
    exactly the trees charter creates most — leaving the generated plugin as an untracked
    change, which made `charter worktree remove` refuse to remove a piece that had done
    nothing. ``--git-common-dir`` resolves to the clone's own git directory from a
    worktree and from the clone alike, so one exclude covers a clone and every worktree
    over it.

    Best-effort and silent. A tree that is not a checkout, a git that is missing, or a
    directory charter cannot write to still gets the plugin: failing to hide a file is
    not a reason to leave the harness unwired.
    """
    try:
        proc = subprocess.run(["git", "-C", str(tree), "rev-parse", "--git-common-dir"],
                              capture_output=True, text=True, timeout=10)
        if proc.returncode != 0:
            return
        common = Path((proc.stdout or "").strip())
        if not common.is_absolute():
            common = Path(tree) / common
        info = common / "info"
        info.mkdir(parents=True, exist_ok=True)
        p = info / "exclude"
        raw = p.read_text() if p.exists() else ""
        if ".opencode/" in raw:
            return
        sep = "" if (not raw or raw.endswith("\n")) else "\n"
        p.write_text(f"{raw}{sep}# charter's generated opencode plugin\n.opencode/\n")
    except (OSError, ValueError, subprocess.SubprocessError):
        return


class OpenCodeHarness(Harness):
    name = NAME

    deficits = (
        Deficit("status-bar",
                "no status-bar socket: opencode has no `statusLine` config, so the plane "
                "state renders on demand via `/charter` rather than ambiently."),
        Deficit("prompt-hook",
                "no per-turn prompt hook: charter's mid-session nudges ride the output of "
                "effectful tools (write/edit/bash) instead of arriving beside them."),
    )

    def detect(self) -> bool:
        """Nothing native to detect.

        opencode sets no environment variable of its own that a shell can see —
        ``$CHARTER_HARNESS`` here comes from :data:`SHIM`, which is charter's own code.
        So an opencode session in an unwired plane is genuinely undetectable, and saying
        so is better than guessing from a path that might mean something else.
        """
        return False

    def wire(self, root: Path) -> list[tuple[str, str]]:
        return [(ensure_shim(root), str(SHIM_PATH))]

    def wire_tree(self, tree: Path) -> list[tuple[str, str]]:
        """The plugin, plus a local exclude so it stays out of the repo's `git status`.

        opencode reads plugins from the session's own directory and **does not walk
        upwards** — so this, not :meth:`wire`, is what actually arms charter where work
        happens. The plane-root copy stays for the rare session started there.
        """
        status = ensure_shim(tree)
        _exclude_locally(tree)
        return [(status, f"{tree.name}/{SHIM_PATH}")]

    def wire_tree_missing(self, tree: Path) -> bool:
        return not (Path(tree) / SHIM_PATH).is_file()

    def ask_rule(self, pattern: str) -> tuple[str, str]:
        """``(tool, glob)``. opencode's permissions are `{tool: {pattern: decision}}` with
        `*`/`?` wildcards — not Claude Code's `Tool(pattern)` string, so the same operator
        sentence has to come apart differently here."""
        p = (pattern or "").strip()
        for oc_id, name in TOOL_NAMES.items():
            for prefix in (f"{name}(", f"{oc_id}("):
                if p.startswith(prefix) and p.endswith(")"):
                    return oc_id, p[len(prefix):-1]
        return "bash", p

    def apply_ask_rule(self, root: Path, pattern: str) -> tuple[str, str]:
        """Write it into `opencode.json`, IF ABSENT and never repairing.

        A `permission` block of the wrong shape is somebody's deliberate structure, and
        an unparseable file is theirs to fix — the same restraint `_load_settings` keeps
        for the file charter half-owns.
        """
        tool, glob = self.ask_rule(pattern)
        p = Path(root) / "opencode.json"
        doc: dict = {}
        if p.exists():
            try:
                doc = json.loads(p.read_text())
            except (OSError, UnicodeDecodeError, json.JSONDecodeError):
                return "malformed", str(p)
            if not isinstance(doc, dict):
                return "malformed", str(p)
        perms = doc.setdefault("permission", {})
        if not isinstance(perms, dict):
            return "malformed", f"{p} (`permission` is not an object)"
        block = perms.setdefault(tool, {})
        if not isinstance(block, dict):
            return "malformed", f"{p} (`permission.{tool}` is not an object)"
        if block.get(glob) == "ask":
            return "present", str(p)
        block[glob] = "ask"
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(json.dumps(doc, indent=2) + "\n")
        return "added", str(p)
