#!/usr/bin/env python3
"""Compose GitHub's social preview from the real status line render.

The card is the most-seen asset in the repo and the least-read: it is what renders when a
link is pasted into Reddit, Slack or X, where a thousand people see it and fifty click
through. It used to be a hand drawing — a wordmark and three nouns — which made it the one
piece of the first impression that could not go stale, because it said nothing specific
enough to be wrong.

It also said nothing *convincing*. The single best argument charter has is the status line,
and the card did not show it. So the card now embeds `statusline.svg` directly: the same
generated bytes the README shows, cropped to its top rows and bled off the bottom edge.
Regenerate the status line and the card follows, which is the whole reason this is a script
and not an SVG anyone edits.

Stdlib only, like `ansi2svg.py` — regenerating an asset must never need a toolchain.

    python3 docs/assets/social-card.py        # → docs/assets/social-card.svg

Then rasterize for upload; GitHub stores the preview separately and has no API for it, so
the PNG is committed to make that manual step reproducible. See this directory's README.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

#: GitHub renders the preview at 2:1. 1280×640 is its recommended size.
W, H = 1280, 640

#: How much of the status line to show, in its own user units (it is 380 tall). Cropping
#: rather than scaling the whole thing keeps the type legible at thumbnail size — a full
#: render shrunk to fit is mush at the size most people actually see this.
CROP = 296.0

#: Where the crop sits. It bleeds off the bottom edge on purpose: a card that shows the
#: whole frame reads as a screenshot of a window, and one that runs off the edge reads as
#: a surface continuing past it.
INSET = 72
PANEL_Y = 336

#: How tall the bottom fade is. The footer sits on it, so it has to reach near-solid
#: *above* that baseline — a shorter fade leaves the URL sitting on live terminal rows,
#: where it is simply unreadable. Full card width, because a fade that stops at the panel
#: edge draws a seam exactly where the eye is looking for the footer.
FADE = 190

BG = "#0d1117"
FG = "#e6edf3"
MUTED = "#8b949e"
DIM = "#6e7681"
CYAN = "#39c5cf"


def statusline_body() -> tuple[str, float, float]:
    """The inner markup of `statusline.svg`, plus the viewBox it was drawn against.

    Read rather than re-derived: this asset must show the same bytes the README shows, and
    a second render path is a second thing that can disagree with the first.
    """
    svg = (HERE / "statusline.svg").read_text()
    m = re.match(r'<svg[^>]*viewBox="([\d.]+) ([\d.]+) ([\d.]+) ([\d.]+)"[^>]*>(.*)</svg>\s*\Z',
                 svg, re.S)
    if not m:
        sys.exit("statusline.svg is not in the shape ansi2svg.py emits — regenerate it first")
    return m.group(5), float(m.group(3)), float(m.group(4))


def build() -> str:
    body, vw, vh = statusline_body()
    if CROP > vh:
        sys.exit(f"CROP={CROP} exceeds the render's own height ({vh})")

    panel_w = W - INSET * 2
    panel_h = panel_w * CROP / vw

    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}"
     role="img" aria-label="charter — a control plane for coding agents across many repos: durable personas, per-task workspaces, and a credential vault the model never reads from. Below the wordmark, charter's real status line showing the active task, its repos and their branches.">
  <style>
    .mono {{ font-family: ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, 'DejaVu Sans Mono', monospace; }}
  </style>
  <defs>
    <linearGradient id="fade" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="{BG}" stop-opacity="0"/>
      <stop offset="0.62" stop-color="{BG}" stop-opacity="0.94"/>
      <stop offset="1" stop-color="{BG}" stop-opacity="1"/>
    </linearGradient>
    <clipPath id="crop">
      <rect x="{INSET}" y="{PANEL_Y}" width="{panel_w}" height="{H - PANEL_Y}"/>
    </clipPath>
  </defs>

  <rect width="{W}" height="{H}" fill="{BG}"/>

  <text class="mono" x="{INSET}" y="150" font-size="76" font-weight="700" fill="{FG}">
    <tspan fill="{CYAN}">⬢</tspan> charter
  </text>
  <text class="mono" x="{INSET + 4}" y="206" font-size="27" fill="{MUTED}">A control plane for coding agents working across many repos</text>

  <g class="mono" font-size="24">
    <text x="{INSET + 4}" y="266" fill="#bc8cff">personas</text>
    <text x="{INSET + 128}" y="266" fill="{DIM}">·</text>
    <text x="{INSET + 154}" y="266" fill="#58a6ff">workspaces</text>
    <text x="{INSET + 306}" y="266" fill="{DIM}">·</text>
    <text x="{INSET + 332}" y="266" fill="{CYAN}">worktrees</text>
    <text x="{INSET + 470}" y="266" fill="{DIM}">·</text>
    <text x="{INSET + 496}" y="266" fill="#d29922">a vault the model never reads</text>
  </g>

  <!-- The argument itself: the same render the README leads with, cropped and bled. -->
  <g clip-path="url(#crop)">
    <svg x="{INSET}" y="{PANEL_Y}" width="{panel_w}" height="{panel_h:.2f}"
         viewBox="0 0 {vw} {CROP}" preserveAspectRatio="xMidYMin slice">{body}</svg>
  </g>
  <rect x="0" y="{H - FADE}" width="{W}" height="{FADE}" fill="url(#fade)"/>

  <text class="mono" x="{INSET}" y="{H - 26}" font-size="22" fill="{DIM}">github.com/diazoxide/charter</text>
  <text class="mono" x="{W - INSET}" y="{H - 26}" font-size="22" text-anchor="end" fill="{DIM}">MIT · uv tool install charter-cp</text>
</svg>
'''


if __name__ == "__main__":
    out = HERE / "social-card.svg"
    out.write_text(build())
    print(f"{out.relative_to(Path.cwd()) if out.is_relative_to(Path.cwd()) else out}")
